### ISSUE TITLE
Odoo 10 web page Defomed

### ISSUE THREAD

**Issue by YahiaZZ** [Yenthe666/InstallScript#100]
Hi,
I installed Odoo v10 in Ubuntu 15.10, (it said that is succesfully installed), but when I want to access via Web page I have this error
`could not execute command 'lessc'`
I have lessc installed (`lessc 3.0.1 (Less Compiler) [JavaScript]`)
and it doesn't display any icons
Please could you see this print screen
![image](https://user-images.githubusercontent.com/13751183/39703857-7cfab4d2-5201-11e8-9926-baae68dc1693.png)

Thanks

**Comment by Yenthe666** [comment]
Hi @YahiaZZ,

It is actually correct installed, there are just issues with the compilation of the assets. Is there any error in your log or not? What happens if you run your Odoo with `?debug=assets` in the URL?

**Comment by YahiaZZ** [comment]
Hi @Yenthe666 
Thank you for your quick answer
The only error was` odoo.addons.base.ir.ir_qweb.assetsbundle: Could not execute command 'lessc'`
When i add `?debug=assets`, it gives the same page
Thanks again

**Comment by Yenthe666** [comment]
What do you get back when you enter `node --version` in a terminal?

**Comment by YahiaZZ** [comment]
It returns 
```
root:~# node --version
v8.11.1
```

**Comment by YahiaZZ** [comment]
Hi,
Please, What is the appropriate Node version for odoo 10?

Thanks

**Comment by Yenthe666** [comment]
I was just checking because I was curious it was correctly installed and working etc.
Please delete all your assets and let Odoo recompile them again.

**Comment by YahiaZZ** [comment]
Hi @Yenthe666 
The `?debug=assets` give me now:

`Loading failed for the <script> with source “http://x.x.x.x:8069/web/static/src/js/web_client.js”.`
