### ISSUE TITLE
Error: Unable to find Wkhtmltopdf on this system. The report will be shown in html.

### ISSUE THREAD

**Issue by thite** [Yenthe666/InstallScript#102]
The odoo cannot generate PDF. Even if you re-install Wkhtmltopdf properly, yet it will generate a PDF which is empty, of either 0 bytes of 409 (maybe 406) bytes.
This problem can occur if we install Odoo 11 on Ubuntu 18 LTS with this script.
You try installing Odoo 11 with the same script on Ubuntu 16 LTS, and it shall work perfectly !!!
The issue needs to be resolved, to work with any Ubuntu version.

**Comment by Yenthe666** [comment]
Hi @thite,

This is actually a known bug in Ubuntu 18 in combination with Wkhtmltopdf as there is no out of the box wkhtmltopdf version available at the moment.
See https://github.com/odoo/odoo/issues/21255 and https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3898 - for now we have to wait a bit

**Comment by thite** [comment]
Ok, thanks. When do you expect the issue to be resolved?

**Comment by Yenthe666** [comment]
Hmm not sure at the moment. I either have to figure out a way to download them and add them myself from the right spot or wait on the developer/Odoo. I'm missing time to do so at the moment

**Comment by Yenthe666** [comment]
Tried something based on https://github.com/odoo/technical-training/pull/8/commits/d21cc5ca28157b36c9c5a9ea5c899b38286a7e97 (also see https://github.com/odoo/technical-training/blob/d21cc5ca28157b36c9c5a9ea5c899b38286a7e97/99-sysadmin/README.md)
What I did:

`sudo apt install libpng-dev`
`wget http://ftp.fr.debian.org/debian/pool/main/libp/libpng/libpng12-0_1.2.50-2+deb8u3_amd64.deb`
`sudo dpkg -i libpng12-0_1.2.50-2+deb8u3_amd64.deb`

no succes, says no wkhtmltopdf is found

Tried
`sudo apt install wkhtmltopdf` on Ubuntu 18.04 and installs `wkhtmltopdf 0.12.4` but generates empty reports.
Don't have more time for now to test / fix.

**Comment by thite** [comment]
I have explored the solution.
There is a version of wkhtml (0.12.5) which works on Ubuntu 18 LTS.
I downloaded this version, installed it and it's perfectly printing the odoo reports!
I tried hard to re-locate the download link, but couldn't find it. Maybe that URL link has been removed.
Will upload my local copy on Git and ping you once I have done.

**Comment by thite** [comment]
Here is the link. Kindly test at your end. [wkhtml0.12.5 for Odoo-11 Reports on Ubuntu 18](https://github.com/thite/wkhtml_0.0.12.5-dev)

**Comment by Yenthe666** [comment]
@thite thanks a lot! Do you have a link to the official file though?

**Comment by thite** [comment]
No... I tried hard but couldn't locate it. If in future we get some reliable source, I will remove this wkhtml0.12.5 file (it's just for a temporary purpose, so that other's won't waste time).

**Comment by Yenthe666** [comment]
@thite thanks to @treviser I found a way - see his original answer on https://www.odoo.com/forum/help-1/question/ubuntu-18-04-lts-how-to-install-wkhtmltopdf-0-12-1-134198
Commands to execute:
sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

After a service reboot or server reboot it'll work.

**Comment by thite** [comment]
@Yenthe666 thanks.

**Comment by iamsurawee** [comment]
Hi @Yenthe666 

I have got problem that show up "Unable to find Wkhtmltopdf on this system. The PDF can not be created."

I try to Commands to execute:
sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
sudo apt-get install -f
sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

But has error in 

root@ubuntu-s-1vcpu-1gb-sgp1-01:/usr/local/bin# sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
ln: failed to create symbolic link '/usr/bin/wkhtmltopdf': File exists

root@ubuntu-s-1vcpu-1gb-sgp1-01:/usr/local/bin# sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
ln: failed to create symbolic link '/usr/bin/wkhtmltoimage': File exists

Please advise how can be fix.

Thank you and Best Regards,
Surawee Umasa

**Comment by Yenthe666** [comment]
@iamsurawee first delete them so the system can regenerate them then.

**Comment by iamsurawee** [comment]
Hi @Yenthe666
I am remove already but show error again 

Unable to find Wkhtmltopdf on this system. The report will be shown in html.

wkhtmltopdf.org


I am new user for unix can you please show me how will be appreciate. 

Thank you and Best Regards,
Surawee Umasa

**Comment by iamsurawee** [comment]
Hi @Yenthe666 

Now It's work need to stop and start service.

Thank you and Best Regards,
Surawee Umasa

**Comment by Yenthe666** [comment]
Happy to hear that - best of luck!

**Comment by nickchacha** [comment]
Anyone getting xfonts-75dpi dependency after trying the fix suggested by @Yenthe666  check here for resolve: https://askubuntu.com/questions/613190/how-can-i-install-xfonts-packages..The fix suggested above worked for me

**Comment by rudybermz** [comment]
> Hi @Yenthe666
> 
> I have got problem that show up "Unable to find Wkhtmltopdf on this system. The PDF can not be created."
> 
> I try to Commands to execute:
> sudo wget https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
> sudo dpkg -i wkhtmltox_0.12.1.3-1~bionic_amd64.deb
> sudo apt-get install -f
> sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
> sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
> 
> But has error in
> 
> root@ubuntu-s-1vcpu-1gb-sgp1-01:/usr/local/bin# sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
> ln: failed to create symbolic link '/usr/bin/wkhtmltopdf': File exists
> 
> root@ubuntu-s-1vcpu-1gb-sgp1-01:/usr/local/bin# sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
> ln: failed to create symbolic link '/usr/bin/wkhtmltoimage': File exists
> 
> Please advise how can be fix.
> 
> Thank you and Best Regards,
> Surawee Umasa

You can overwrite with the parameter -sf:
sudo ln -sf /usr/local/bin/wkhtmltopdf /usr/bin
sudo ln -sf /usr/local/bin/wkhtmltoimage /usr/bin

Don't forget to reboot afterwards.

**Comment by asoral** [comment]
I am using Odoo 12ce and Ubuntu 18.10 and wkhtmltopdf 0.12.5 but PDF generation is taking a lot of time and it is not printing properly. No header and footer are showing on report.

Please suggest. @Yenthe666

**Comment by Yenthe666** [comment]
@asoral set a report.url parameter, you're missing one.

**Comment by SemtiaJorgeLira** [comment]
@Yenthe666 thanks for your tips and function if it generates the pdf but at the end it marks the following error: that allows me to copy to the clipboard :  

Error:


undefined

--------------

Gracias

**Comment by Yenthe666** [comment]
Hmm undefined doesn't say a lot hehe. Is there a bigger trace? Is it a default Odoo report?

**Comment by SemtiaJorgeLira** [comment]
![evidencia_odoo](https://user-images.githubusercontent.com/40837218/54242353-e3b6fd80-44e9-11e9-87f6-9ebddc848734.png)

In fact the pdf generates it but with that error display as seen in the image. If I copy the error content to the clipboard because nothing is seen, the only thing it says is:

Error:


undefined

just those lines

**Comment by Yenthe666** [comment]
@SemtiaJorgeLira can you try it in English please? I assume the source term in your language is broken.

**Comment by sanjay-onnet** [comment]
I am working on odoo v8 to v13 when i install wkhtmltopdf it is wokring fine for odoo v8 and v8 but when i try to print in odoo v11 or above it gives me error like wkhtmltopdf not found.
@Yenthe666 can you please help me on it?

**Comment by congson95dev** [comment]
If some one is looking for the answer in odoo-15 ubuntu 20.04 then here is it:

```
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
```

If you get issue missing library `libpng12-0`:

```
sudo add-apt-repository ppa:linuxuprising/libpng12
sudo apt update
sudo apt install libpng12-0
```

If you get issue missing library `libssl1.0.0`:

```
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb
sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu5.7_amd64.deb
```

then re-run this command:

`sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb`

Hope this helped.

**Comment by Yenthe666** [comment]
https://github.com/Yenthe666/InstallScript/commit/6db2b2121fb5b0a325c6e7577f003b4ad36d719c should auto work now too FYI :)
