### ISSUE TITLE
ODOO 8 : Authentication is required to restart 'odoo.service'.

### ISSUE THREAD

**Issue by yboujraf** [Yenthe666/InstallScript#106]
Dear, 

After an upgrade, Authentication is required to restart 'odoo.service'.

> by-systems@by-odoo8-srv:~$ systemctl restart odoo.service
> ==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
> Authentication is required to restart 'odoo.service'.
> Multiple identities can be used for authentication:
>  1.  by-systems,,, (by-systems)
>  2.  ODOO,,, (odoo)
> Choose identity to authenticate as (1-2): 2
> Password:
> polkit-agent-helper-1: pam_authenticate failed: Authentication failure
> ==== AUTHENTICATION FAILED ===
> Failed to restart odoo.service: Access denied
> See system logs and 'systemctl status odoo.service' for details.
> by-systems@by-odoo8-srv:~$

I used your script but I don't know the password used for the odoo user.

Any help could help me to restart odoo ;-) 

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
@yboujraf check what `systemctl status odoo.service` says.
You can change a user his pass with `sudo passwd youruser`

**Comment by yboujraf** [comment]
Dear,

I tried to change the passwd but still the error messsage : 

> by-systems@by-odoo8-srv : $ systemctl status odoo.service
> odoo.service
>    Loaded: not-found (Reason: No such file or directory)
>    Active: inactive (dead)
> by-systems@by-odoo8-srv:~$ systemctl restart odoo.service
> == AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ==
> Authentication is required to restart 'odoo.service'.
> Multiple identities can be used for authentication:
>  1.  by-systems,,, (by-systems)
>  2.  ODOO,,, (odoo)
> Choose identity to authenticate as (1-2): 2
> Password:
> polkit-agent-helper-1: pam_authenticate failed: Authentication failure
>  AUTHENTICATION FAILED
> Failed to restart odoo.service: Access denied
> See system logs and 'systemctl status odoo.service' for details.
> by-systems@by-odoo8-srv:~$ sudo passwd odoo
> [sudo] password for by-systems:
> Enter new UNIX password:
> Retype new UNIX password:
> passwd: password updated successfully
> by-systems@by-odoo8-srv: $ systemctl restart odoo.service
>  AUTHENTICATING FOR org.freedesktop.systemd1.manage-units
> Authentication is required to restart 'odoo.service'.
> Multiple identities can be used for authentication:
>  1.  by-systems,,, (by-systems)
>  2.  ODOO,,, (odoo)
> Choose identity to authenticate as (1-2): 2
> Password:
>  AUTHENTICATION COMPLETE ==
> Failed to restart odoo.service: Unit odoo.service not found.

We use the odoo V8

> From https://github.com/odoo/odoo
 * branch            8.0        -> FETCH_HEAD
HEAD is now at 4045e4f [FIX] hw_escpos: complying to barcode method A


I hope it could help you.

Best Regards
Youssef

**Comment by Yenthe666** [comment]
The problem is at Loaded: not-found (Reason: No such file or directory)
It looks like your Odoo can't find the config file.

**Comment by odooconcept** [comment]
when I do:
cd /etc/init.d
and then 
sudo service odoo-server restart
nothing seems to happen

If I do 
systemctl status odoo.service

I get same issue:

odoo.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)

If I just do

service odoo-server restart

I get

Authentication is required to restart 'odoo-server.service'.
Multiple identities can be used for authentication:
 1.  Ubuntu (ubuntu)
 2.  ODOO,,, (odoo)
Choose identity to authenticate as (1-2): ^[Failed to restart odoo-server.service: Connection timed out
See system logs and 'systemctl status odoo-server.service' for details.

How should I restart Odoo server?

I used this install script for version 11.

**Comment by Yenthe666** [comment]
@odooconcept this is your real issue:
Loaded: not-found (Reason: No such file or directory)
The service file is not in the right place, there are right issues or you have mulitple files that link to wrong locations.
