### ISSUE TITLE
Installation Problem in Ubuntu 18.04

### ISSUE THREAD

**Issue by Sumeetddgr** [Yenthe666/InstallScript#107]
Hi Yenthe,
I have installed as per the command lines mentioned in the odoo-install.sh using terminal first using port 8069 for Odoo v10 in ubuntu 18.04. But when I open in firefox localhost:8069 it shows "Firefox can’t establish a connection to the server at localhost:8069."

Thereafter, I took chance using port 8070 for Odoo v11 in same OS, but the same result comes out that is "Firefox can’t establish a connection to the server at localhost:8070." Please help me to figure out the solution.

Thanks,
Sumit

**Comment by Yenthe666** [comment]
Hi @Sumeetddgr,

Can you please post the output from the logfile at `/var/log/odoo`?

**Comment by Sumeetddgr** [comment]
Hi Yenthe, 

The file is not found in the said location. But I am posting the terminal last commands : 
'''---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
cp: cannot stat '/odoo/odoo-server/debian/odoo.conf': No such file or directory
chown: cannot access '/etc/odoo-server.conf': No such file or directory
chmod: cannot access '/etc/odoo-server.conf': No such file or directory
* Change server config file
sed: can't read /etc/odoo-server.conf: No such file or directory
sed: can't read /etc/odoo-server.conf: No such file or directory
* Create startup file
bash: /odoo/odoo-server/start.sh: No such file or directory
bash: /odoo/odoo-server/start.sh: No such file or directory
chmod: cannot access '/odoo/odoo-server/start.sh': No such file or directory
* Create init file
* Security Init File
* Change default xmlrpc port
* Start ODOO on Startup
* Starting Odoo Service
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 8069
User service: odoo
User PostgreSQL: odoo
Code location: odoo
Addons folder: odoo/odoo-server/addons/
Start Odoo service: sudo service odoo-server start
Stop Odoo service: sudo service odoo-server stop
Restart Odoo service: sudo service odoo-server restart
-----------------------------------------------------------
'''

logfile = /var/log/odoo/odoo-server.log is not found.

Thanks,
Sumit

**Comment by Yenthe666** [comment]
Looks like the script failed right from the start. Did you run it with a user with limited rights or is it a server with a lot of restrictions?

**Comment by Sumeetddgr** [comment]
I logged in my user account (no limited rights) and then executed the commands as root. Is this wrong way of doing ?

**Comment by Yenthe666** [comment]
Did you do it like this? https://github.com/Yenthe666/InstallScript/blob/11.0/README.md

**Comment by Sumeetddgr** [comment]
Yes, exactly following the procedure mentioned. I have checked 3 times after that in different pcs but same result comes out. I cannot figure out the problem. Seems dissapointing.

sudo: gdebi: command not found

---- Create ODOO system user ----
Adding user `odoo' to group `sudo' ...
Adding user odoo to group sudo
Done.

---- Create Log directory ----

==== Installing ODOO Server ====
sudo: git: command not found

---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
* Creating server config file
* Create startup file
bash: /odoo/odoo-server/start.sh: No such file or directory
bash: /odoo/odoo-server/start.sh: No such file or directory
chmod: cannot access '/odoo/odoo-server/start.sh': No such file or directory
* Create init file
* Security Init File
* Start ODOO on Startup
* Starting Odoo Service

Thanks,
Sumit Sinha

**Comment by Yenthe666** [comment]
sudo: git: command not found
seems to be pointing to the fact that you don't have git installed..
What happens when you run `apt-get install git-core`

**Comment by Sumeetddgr** [comment]
Hi Yenthe,
The problem is resolved. I am thankful for your response.
But it was success in different pc. As repeating the same installation steps in old pc is not working, so Do I need to format the old pc again ?
 (I tried re-installation with different port number in the odoo_install.sh file)

Regards
Sumit Sinha

**Comment by Yenthe666** [comment]
Hmm I assume a package was missing on the old computer which resulted in the git clone failing. If that part of the script fails it it can't copy the config file and so on which is in there, resulting in pretty much everything failing.

**Comment by Sumeetddgr** [comment]
Hi Yenthe,
This message is coming in old system 

Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libpng12-0

ln: failed to create symbolic link '/usr/bin/wkhtmltopdf': File exists
ln: failed to create symbolic link '/usr/bin/wkhtmltoimage': File exists

I am not able to understand this. Will this go off after system format ?

Regards,
Sumit Sinha

**Comment by Sumeetddgr** [comment]
Installation is done. 
Thanks Yenthe  for your response.

Regards.
