### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by WonderM** [Yenthe666/InstallScript#110]
Hi Yenthe.

Please note that I have tried your script on Linux Mint 19 and have me these three error messages:

#ERROR1

Package python-pypdf is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package python-pybabel is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-pybabel' has no installation candidate
E: Package 'python-pypdf' has no installation candidate

#ERROR2

Running setup.py install for greenlet ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7awqhyd3/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7mhdv_qz/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.linux-i686-3.6
    i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-HTtWq7/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c greenlet.c -o build/temp.linux-i686-3.6/greenlet.o
    In file included from greenlet.c:5:0:
    greenlet.h:8:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-7awqhyd3/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7mhdv_qz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-7awqhyd3/greenlet/

#ERROR3

Saving to: ‘wkhtmltox-0.12.1_linux-trusty-i386.deb’

wkhtmltox-0.12.1_li 100%[===================>]  13.95M   206KB/s    in 2m 0s   

2018-07-09 20:12:04 (119 KB/s) - ‘wkhtmltox-0.12.1_linux-trusty-i386.deb’ saved [14624368/14624368]

Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libpng12-0

I have node version 8.10.0, npm version 6.1.0 and psql version 10.4.

I hope it make sense.

**Comment by Yenthe666** [comment]
Hi @WonderM,

Thanks a lot for the feedback!
Originally the script was only made for Ubuntu 14, 16 & 18, not for mint. I haven't ever tested it on mint honestly.

**Comment by AdriantoDimaz** [comment]
Hi Yenthe.
I have tried your script on Ubuntu Server 18.04 and have this:
"unable to find wkhtmltopdf on this system"

Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libpng12-0

other than that your script is marvelous

**Comment by siddharth-kanojiya** [comment]
@AdriantoDimaz 

Change wkhtmltopdf path to this

WKHTMLTOX_X64=https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
WKHTMLTOX_X32=https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_i386.deb

It worked for me on ubuntu 18.04

**Comment by Yenthe666** [comment]
Or alternatively you can have a look at https://github.com/Yenthe666/InstallScript/issues/102 which has another solution too. I should fix the script soon, just need some extra time.

**Comment by jcchoquet** [comment]
Hi,
I have the same erro on Debian Stretch:
 unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

an idea ?

**Comment by Yenthe666** [comment]
They should all be good in the meanwhile.
