### ISSUE TITLE
InstallScri

### ISSUE THREAD

**Issue by FelipeEB** [Yenthe666/InstallScript#111]
Hello,
Great Script -- 

If you install Odoo v9 on Ubuntu 18.04 you've to fix a few issues:

**apt-get install -y python-dev libldap2-dev libsasl2-dev libssl-dev** 

install deb:  apt install ./python-gpgme_0.3-1.2build2_amd64.deb
from http://security.ubuntu.com/ubuntu/pool/main/p/pygpgme/python-gpgme_0.3-1.2build2_amd64.deb

install following pip2 Modules from source with **pip2 install .**
https://kent.dl.sourceforge.net/project/pyxml/pyxml/0.8.4/PyXML-0.8.4.tar.gz
https://dl.cihar.com/utidylib/uTidylib-0.3.tar.gz
https://launchpadlibrarian.net/62807092/bzrtools-2.3.0.tar.gz
https://fossies.org/linux/privat/old/PyChart-1.39.tar.gz

finally install following pip2 modules:
**pip2 install lxml passlib werkzeug decorator python-dateutil pytz psycopg2 babel PyYAML pillow reportlab mako Python-Chart psutil requests jinja2 psycopg2-binary bcrypt beautifulsoup4 cffi dnspython docutils feedparser funcsigs gdata html5lib linecache2 mock ndg-httpsclient ofxparse paramiko pbr phonenumbers psycogreen py-Asterisk pyasn1 pycparser pycrypto pydot Pygments pygobject pyinotify PyNaCl pyOpenSSL pyparsing pyPdf pysftp python-ldap python-openid python-stdnum PyWebDAV roman traceback2 unittest2 vatnumber vobject xlwt zope.interface pygpgme ZSI**

greetings
Felipe

**Comment by Yenthe666** [comment]
Hi @FelipeEB,

Thanks a lot for the compliment & feedback.
I guess you already had another Odoo instance with Python 3 or some defaults to Python 3. In this case you indeed need to mention pip2 as the defaulter.
Perhaps something I should default too.

**Comment by FelipeEB** [comment]
it‘a because of ubuntu 18.04, which defaults to python 3.   it was a fresh install... odoo
starts with 11 only supporting python 3too...
Felipe

**Comment by Yenthe666** [comment]
Yep - so I might want to default the V8/V9/V10 script to `pip2` to be absolutely safe I guess.
