### ISSUE TITLE
 Odo12 released in the future  Installation script

### ISSUE THREAD

**Issue by talway** [Yenthe666/InstallScript#113]
Hello, can you make a future release of the odoo12 installation script?
I hope that I can install the new version of the test and have some features.
Thank you!

https://github.com/odoo/odoo/tree/master

**Comment by Yenthe666** [comment]
Hi @talway,

I haven't tested myself yet but it should work fine by setting the odoo version parameter to master (upcoming V12).

Regards,
Yenthe

**Comment by talway** [comment]
I modified the version to install, have the following prompt, you can the next update to fix it; 
In addition: the installation process there are 2 need to be manually confirmed, whether to make automatic confirmation. 
Thank you

-------------------------------------------------
Style error
× 

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.
Could not execute command 'sassc'This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/fonts.scss
    - /web/static/src/scss/ui.scss
    - /web/static/src/scss/ui_extra.scss
    - /web/static/src/scss/navbar.scss
    - /web/static/src/scss/mimetypes.scss
    - /web/static/src/scss/modal.scss
    - /web/static/src/scss/animation.scss
    - /web/static/src/scss/rainbow.scss
    - /web/static/src/scss/datepicker.scss
    - /web/static/src/scss/banner.scss
    - /web/static/src/scss/colorpicker.scss
    - /web_tour/static/src/scss/tip.scss
    - /web_tour/static/src/scss/keyframes.scss

**Comment by Yenthe666** [comment]
Hi there,

The V12 installation script is out of beta and tested on Ubuntu 16 & 18. You can download & test it again now.

Regards,
Yenthe
