### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by iamsurawee** [Yenthe666/InstallScript#115]
Hi @Yenthe666,

We try to send email and got error 

Connection Test Failed! Here is what we got instead:
101
Network is unreachable

We use localhost and gmail SMTP but still show this error.

Best Regards,
Surawee Umasa

**Comment by Yenthe666** [comment]
Hi there,

This is not related to my Odoo script.
You should ask it on the official help forums at https://www.odoo.com/forum/help-1
