### ISSUE TITLE
Odoo not accessible ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by codeagencybe** [Yenthe666/InstallScript#116]
Hello Yenthe,

I have used your script to install Odoo 11 Enterprise. 
During setup, everything went perfect, no errors and I get the message that Odoo is started and up and running. 
Everything is default from your config. 
I used Ubuntu 16.04, everything default. 

After I got the message everything OK and up and running, I point my browser to IP and port 8069.
But I get the error ERR_CONNECTION_REFUSED
I tried with and without ports and also several others (8069 - 8070's range)

I have searched for hours now if there is anything in the file that could run it to perhaps another port but I can't find anything. 

Is there any reason why it returns error connection refused? 
Also, I don't see anything specific in your script about a frontend server like NGINX.
Is this part missing or is it on purpose that we have to install a webserver seperately? 

Nowhere in the documentation it's mentioning anything about this. And according your online tutorial, I also don't see anything about installing NGINX, and still you were able to open the site just by visiting the IP:8069. 

Thanks for your soonest feedback!

**Comment by Yenthe666** [comment]
Hi @codeagencybe,

Nginx is currently not added in as an option to deploy. Right now it'll install a minimalist Odoo instance with no Nginx and/or reverse proxy. You should just be able to access it from ip:port.
Does your Odoo logfilder (under /var/log/odoo) say anything more/else?

Regards,
Yenthe

**Comment by acsistemas** [comment]
Hi, I'm using Digital Ocean and also AWS EC2, and after installing Odoo CE V11 using your script, and try to create the first database I get the same error ERR_EMPTY_RESPONSE
