### ISSUE TITLE
Install Script 8, 10, and 11 does not work for Odoo 8 on Ubuntu 18.04

### ISSUE THREAD

**Issue by Randy01p** [Yenthe666/InstallScript#117]
Ive tried install_script 8, 10, and 11, on Ubuntu 18.04.
Odoo 8 will not start up and log file does not get created at all, it says active (exited) in the status. Similar to this issue: https://github.com/Yenthe666/InstallScript/issues/55

python_pybabel does not exist in Ubuntu 18.04 anymore

Please make it work for Odoo 8 on Ubuntu 18.04?

**Comment by Randy01p** [comment]
Update: Ive also tried to install Odoo 8 on Ubuntu 16.04, same problem.

**Comment by Ark74** [comment]
Python for 16.04 and 18.04 by default is python3.
Odoo 8 requires python2. 

Also at this point version 8 is EOL.

**Comment by Yenthe666** [comment]
Indeed version 8 is EOL but I'll try to look into it when I have some spare time.

**Comment by xAlphaOmega** [comment]
> Update: Ive also tried to install Odoo 8 on Ubuntu 16.04, same problem.

What is the purpose of keeping Odoo 8 when the versions are much improved, I never understand this philosophy. Can you please explain?

**Comment by Yenthe666** [comment]
In the meanwhile V9 is also deprecated so I'm not going to bother and go back two deprecated versions honestly.
