### ISSUE TITLE
[12.0] Testing Feedback

### ISSUE THREAD

**Issue by ray-odoo** [Yenthe666/InstallScript#118]
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-30-generic x86_64)

Note: I changed the branch to "12.0"

1)
ERROR after line 63:
Package gdebi-core is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package python3-pip
E: Package 'gdebi-core' has no installation candidate

RESOLVED WITH THIS:
sudo add-apt-repository universe
sudo apt-get update

2)
ERROR after line 86:
Dependency is not satisfiable: libpng12-0

RESOLVED WITH THIS:
https://groups.google.com/forum/#!topic/vesta-discuss/-Z8OD_C37jQ

3)
ERROR after line 107:
Installing collected packages: pytz, Babel, decorator, docutils, lxml, requests, ebaysdk, feedparser, greenlet, gevent, html2text, MarkupSafe, Jinja2, libsass, Mako, pbr, mock, num2words, beautifulsoup4, ofxparse, passlib, olefile, Pillow, psutil, psycopg2, pyparsing, pydot, pyldap, PyPDF2, pyserial, python-dateutil, pyusb, qrcode, reportlab, suds-jurko, python-stdnum, vatnumber, vobject, Werkzeug, XlsxWriter, xlwt, xlrd
  Running setup.py install for lxml ... error
ERROR: b'/bin/sh: 1: xslt-config: not found\n'
    ** make sure the development packages of libxml2 and libxslt are installed **
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0zln_g0w/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-st4tsca_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-0zln_g0w/lxml/

RESOLVED WITH THIS:
sudo apt-get install libxml2-dev libxslt1-dev zlib1g-dev
sudo apt-get install libsasl2-dev libldap2-dev libssl-dev

4)
ERROR AFTER LINE 133:
ln: failed to create symbolic link '/usr/bin/node': File exists
(didn't end up being a problem).

TESTED TO LINE 143 ONLY, PREFER TO USE SYSTEMD STARTUP.

**Comment by fgarcia-humanoide** [comment]
I tried the script for odoo 12 but odoo is not running. 

Lots of messages during install.

I used Yenthe's scripts for installing versions 8, 10, and 11, (in nearly 40 production installations). Allways adding something with an auxiliary script.

So now it is time to solve the problems step by step.

**Comment by fgarcia-humanoide** [comment]
After installing I aplied Ray solutions but do not work either.

¿Should I aply the solutions first in a new machine and then install odoo?

**Comment by fgarcia-humanoide** [comment]
I have this error using the odoo 11 sript (changing to version 12.0)

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

Could not execute command 'sassc'This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/primary_variables.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /web/static/lib/bootstrap/scss/_variables.scss
    - /web/static/src/scss/fonts.scss
    - /web/static/src/scss/ui.scss
    - /web/static/src/scss/ui_extra.scss
    - /web/static/src/scss/navbar.scss
    - /web/static/src/scss/mimetypes.scss
    - /web/static/src/scss/modal.scss
    - /web/static/src/scss/animation.scss
    - /web/static/src/scss/rainbow.scss
    - /web/static/src/scss/datepicker.scss
    - /web/static/src/scss/banner.scss
    - /web/static/src/scss/colorpicker.scss
    - /web/static/src/scss/keyboard.scss
    - /web_tour/static/src/scss/tip.scss
    - /web_tour/static/src/scss/keyframes.scss

**Comment by fgarcia-humanoide** [comment]
Now I have installed enterprise.  How can this happen?

**Comment by Yenthe666** [comment]
@fgarcia-humanoide you didn't install libsass (see https://github.com/Yenthe666/InstallScript/commit/356a1cede5c928ef4b234b6e2cba1c75ebbc4b3d#diff-5903e4a9e967af1610a129f4adc34b4d) for some reason

**Comment by janbec** [comment]
With the steps described by @ray-odoo I was able to get a clean installation. Thanks, Ray! Thanks Yenthe!
I installed the missing packages before running the script.

**Comment by Yenthe666** [comment]
Added those fixes, did a test run on a clean Ubuntu 18.04.1 and works neat out of the box now.
Removed it out of beta, it is now at https://github.com/Yenthe666/InstallScript under the 12.0 branch
Let me know if you notice any more issues guys! :)

@ray-odoo thanks a lot for the help & tips!
