### ISSUE TITLE
Renaming the branches

### ISSUE THREAD

**Issue by sebastian-code** [Yenthe666/InstallScript#12]
I think than, seeing where the script is going, and how it pretends to approach the installation, is safe to say than perhaps some more appropriate naming for the branches is in place.

A master branch, which is the default one too (right now is the 9.0 branch), and perhaps a development branch too.

**Comment by Yenthe666** [comment]
@sebastian-code,

The reason that 9.0 is the default at the moment is because this is the 'stable' script. The 'master' version is the version that we're developing on. Atleast, that was my idea :smile:

**Comment by Yenthe666** [comment]
@sebastian-code I honestly think that we should choose if we want to merge the 8.0 and 9.0 script in one or not. And then if we create one version for this script or a stable (which contains fully test coded) and a development version (which is work in progress).

**Comment by sebastian-code** [comment]
I do agree with you, that would benefit the script, the process and also that will give to the repository a more organized aspect.

**Comment by sebastian-code** [comment]
Thinking about this, I would suggest to go with the master/development branching model and to merge all the stable code into master, and every other improvement/modification/change will go inside development until it's fully tested.

**Comment by Yenthe666** [comment]
@sebastian-code yes but I want two different branches atleast. A stable version and a master/development! :+1:

**Comment by sebastian-code** [comment]
Sorry if I confused you with my suggestion. I was saying that, one branch named master (usually is accepted this naming for the stable branch) and another one named development, into this branch is were every change is made and evaluated to be incorporated into master after testing.

**Comment by Yenthe666** [comment]
@sebastian-code that makes sense. Sounds like a good concept to me and was pretty much what I wanted to do too. V8 and V9 script would have to be merged in to eachother too.
@tvibliani do you like this idea / setup too?

**Comment by tvibliani** [comment]
:+1:

**Comment by seancallahan88** [comment]
Apologies if this is a stupid question, but is the 9.0 stable branch contain all the odoo enterprise code?

**Comment by Yenthe666** [comment]
@seancallahan88 the 9.0 stable branch doesn't install the Enterprise code at the moment. Perhaps this is something nice for on the to-do list :)

**Comment by sebastian-code** [comment]
But that only will work if you have access to the enterprise repos, which you only will work if you have the paid enterprise license.

**Comment by Yenthe666** [comment]
Good point there @sebastian-code! So that has to be caught too.

**Comment by sebastian-code** [comment]
I don't know the specific mechanics of those repos (obviously I don't have the paid version) and I haven't found how that's done, from my point of view, I'm stuck with Odoo 8 forever

**Comment by Yenthe666** [comment]
In all honesty I do have a feeling that Odoo 9 is rather a downgrade then an upgrade. Only when you have the enterprise version it'll become interesting and even then I notice that a lot of the functionalities in Odoo 9 are still broken.
I prefer to stay on 8 for now with most of my Odoo databases too.

**Comment by Yenthe666** [comment]
To come back on this one: we have a 9.0, 10.0, 11.0 branch now and a master and development branch (for my own test purposes) so I think this can be closed.
