### ISSUE TITLE
Script is not working anymore 

### ISSUE THREAD

**Issue by khalilsido** [Yenthe666/InstallScript#121]
Hello 

I used your script to install odoo 11 on 2 servers thank you 

But suddenly I am trying to install in on new server everything is completed but once I go to my browser I can't access odoo , do I need to change something ?

**Comment by Yenthe666** [comment]
Hi there,

Please check what is in the logfile (under /var/log/odoo)

Regards,
Yenthe

**Comment by motermouth15** [comment]
Hello- I am having this problem as well! I am trying to migrate my instance from microsoft's cloud computing, over to google's. I was using this script to install a fresh odoo before hand. Even before I migrate any of my data, the odoo instance never seems to start.

No log file is created in /var/log/odoo, but the folder does exist.

When I use command "sudo systemctl status odoo-server" I get the following reply:

> ● odoo-server.service - LSB: Enterprise Business Applications
>    Loaded: loaded (/etc/init.d/odoo-server; bad; vendor preset: enabled)
>    Active: active (exited) since Wed 2019-01-30 00:34:06 UTC; 4min 52s ago
>      Docs: man:systemd-sysv-generator(8)
>   Process: 14949 ExecStop=/etc/init.d/odoo-server stop (code=exited, status=0/SUCCESS)
>   Process: 15005 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/SUCCESS)
> Jan 30 00:34:06 MYDOMAIN systemd[1]: Starting LSB: Enterprise Business Applications...
> Jan 30 00:34:06 MYDOMAIN odoo-server[15005]: Starting odoo-server: odoo-server.
> Jan 30 00:34:06 MYDOMAIN systemd[1]: Started LSB: Enterprise Business Applications.

Nothing fails if I stop, restart, or start the service.

I then checked open ports with "netstat -plntu" and got the following back:

> tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1607/nginx -g daemo
> tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1707/sshd       
> tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1615/postgres   
> tcp6       0      0 :::80                   :::*                    LISTEN      1607/nginx -g daemo
> tcp6       0      0 :::22                   :::*                    LISTEN      1707/sshd       
> udp        0      0 0.0.0.0:68              0.0.0.0:*                           966/dhclient    
> udp        0      0 10.142.0.4:123          0.0.0.0:*                           1498/ntpd       
> udp        0      0 127.0.0.1:123           0.0.0.0:*                           1498/ntpd       
> udp        0      0 0.0.0.0:123             0.0.0.0:*                           1498/ntpd       
> udp6       0      0 fe80::4001:aff:fe8e:123 :::*                                1498/ntpd       
> udp6       0      0 ::1:123                 :::*                                1498/ntpd       
> udp6       0      0 :::123                  :::*                                1498/ntpd       
> 

What am I missing?

**Comment by Yenthe666** [comment]
Don't see anything odd directly. Does the Odoo load with IP:port?

**Comment by motermouth15** [comment]
In my configuration, it's called to load on port 8069. Wouldn't it be shown in the list when I use command "netstat -plntu"?

Either way, my server refuses the connection if I go to www.mydomain.com:8069 but only shows the nginx standard loading screen if I just use port 80. I've also tried forwarding requests from port 80 to 8069 with no luck.

**Comment by motermouth15** [comment]
This might seem W I L D, but I actually don't think the script is the problem. I think something in google's cloud computing is preventing it? I just created a fresh VM instance on my own server and was able to install everything just fine with the script. Could that be possible?

**Comment by motermouth15** [comment]
> In my configuration, it's called to load on port 8069. Wouldn't it be shown in the list when I use command "netstat -plntu"?
> 
> Either way, my server refuses the connection if I go to [www.mydomain.com:8069](http://www.mydomain.com:8069) but only shows the nginx standard loading screen if I just use port 80. I've also tried forwarding requests from port 80 to 8069 with no luck.

I have no idea what changed, but I used a fresh image of ubuntu 16.04 and now the script worked.

**Comment by Yenthe666** [comment]
Hmm I guess some dependency failed in your previous run which is fixed in the meanwhile. Thanks for the feedback!
