### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tonybenoy** [Yenthe666/InstallScript#122]
Could you please add a license to the file?

**Comment by Yenthe666** [comment]
Hi @tonybenoy,

I've added it in.
V9: https://github.com/Yenthe666/InstallScript/commit/06e4228a11159955983240d85638935e3e231a02
V10: https://github.com/Yenthe666/InstallScript/commit/6e2e54b487e9a27efb30583f2c9ae361c1ebc65a
V11: https://github.com/Yenthe666/InstallScript/commit/34fe7f0deb3a172b012004de051bf78ae4876969
Upcoming V12: https://github.com/Yenthe666/InstallScript/commit/793a70c8eedf0d0f2d8d91e232de7ac0103b998a

P.S: Thanks for the new PR! I'll get to it as soon as possible. I have some issues with a corrupt hard drive that prevent me from testing today.

**Comment by tonybenoy** [comment]
Hi @Yenthe666 
Thanks for the License. I've pushed some more changes to the nginx part to improve on the security part of it.
