### ISSUE TITLE
WKHTMLTOPDF，This software download is particularly slow, can change download source, 

### ISSUE THREAD

**Issue by talway** [Yenthe666/InstallScript#123]
WKHTMLTOPDF，This software download is particularly slow, can change download source, thank you!

##
## https://www.odoo.com/documentation/8.0/setup/install.html#deb ):
WKHTMLTOX_X64=https://downloads.wkhtmltopdf.org/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
WKHTMLTOX_X32=https://downloads.wkhtmltopdf.org/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-i386.deb

**Comment by Yenthe666** [comment]
Hi @talway,

Thanks a lot for the suggestion.
I don't have any speed problems or anything with downloading wkhtmltopdf at my end though. I don't see a use in changing the URL as it just points to another download location.

Regards,
Yenthe
