### ISSUE TITLE
odoo12 need SassC and LibSass

### ISSUE THREAD

**Issue by offer1983** [Yenthe666/InstallScript#124]
ubuntu-18: Wkhtmltopdf failed to install

odoo12 need SassC and LibSass
Website and css： error

https://www.odoo.com/forum/help-1/question/how-to-install-sassc-139497
https://www.odoo.com/zh_CN/forum/help-1/question/ubuntu-18-04-lts-how-to-install-wkhtmltopdf-0-12-1-134198

**Comment by Yenthe666** [comment]
Hi there,

I made some more fixes and patches. The latest 12.0 version of the script should work just fine now!
