### ISSUE TITLE
home/.../.cache/pip ownership issue - cache disabled

### ISSUE THREAD

**Issue by GraamGunn** [Yenthe666/InstallScript#125]
I get the following errors when installing on Ubuntu 18.04.1 LTS

E: Package 'python-pypdf' has no installation candidate

The directory '/home/graham/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

The directory '/home/graham/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Collecting pypdf2
.
.
.

---- Installing Enterprise specific libraries ----
The directory '/home/graham/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/graham/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

**Comment by Yenthe666** [comment]
Hi there,

The issue comes from The directory '/home/graham/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. 
Does python-pypdf install if you run it with the -H flag? With what user do you do this? Does it have sudo rights etc?

**Comment by GraamGunn** [comment]
Hi,

1. I ran your odoo install script as sudo.
2. I will re-try installing pypdf when next at the client
3. What impact will pip cache error have had on the odoo installation?

Graham
