### ISSUE TITLE
website bug,and install: Dependency is not satisfiable: libpng12-0

### ISSUE THREAD

**Issue by offer1983** [Yenthe666/InstallScript#128]
google cloud:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

wkhtmltox-0.12.1_li 100%[===================>]  13.51M   817KB/s    in 18s     

2018-10-15 09:42:31 (784 KB/s) - ‘wkhtmltox-0.12.1_linux-trusty-amd64.deb’ saved [14166104/14166104]

Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
**Dependency is not satisfiable: libpng12-0**

**Comment by offer1983** [comment]
Odoo12 Choose BOOTSWATCH theme: Select theme's menu is invalid.
Odoo12 Choose DEFAULT theme: Custom theme menu color is invalid.

<img width="1376" alt="20181015180611" src="https://user-images.githubusercontent.com/43988295/46944614-18429c80-d0a5-11e8-89d0-5831914a8463.png">
<img width="1386" alt="20181015180827" src="https://user-images.githubusercontent.com/43988295/46944709-5cce3800-d0a5-11e8-913c-e16a9bf4308c.png">
<img width="1349" alt="20181016165409" src="https://user-images.githubusercontent.com/43988295/47004446-26a3bd80-d164-11e8-89c9-d86c509b2828.png">

<img width="971" alt="11_42_15__10_16_2018" src="https://user-images.githubusercontent.com/43988295/47004610-8ac68180-d164-11e8-83c6-09a75e4a0b43.png">

**Comment by Yenthe666** [comment]
Odoo itself had issues here, should be resolved now. If not you're missing  a package, just install all requirements from `requirements.txt` then.
