### ISSUE TITLE
install Odoo 11

### ISSUE THREAD

**Issue by jcchoquet** [Yenthe666/InstallScript#129]
Hello,
I want to install Odoo 11 Enterprise with your script, but the github for this version is not accessible.
i have an error 404.

**Comment by Yenthe666** [comment]
Hi,

Not sure what you mean. It is there: https://github.com/Yenthe666/InstallScript/blob/11.0/odoo_install.sh

**Comment by jcchoquet** [comment]
no your script is accessible, but this is the github enterprise : "https://www.github.com/odoo/enterprise"

**Comment by Yenthe666** [comment]
Ahh. That is because you're not an official Odoo partner. If you're not a partner you don't have access to the enterprise code. 😉

**Comment by jcchoquet** [comment]
the problem is that I am Odoo partner :-)

**Comment by Yenthe666** [comment]
@jcchoquet then you have to reach out to your account manager. It means your Github account is not added as a verified user on the github.com/odoo/enterprise repository.
You can also manage this from your own partner dashboards page. There is an option to add Github users from your account.

**Comment by jcchoquet** [comment]
thanks, I have added my account in my dashboard but it doesn't work. I will contact my account manager.
thanks again

**Comment by Yenthe666** [comment]
No problem. The syncing can take up to a few hours, I've had issues before too. Anyways, as soon as that is fixed you can use the script 😉
