### ISSUE TITLE
Arch Linux Script

### ISSUE THREAD

**Issue by jeffryjdelarosa** [Yenthe666/InstallScript#134]
Is there a arch linux, manjaro or any pacman sript?

**Comment by Yenthe666** [comment]
Hi @jjdelarosa,

Sorry but no, right now I only have support for Ubuntu related versions, no Arch or variants.

**Comment by jeffryjdelarosa** [comment]
Thanks, @Yenthe666 Don't you have a module to print dot matrix printer... I have searched, because we have 3 Epson LX-350 and we want to print out in half page....
