### ISSUE TITLE
Odoo12 - Ubuntu 18.04.1 - Installation problem

### ISSUE THREAD

**Issue by yboujraf** [Yenthe666/InstallScript#135]
OS : Ubuntu 18.04.1 server AMD
Odoo Version : Odoo 12 Community version
User : root
Folder :  /opt where script installed

Dear,

During the execution of the script I found three error messages :

1. Permission denied

`---- Create custom module directory ----

mkdir: cannot create directory ‘/odoo/custom’: Permission denied
mkdir: cannot create directory ‘/odoo/custom/addons’: No such file or directory
`

2. /var/log/odoo/odoo-server.log

`2018-12-18 00:23:17,657 14978 INFO ? odoo.service.server: HTTP service (werkzeug) running on hostname_of_my_firewall:8069`

I don't know why odoo uses the hostname of my firewall instead of the address of the server hosting Odoo12?
 
[odoo-server.log](https://github.com/Yenthe666/InstallScript/files/2688402/odoo-server.log)

3. webpage access

Finally at the end of the execution when I am opening a web page

I have this

![image](https://user-images.githubusercontent.com/6151258/50125060-85baa700-0267-11e9-8c4f-f69ba318bacc.png)

I filled the datas to create the database but finally system error.

Thanks in advance,

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear

After verifying step by step the execution of the script.

I found the pacakage `gdebi` is not installed.

I tried to install it and I got this message :

`root@odoo:/opt# sudo apt install gdebi
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package gdebi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'gdebi' has no installation candidate`

That's why  wkhtmltox is not installed.

Best Regards
Youssef

**Comment by yboujraf** [comment]
Dear,

I think I found the issue.

When I have created my VM, installed the ubuntu 18.04.1, I created the user `odoo`.

If I execute the script, I will have the issue mentionned above.

If I change the `OE_USER="odoo"` by `OE_USER="odoo12"` then everything is fine.

I suspect this is related the rights of folder /home/odoo.

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
Ahh yes, the users seem to have conflicted. Did you manage to install and run it fine with a new defined user?

**Comment by byk3v** [comment]
Im facing the same problem when I run the script, but with Ubuntu 18.04, Odoo 13

During the execution of the script I found three error messages :

    Permission denied

`---- Create custom module directory ----

mkdir: cannot create directory ‘/odoo/custom’: Permission denied
mkdir: cannot create directory ‘/odoo/custom/addons’: No such file or directory
`

At the end there was founded a solution_??
Thanks in advanced

**Comment by Yenthe666** [comment]
Looks like your user has insufficient security rights, that's all :)

**Comment by byk3v** [comment]
I, reinstalled everything again, even the OS, and after some troubles with postgresql, It worked, Thanks
