### ISSUE TITLE
Odoo12 - multiple instance installation with script

### ISSUE THREAD

**Issue by darshan-odoo** [Yenthe666/InstallScript#136]
**Steps followed :** I am trying to install multiple scripts for Odoo.

Installed v11 with the script and then v12. 

Error Faced  `fatal error : /odoo/odoo-server path already exists`

![image](https://user-images.githubusercontent.com/42735016/50425628-3bf24200-08a1-11e9-9fc4-b63eae2a9a3f.png)

**Description:**

`OE_HOME_EXT="/$OE_USER/${OE_USER}-server"`

`sudo git clone --depth 1 --branch $OE_VERSION https://www.github.com/odoo/odoo $OE_HOME_EXT/`

https://github.com/Yenthe666/InstallScript/blob/12.0/odoo_install.sh#L116

The directory it uses to clone is : odoo/odoo-server

So when I use the script for multiple instances does not work in that case, shows fatal error as the directory already exists.

Hopefully, If we could use something like this $OE_HOME_EXT/$OE_VERSION/ to create the directory based on versions, to resolve this issue.

P.S: Also there might be some other warnings/errors I guess need to considered while creating a log file or symbolic link for wkhtmltopdf.

Hopefully, this would be helpful, thanks!

@Yenthe666

**Comment by Yenthe666** [comment]
Well, you have too change the parameters yourself.. You could change the Odoo username for the second install and then everything works fine.
