### ISSUE TITLE
wkhtmltox install on ubuntu bionic

### ISSUE THREAD

**Issue by icf20** [Yenthe666/InstallScript#139]
the corect link is https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb

the script dont install it so it can be installed manually after using `wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
`
u get some errors if you `dpkg -i wkhtmltox_0.12.5-1.bionic_amd64.deb`

```
`Package fontconfig is not installed.
 wkhtmltox depends on libjpeg-turbo8; however:
  Package libjpeg-turbo8 is not installed.
 wkhtmltox depends on libxrender1; however:
  Package libxrender1 is not installed.
 wkhtmltox depends on xfonts-75dpi; however:
  Package xfonts-75dpi is not installed.
 wkhtmltox depends on xfonts-base; however:
  Package xfonts-base is not installed.

$ apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core libfontconfig1 libfontenc1 libjpeg-turbo8 libxrender1 x11-common xfonts-75dpi xfonts-base xfonts-encodings xfonts-utils
Suggested packages:
  xfs | xserver
The following NEW packages will be installed:
  fontconfig fontconfig-config fonts-dejavu-core libfontconfig1 libfontenc1 libjpeg-turbo8 libxrender1 x11-common xfonts-75dpi xfonts-base xfonts-encodings xfonts-utils
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 11.5 MB of archives.
After this operation, 17.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] y


```

does anyone got a better solution ?

**Comment by ChristopheLux** [comment]
Hello

Even if Odoo mentioned that 0.12.5.1 https://github.com/odoo/odoo/wiki/Wkhtmltopdf  is supported I have not yet succeeded in having it working for Odoo even if the install is correct (Ubuntu 18.04 LTS updated)
with the following steps
after 
sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
      sudo apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb  (this allows to install all the dependencies)
	sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin
    sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin

So if @Yenthe666 has an idea

PS: odoo server log  INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf

ls -al /usr/bin | grep wk
lrwxrwxrwx  1 root   root          21 Mar 20 15:49 awk -> /etc/alternatives/awk
-rwxr-xr-x  1 root   root      658072 Feb 11  2018 gawk
-rwxr-xr-x  1 root   root      191504 Jan 10 13:07 gpg-wks-server
-rwxr-xr-x  1 root   root        3189 Feb 11  2018 igawk
-rwxr-xr-x  1 root   root      125416 Apr  3  2018 mawk
lrwxrwxrwx  1 root   root          22 Mar 20 15:49 nawk -> /etc/alternatives/nawk
-rwxr-xr-x  1 root   root       14408 Jan 22  2018 showkey
lrwxrwxrwx  1 root   root          28 Apr  1 17:54 wkhtmltoimage -> /usr/local/bin/wkhtmltoimage
lrwxrwxrwx  1 root   root          26 Apr  1 17:54 wkhtmltopdf -> /usr/local/bin/wkhtmltopdf

**Comment by ChristopheLux** [comment]
FYI
Odoo is not "seeing" wkhtmltopdf if is not installed in /odoo

It was not working when I installed Odoo in /opt/odoo....weird
Maybe I miss something but install script is the same just chnage the home of odoo user...

**Comment by Yenthe666** [comment]
@ChristopheLux I've got dozens of instances running with wkthmltopdf outside of the Odoo directory with this script. Your wkhtmltoimage and wkhtmltopdf belong to the user root which is most likely not your Odoo user (and shouldn't be).

**Comment by ChristopheLux** [comment]
Sorry If I was not precise 

My installation works if odoo home is /odoo
My installation does not work if odoo home is /opt/odoo

wkhtmltopdf/image never installed in odoo directory and never owned by odoo users
PS I used you script just changed the home

**Comment by Yenthe666** [comment]
@ChristopheLux you can just change the home directory at https://github.com/Yenthe666/InstallScript/blob/12.0/odoo_install.sh#L18 ?

**Comment by ChristopheLux** [comment]
That is what I did :) forgot to mention it is for Odoo v11

**Comment by Yenthe666** [comment]
odd, that should really work. I have dozens of instances running in different folders that are both under /opt and not under /opt. Perhaps you have right issues?
