### ISSUE TITLE
Installation Folder

### ISSUE THREAD

**Issue by sebastian-code** [Yenthe666/InstallScript#14]
At this point the script creates a folder in the root address of the disk as the home folder for the odoo user, and also to contain the odoo software.

In Linux is usually a good practice to do that inside the /opt/ folder, I would say than that is basically because the modularity Linux installs allow for mounting folders in different storage units. 

I didn't created a PR basically because I want to here from you @Yenthe666 and @tvibliani and what do you think about this, before to suggest something.

**Comment by Yenthe666** [comment]
@sebastian-code,

So you'd suggest /opt/odoo-server in place of /odoo/odoo-server? Is that what you mean?

**Comment by sebastian-code** [comment]
Actually I would go for something even more like /opt/'user_name'/ as root folder even for the software, that's because if you want to have multiple versions of odoo running on the same machine, you only need to change the user name, and you'll have separated users and folder for every install too.

**Comment by tvibliani** [comment]
:+1:

**Comment by Yenthe666** [comment]
@sebastian-code I don't really see a lot of benefits in this. The only change would be getting /opt/user_name/ in place of /odoo-your-name/odoo-your-name-server/
So if you'd give the Odoo instance in the script your customer his name you would get odoo-customer-name/odoo-customer-name-server.
I don't really see any plus sides in this. Yes yours would perhaps be a bit more cleaner when you're in /opt/ but the current setup would already show /odoo-your-name/ which would make it clear what Odoo it is before you even navigate in to any folder.
(plus not everybody nows about /opt/ and that this is common Linux behaviour)

**Comment by sebastian-code** [comment]
Perhaps, but I was suggesting something more like /opt/odoo-user/, and well, I know than not everybody is a Linux SysAdmin, but that doesn't mean than we shouldn't implement good practices. As I said, is not necessary, is just a *nice to have* feature.

**Comment by Yenthe666** [comment]
@sebastian-code understood! I'll keep this open but unchanged for now. Thanks for the idea though :smiley:
