### ISSUE TITLE
Linux Mint 19.1 Proposed Installation Changes

### ISSUE THREAD

**Issue by WonderM** [Yenthe666/InstallScript#141]
Please check : 
line 64, include python3-dev
line 72, pythothon-pypdf2 and pythothon-pypdf, isn't that a repeat?
also in line 72, change python-pybabel to python-babel

So far so good.

Thanks

**Comment by Ajilis** [comment]
do you have a problem with install ?

**Comment by WonderM** [comment]
I am proposing the update to the script as I have solved some of the challenges faced by others like (https://github.com/Yenthe666/InstallScript/issues/132).

I hope it will help ;)

**Comment by Ajilis** [comment]
I can test your update if you want ?

**Comment by WonderM** [comment]
Your help is appreciated. I will wait for your response

**Comment by Ajilis** [comment]
It seems not working for on a Ubuntu. but i redo a test this evening

**Comment by Ajilis** [comment]
Duplicate of #143

**Comment by Yenthe666** [comment]
Hi,

If anyone has time can you also try https://github.com/Yenthe666/InstallScript/tree/12-requirements ?
I've made the script use the requirements from the txt file, I wonder if it helps for Mint 19.1.
