### ISSUE TITLE
error ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by acsistemas** [Yenthe666/InstallScript#142]
After installing Odoo EC 11, I launches the form to create the first database, after a few seconds to give click on the button "Create Database" I get this error in the browser: ERR_EMPTY_RESPONSE

**Comment by Yenthe666** [comment]
Please give the output from the logfile

**Comment by acsistemas** [comment]
Good day. Thank you for responding. A moment ago I made an attempt again. I have used their "script install odoo v 11" many times since the last year that I am learning Odoo. But yesterday I wanted to do a new installation on an instance of VPS newly created, I got the error in the browser ERR_EMPTY_RESPONSE after you create your first database.

1.- This is shown in the terminal normally when you finish installing your "script Install" http://snap.ashampoo.com/3ilbniml5lSF0sDXxfeoyofWuegPcuE75P9kyLVVWj4W3aptFTC8dHVxm4iorMmo

2.- Then the form appears to create the first database http://snap.ashampoo.com/4fs7Aj5xxNE7ev4RPjMBEtDs8qeGgBFChXAiB7azLEXq1uCl8PnDDQVCBZji4ple And when I click on the Create Database button...

3.- The error is displayed and not let me do anything http://snap.ashampoo.com/Qi0Vp9Yxh72U4qAP2KX06DvDyuX6xQ1jz1ajZYBBx5wTNxEjC5jAA0ezT5Wmosvi

4.- Odoo Log: https://pastebin.com/0NFs9eWv (Comment, in this Log, appears my public IP, of my router)

5.- Postgresql main Log https://pastebin.com/Y84uSFYN

Additional comment; I have tried in a new drope of Digital Ocean and in a new instance of AWS EC2, in both I get the same problem

Please, I let's be helped to make work the Odoo, Thank you very much for its help. Kind regards

**Comment by Yenthe666** [comment]
Hi @acsistemas,

Hmm, interesting, there is literally nothing in the Odoo logs that hints about the issue. 
It looks like postgreSQL itself is dropping the connections for some reason. Do you also get it when you're in incognito mode and thus have no cookies or any values stored?

**Comment by acsistemas** [comment]
In Incognito mode I get another type of message, I gave click the Show Details button, and here I send the full capture http://snap.ashampoo.com/uLIq6TJtVUoZNMsq4V7yaJRLrJ48br3v7EG3YQppg7JTK5EHSdAtnSa95578ozTm

In Mozilla Firefox It appears like this: http://snap.ashampoo.com/Y4czp9NvjMO9toFqYRK2HNcSwLOwnjShgvBvUpL8517qJDBdVM882bRsMbj1K5CQ

**Comment by acsistemas** [comment]
Here https://pastebin.com/Y84uSFYN is a line that refers to something incomplete:
2019-02-12 13:51:10 UTC [6233-1] [unknown]@[unknown] LOG:  incomplete startup packet

**Comment by Yenthe666** [comment]
Are you sure you've correctly configured your DNS & all the other settings? You've changed nothing to the install script and did nothing after using the script?

**Comment by acsistemas** [comment]
I have configured the Google DNS on my network adapter http://snap.ashampoo.com/sab5WgHL09UaKRIhNjguKItBLkjS8YCQYeoQkV6JvskbftIt5OIix4JehtWFMzwG , and I have not modified anything from the install script file. As I mentioned, I installed several times Odoo 11, using his script and since yesterday I have the problem described

**Comment by Yenthe666** [comment]
Really looks like a misconfiguration somewhere though. Why don't you simply use a cloud server with Nginx and point to a domain?

**Comment by acsistemas** [comment]
Where can that bad setup be? I'm already in a drop of Digital Ocean, I also tried a AWS EC2, and the Odoo's I already have work with IP

**Comment by acsistemas** [comment]
Really well rare, 4 or 5 days ago was that I did the last installation of Odoo 11 using your script, no problems. And it's developing that Odoo like everyone else you install previously

**Comment by Yenthe666** [comment]
Yeah I really cannot think of what is wrong. I've actually installed an Odoo 11 today without any issues so that is why I find this odd. Can you access the Odoo by going to the IP:PORT directly?

**Comment by acsistemas** [comment]
This is the http://142.93.19.184:8069/ that should start, And shows me this http://snap.ashampoo.com/wl6Jaiqus1XTpzwlrjZwlDHqeapdaPjw2GA2OrPcmiw4CniTWCldGSTlSeoSTXkp

**Comment by acsistemas** [comment]
For you work this IP? http://142.93.19.184:8069/

**Comment by acsistemas** [comment]
It will not be that my public IP, of the router, has been blocked(banned) by any server or something that Odoo need to connect to work?

**Comment by Yenthe666** [comment]
@acsistemas that is possible, depending on your internal network configurations and setup. The IP is not reachable at all for me so it is not publicly available for sure.

**Comment by albosta** [comment]
i also face the same problem just from couple of days. i have been always using your script with no problem until few days back.

**Comment by acsistemas** [comment]
Hello @albosta , you have tried to change your public IP (from your router) and try to do the installation of Odoo with this script. I want to do this, but unfortunately my IP has not been able to change yet.

**Comment by albosta** [comment]
i deployed this script in VM locally. and i access Odoo internally IP:PORT. 
i never faced an issue with this script until recently.

**Comment by acsistemas** [comment]
Well, that's bad luck. So far I do not know because the script @Yenthe666 no longer works for me, often use it, and suddenly stopped working.

**Comment by bennals** [comment]
I'm also having the exact same problem.  This is for a fresh installation (yesterday) of Ubuntu server 16.04.5 in Virtualbox running on a Mac. I could connect to the database manager screen but after creating the first test database I can no longer connect with a browser (tried many).  Just getting the ERR_EMPTY_RESPONSE message.

Is it possible a recent change in Odoo source code that the script pulls from github is the problem?

**Comment by acsistemas** [comment]
> I'm also having the exact same problem. This is for a fresh installation (yesterday) of Ubuntu server 16.04.5 in Virtualbox running on a Mac. I could connect to the database manager screen but after creating the first test database I can no longer connect with a browser (tried many). Just getting the ERR_EMPTY_RESPONSE message.
> 
> Is it possible a recent change in Odoo source code that the script pulls from github is the problem?

I still think my router IP has been banned. At least change in a couple of weeks and I'll try again.

**Comment by bennals** [comment]
Hi guys.  I just tried a few things and the problem seems to be fixed (don't ask me why, but maybe someone smarter than me can figure it out based on what I did).  Here's what I did.

I'm actually using the version of the script provided by @chris001 (shame he seems to have drifted away from the project) [here](https://github.com/Yenthe666/InstallScript/blob/64694818b0568a5d1af2bd5079d7e9e8c31e85eb/odoo_install.sh)

There is a bug in the script related to installing ldap in line 488 which stops it from completing

`sudo -H pip3 install $_upgrade_flag gevent feedparser ldap lxml mako \`

So just remove 'ldap' (which appears to be deprecated anyway) and the script should complete.

`sudo -H pip3 install $_upgrade_flag gevent feedparser lxml mako \`

I thought I would try from a clean slate so I ran the script using the --uninstall option to begin with.

Then I manually installed the dependencies for 11.0 currently listed on the Odoo github repositry [here](https://github.com/odoo/odoo/blob/11.0/requirements.txt).  This was just in case something had changed in the dependencies that had not been updated in the script(??).

`pip3 install -r requirements.txt`

Then I ran the installation script again (linked above).  It completed without errors (just a warning about python2.7 deprecation) and I was able to create a new database with demo data and log in to it.  I also installed all the apps without issue.

Hopefully that helps someone.

**Comment by acsistemas** [comment]
> Hi guys. I just tried a few things and the problem seems to be fixed (don't ask me why, but maybe someone smarter than me can figure it out based on what I did). Here's what I did.
> 
> I'm actually using the version of the script provided by @chris001 (shame he seems to have drifted away from the project) [here](https://github.com/Yenthe666/InstallScript/blob/64694818b0568a5d1af2bd5079d7e9e8c31e85eb/odoo_install.sh)
> 
> There is a bug in the script related to installing ldap in line 488 which stops it from completing
> 
> `sudo -H pip3 install $_upgrade_flag gevent feedparser ldap lxml mako \`
> 
> So just remove 'ldap' (which appears to be deprecated anyway) and the script should complete.
> 
> `sudo -H pip3 install $_upgrade_flag gevent feedparser lxml mako \`
> 
> I thought I would try from a clean slate so I ran the script using the --uninstall option to begin with.
> 
> Then I manually installed the dependencies for 11.0 currently listed on the Odoo github repositry [here](https://github.com/odoo/odoo/blob/11.0/requirements.txt). This was just in case something had changed in the dependencies that had not been updated in the script(??).
> 
> `pip3 install -r requirements.txt`
> 
> Then I ran the installation script again (linked above). It completed without errors (just a warning about python2.7 deprecation) and I was able to create a new database with demo data and log in to it. I also installed all the apps without issue.
> 
> Hopefully that helps someone.

thank you very much for sharing. I will try it.

**Comment by Yenthe666** [comment]
Hi all,

I've just deployed a new server to test these reports (Ubuntu 18.04). Everything works fine out of the box. On a local IP, with port, internal IP and remote URL with certificate have all been tested.
There has to be some deployment issues at your end.

**Comment by bennals** [comment]
I was on 16.04 @Yenthe666.  Not sure about the others.  Might the issue be kept open in case it's something we can sort out for 16.04 installations as there are still a few of those around?

**Comment by elteatroescultura** [comment]
> Hi guys. I just tried a few things and the problem seems to be fixed (don't ask me why, but maybe someone smarter than me can figure it out based on what I did). Here's what I did.
> 
> I'm actually using the version of the script provided by @chris001 (shame he seems to have drifted away from the project) [here](https://github.com/Yenthe666/InstallScript/blob/64694818b0568a5d1af2bd5079d7e9e8c31e85eb/odoo_install.sh)
> 
> There is a bug in the script related to installing ldap in line 488 which stops it from completing
> 
> `sudo -H pip3 install $_upgrade_flag gevent feedparser ldap lxml mako \`
> 
> So just remove 'ldap' (which appears to be deprecated anyway) and the script should complete.
> 
> `sudo -H pip3 install $_upgrade_flag gevent feedparser lxml mako \`
> 
> I thought I would try from a clean slate so I ran the script using the --uninstall option to begin with.
> 
> Then I manually installed the dependencies for 11.0 currently listed on the Odoo github repositry [here](https://github.com/odoo/odoo/blob/11.0/requirements.txt). This was just in case something had changed in the dependencies that had not been updated in the script(??).
> 
> `pip3 install -r requirements.txt`
> 
> Then I ran the installation script again (linked above). It completed without errors (just a warning about python2.7 deprecation) and I was able to create a new database with demo data and log in to it. I also installed all the apps without issue.
> 
> Hopefully that helps someone.

I'm also having the exact same problem since 1 weeks ago.   This is for a fresh installation in Ubuntu server 16.04.    
Now I'm going to try the  @bennals  suggestions, I'll let you know if I can solve the problem.

**Comment by Yenthe666** [comment]
Hmm perhaps a 16.04 issue after all then. Keep me updated.

**Comment by acsistemas** [comment]
Muchas gracias (Thank you so much) @elteatroescultura

**Comment by acsistemas** [comment]
From time to time trying to and until yesterday that try again, and normal, installed as before giving this error. The only thing I did different was that the first database the create with sample data in the system, and it worked, already then create another database clean and everything well...

**Comment by bennals** [comment]
That may have been a difference when I had success as well @acsistemas.  I normally don't bother with creating a database with demo data but I did on the occasion that it worked (after not working on previous attempts).

**Comment by herawais** [comment]
I faced same problem, the issue was the persistantVolume storage was full , i increased the capacity of PV and it worked,
i am using Odoo based on Kubernetes
