### ISSUE TITLE
Detail Issue on install 

### ISSUE THREAD

**Issue by Ajilis** [Yenthe666/InstallScript#143]
1) 
Fresh new Ubuntu 18.04 64 bit 1024 ram / Vultr.com
apt-get update
apt-upgrade
reboot

2)
line 64, include python3-dev
line 72, change python-pybabel to python-babel

3) ./odoo_install.sh

2 errors 
![capture d ecran 2019-02-28 a 11 43 49](https://user-images.githubusercontent.com/24373892/53561503-5ec5fe80-3b4f-11e9-8543-0c76e596c8e0.png)

and 

![capture d ecran 2019-02-28 a 11 44 06](https://user-images.githubusercontent.com/24373892/53561523-69809380-3b4f-11e9-81df-a81f4b16ec98.png)

4) browse http://myip:8069

NOTHING
Reboot NOTHING

**Comment by Yenthe666** [comment]
Could you please give https://github.com/Yenthe666/InstallScript/tree/12-requirements a test?

**Comment by Ajilis** [comment]
tested same config:

Fresh new Ubuntu 18.04 64 bit 1024 ram / Vultr.com
apt-get update
apt-upgrade
reboot

result:

![capture d ecran 2019-03-01 a 22 20 34](https://user-images.githubusercontent.com/24373892/53718300-14989200-3e5b-11e9-982c-293efe270e81.png)

![capture d ecran 2019-03-01 a 22 20 56](https://user-images.githubusercontent.com/24373892/53718314-19f5dc80-3e5b-11e9-8c2e-73a61c868990.png)


    browse http://myip:8069

NOTHING
Reboot NOTHING

**Comment by ChristopheLux** [comment]
Hello

Install libpq-dev when installing postgresql and then it will go smoothly

Best regards

**Comment by Yenthe666** [comment]
See https://github.com/Yenthe666/InstallScript/commit/6fbec3cb31dd599db1af0b23ca387aa6130ab5d6
