### ISSUE TITLE
how can add https support?

### ISSUE THREAD

**Issue by nj-dream** [Yenthe666/InstallScript#144]
hello,

I use your script install odoo 12.It's very nice.thank you very much!
but I meet a problem.

I want to visit the odoo server by https.
I want to add ssl support and still use default port 8069,example https://odoo.mydomain.com:8069.
How to add ssl support in the odoo server?

thanks!

**Comment by Yenthe666** [comment]
Hi @nj-dream,

You'll need to setup Nginx, add a SSL certificate to the server and map them to eachother.
See http://nginx.org/en/docs/http/configuring_https_servers.html
