### ISSUE TITLE
odoo 11 - Imposible to work with workers >0

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#145]
Using this script, odoo works fine.

If you have 4 cores and plenty of ram , and you try to take advantage of the multiprocesor configuration, this happens

I have 4 cores, so in the config file, I set workers = 9

Restart odoo service

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

and the 4 cores start to work at 70% , even without anyone connected.

¿Someone knows to solve this?

Thanks

**Comment by Yenthe666** [comment]
Answered yourself at https://www.odoo.com/forum/help-1/question/odoo-11-is-not-working-with-multiprocessor-setings-workers-9-146761 so closing

**Comment by fgarcia-humanoide** [comment]
Thank you very much for answering,

In a new instalation I can`t solve the problem

It is impossible for me to have more than 0 workers

**Comment by Yenthe666** [comment]
There has to be a difference or issue though, I have dozens of installs running with workers without issues. Some thoughts or questions:

- Does your server have enough RAM?
- Are there errors in the logfiles?
- Are all required packages ok?
- Did you follow the guidelines and calculations from the official docs?
