### ISSUE TITLE
Images dont display for custom modules

### ISSUE THREAD

**Issue by cubu** [Yenthe666/InstallScript#146]
Fresh new Ubuntu 18.04 64 bit on EC2 (t2.medium)
Run the script succesfully.
Start server, install default app. Everything is great.

Problem raise when upload & install custom modules:

Step 1: set permission so can upload using SFTP:
sudo chown -R ubuntu:ubuntu /odoo/custom/addons
sudo chmod -R 755 /odoo/custom/addons

Step 2: upload custom modules to addons folder above

Step 3: search modules. Find, but no image for default module icon(https://example.com/xxx_theme/static/description/icon.png)

Step 4: Install complete, go to website configuration to change theme. Go to Home page -> No images.  

Step 5: Try to install other modules (not theme), every module I upload have trouble with image display too.

This one is recently. Before that I have no trouble install and config this theme using the same steps above.

**Comment by Yenthe666** [comment]
Hi @cubu,

This actually looks like invalid custom development. Have you tried putting your addon under `/static/src/img` and naming it `icon.jpg`? That should work.

**Comment by cubu** [comment]
These modules are I bought from odoo.com. It has been developed by other developers and it works perfect with local development.
The problem not just about icon, but all the pictures of the theme dont display also.

**Comment by cubu** [comment]
Here are interface of default editor when edit page:
![image](https://user-images.githubusercontent.com/2313183/54418620-09d1dd00-4738-11e9-92a7-2db3d7e5d635.png)

**Comment by Yenthe666** [comment]
Looks like you either have a rights issue or that your less didn't install correctly. Can you check both?

**Comment by cubu** [comment]
Thanks for your suggestion, turn out  the line 139 get errors:
`sudo apt-get install nodejs npm`
So no  `npm ` was installed.
I separate it to:
`sudo apt-get install nodejs -y `
 `sudo apt-get install  npm -y `
then it works.

**Comment by Yenthe666** [comment]
Odd that they worked separated but not combined. Happy that it is solved.

**Comment by cubu** [comment]
When I install it by hand, it require me to type "Y/N" to confirm, After I type "Y" and enter, it automatically Abort the command. Not sure why it behave like that. And it happen with not just one instance, but with all EC2 instances I use.

`ubuntu@ip-172-168-24-11:~$ sudo apt-get install nodejs npm
`
`Reading package lists... Done
`
`Building dependency tree
`
`Reading state information... Done
`
`nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
`
`nodejs set to manually installed.
`
`The following package was automatically installed and is no longer required:
`
`  libssl-doc
`
`Use 'sudo apt autoremove' to remove it.
`
`The following additional packages will be installed:
`
`  gyp javascript-common libjs-async libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libssl1.0-dev libuv1-dev node-abbrev node-ansi node-ansi-color-table
`
`  node-archy node-async node-balanced-match node-block-stream node-brace-expansion node-builtin-modules node-combined-stream node-concat-map node-cookie-jar
`
`  node-delayed-stream node-forever-agent node-form-data node-fs.realpath node-fstream node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs node-gyp
`
`  node-hosted-git-info node-inflight node-inherits node-ini node-is-builtin-module node-isexe node-json-stringify-safe node-lockfile node-lru-cache node-mime node-minimatch
`
`  node-mkdirp node-mute-stream node-node-uuid node-nopt node-normalize-package-data node-npmlog node-once node-osenv node-path-is-absolute node-pseudomap node-qs node-read
`
`  node-read-package-json node-request node-retry node-rimraf node-semver node-sha node-slide node-spdx-correct node-spdx-expression-parse node-spdx-license-ids node-tar
`
`  node-tunnel-agent node-underscore node-validate-npm-package-license node-which node-wrappy node-yallist nodejs-dev
`
`Suggested packages:
`
`  node-hawk node-aws-sign node-oauth-sign node-http-signature debhelper
`
`The following packages will be REMOVED:
`
`  libssl-dev
`
`The following NEW packages will be installed:
`
`  gyp javascript-common libjs-async libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libssl1.0-dev libuv1-dev node-abbrev node-ansi node-ansi-color-table
`
`  node-archy node-async node-balanced-match node-block-stream node-brace-expansion node-builtin-modules node-combined-stream node-concat-map node-cookie-jar
`
`  node-delayed-stream node-forever-agent node-form-data node-fs.realpath node-fstream node-fstream-ignore node-github-url-from-git node-glob node-graceful-fs node-gyp
`
`  node-hosted-git-info node-inflight node-inherits node-ini node-is-builtin-module node-isexe node-json-stringify-safe node-lockfile node-lru-cache node-mime node-minimatch
`
`  node-mkdirp node-mute-stream node-node-uuid node-nopt node-normalize-package-data node-npmlog node-once node-osenv node-path-is-absolute node-pseudomap node-qs node-read
`
`  node-read-package-json node-request node-retry node-rimraf node-semver node-sha node-slide node-spdx-correct node-spdx-expression-parse node-spdx-license-ids node-tar
`
`  node-tunnel-agent node-underscore node-validate-npm-package-license node-which node-wrappy node-yallist nodejs-dev npm
`
`0 upgraded, 73 newly installed, 1 to remove and 4 not upgraded.
`
`Need to get 4334 kB of archives.
`
`After this operation, 17.4 MB of additional disk space will be used.
`
`Do you want to continue? [Y/n] y
`
`Abort.
`
`ubuntu@ip-172-168-24-11:~$ sudo npm install -g less
`
`sudo: npm: command not found
`

**Comment by Yenthe666** [comment]
Uhh that is really odd. Why on earth does it aboard on a yes.. Never seen that before.
