### ISSUE TITLE
script not working with Google Cloud Platform VM

### ISSUE THREAD

**Issue by eversatis** [Yenthe666/InstallScript#149]
I am not sure if this issue is considered duplicated with the following one. If yes, please you can delete it.
https://github.com/Yenthe666/InstallScript/issues/148

I use the script in DO and linode many times before. None of theme had an issue. But I can not get it working on Google Cloud Platform(GCP). After the script run done, I got successful information as usual.
```
---------------------------------------------------------
The Odoo server is up and running. Specifications:
Port: 8069
User servDoneice: odoo
User PostgreSQL: odoo
Code location: odoo
Addons folder: odoo/odoo-server/addons/
Start Odoo service: sudo service odoo-server start
Stop Odoo service: sudo service odoo-server stop
Restart Odoo service: sudo service odoo-server restart
-----------------------------------------------------------
```

But the odoo server is not actually started.
$ sudo service odoo-server status
```
● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)
```

If I start it manually, I get the following status which I have no idea if it is normal.
$ sudo service odoo-server start
$ sudo systemctl status odoo-server
```
● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; generated)
   Active: active (exited) since Sat 2019-04-13 08:55:49 UTC; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25337 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/SUCCESS)

Apr 13 08:55:49 odoo12 systemd[1]: Starting LSB: Enterprise Business Applications...
Apr 13 08:55:49 odoo12 odoo-server[25337]: Starting odoo-server: odoo-server.
Apr 13 08:55:49 odoo12 systemd[1]: Started LSB: Enterprise Business Applications.
```

 But I still have no connect in the web browser. I did like more than dozens test by create instance again and again with no success.

**Comment by eversatis** [comment]
I read through the other issue and find the new script with requirements.txt is working for the GCP. Just want others know it if anyone use GCP. Thank you!

**Comment by Yenthe666** [comment]
@frankmiao2015 so you can confirm that the script from this branch (https://github.com/Yenthe666/InstallScript/tree/12-requirements) works? I've been asking multiple people for feedback but never heard back from anyone. So you can confirm that the default 12.0 branch does not work and the 12-requirements branch does work?

**Comment by eversatis** [comment]
> @frankmiao2015 so you can confirm that the script from this branch (https://github.com/Yenthe666/InstallScript/tree/12-requirements) works? I've been asking multiple people for feedback but never heard back from anyone. So you can confirm that the default 12.0 branch does not work and the 12-requirements branch does work?

Yes, I confirm  the branch https://github.com/Yenthe666/InstallScript/tree/12-requirements works for GCP vm. Just set up two instance yesterday. Deployed with ubuntu 18.04 LTS. Simply tick both http and https protocol and nothing more.  

And the default one is not working.

**Comment by Yenthe666** [comment]
Thanks for the feedback! I guess it is time to switch back to requirements.txt in my 12 branch then. I'll merge it in soon.

**Comment by Yenthe666** [comment]
Integrated in V12 at https://github.com/Yenthe666/InstallScript/commit/b9727fd7870efdcad561e07ba9bc478b3775c3f7

**Comment by mupagasi** [comment]
Hi @Yenthe666 it is still not showing anything. i/m using GCP Ubuntu 16.04.6 LTS, even after this fix you mentioned

2020-05-24 07:44:55,647 2313 INFO ? odoo: Odoo version 12.0
2020-05-24 07:44:55,648 2313 INFO ? odoo: Using configuration file at /etc/odoo-server.conf
2020-05-24 07:44:55,649 2313 INFO ? odoo: addons paths: ['/odoo/.local/share/Odoo/addons/12.0', '/odoo/odoo-server/addons', '/odoo/custom/addons', '/odoo/odoo-server/odoo/addons']
2020-05-24 07:44:55,649 2313 INFO ? odoo: database: default@default:default
2020-05-24 07:44:55,742 2313 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2020-05-24 07:44:55,852 2313 INFO ? odoo.service.server: HTTP service (werkzeug) running on ubuntu-xenial-odoo.us-central1-a.c.stately-bulwark-260318.internal:8069

**Comment by Yenthe666** [comment]
Well I've got three Odoo's running in Google Cloud without issues so it has to be a deployment issue at your end. Sure you're not missing firewalls or closed ports or something? ;)

**Comment by mupagasi** [comment]
That’s what i thought.. but i‘m not able to diagnosis Firewall issues.

**Comment by chris001** [comment]
Your web server port just needs to be open to the internet.  Either `443` if you're using `nginx` or `8069` or whatever other port `odoo` server listening on if you're not using a `HTTPS` front end proxy `nginx`.  Best practice of course is to use `nginx` `https`.
