### ISSUE TITLE
Question How to Install Odoo 9 with other port? (8070)

### ISSUE THREAD

**Issue by diezcode** [Yenthe666/InstallScript#15]
I have installed Odoo 8 debian.
When I use your installation script for odoo 9 on the same server, the Odoo 8 version is gone away. Because on port 8069 is Odoo 9.
I want Odoo8 on port 8069 and Odoo9 on port 8070.

Can you help me ?

I mean I don't want to overwrite the Path from Odoo 8 like /etc/init.d/odoo

**Comment by Yenthe666** [comment]
Hi diezcode,

You should modify the port in both scripts.
In V8 this line: https://github.com/Yenthe666/InstallScript/blob/8.0/odoo_install.sh#L30
In V9 this line: https://github.com/Yenthe666/InstallScript/blob/9.0/odoo_install.sh#L26
Be sure to give both Odoo version a different name too. 
In V8 this line: https://github.com/Yenthe666/InstallScript/blob/8.0/odoo_install.sh#L19
In V9 this line: https://github.com/Yenthe666/InstallScript/blob/9.0/odoo_install.sh#L19

When both the port and the name are different for both versions you will have two different Odoo's running side by side.

**Comment by diezcode** [comment]
Okay it WORKS, finally, thank you. 
But I see when I make a DB named = db_init in Odoo 8 you can't use the same dbname for Odoo9 dbs.

**Comment by diezcode** [comment]
Is Odoo9 using Postgrs 9.3 or 9.4 ?

**Comment by Yenthe666** [comment]
@diezcode that is correct. PostgreSQL cannot handle the same database names within scheme's, this is a problem everybody faces I'm afraid. Your only solution would be two postgreSQL versions/databases.. And both Odoo V8 and V9 use postgreSQL 9.3, it performs better than 9.4.

**Comment by diezcode** [comment]
Thanks for this
