### ISSUE TITLE
[11] PyYaml version update

### ISSUE THREAD

**Issue by misuv** [Yenthe666/InstallScript#150]
For Odoo 11, after using the script I couldn't install some Odoo modules. The solution was to reinstall PyYaml version below 4. So please update your script.

more info at [https://www.odoo.com/forum/help-1/question/having-yaml-constructor-constructorerror-while-installing-apps-sales-management-inventory-management-etc-147961](url)

**Comment by Yenthe666** [comment]
Hi @misuv,

Thanks for the report! Which PyYaml version exactly was installed on your server and which Ubuntu version are you using?

**Comment by misuv** [comment]
Ubuntu 16.04 and PyYAML==3.13 (Before was PyYAML 5.something)

**Comment by Yenthe666** [comment]
so my script installed 5 by default?

**Comment by misuv** [comment]
yes

**Comment by Yenthe666** [comment]
@misuv any chance you can test the branch https://github.com/Yenthe666/InstallScript/blob/12-requirements/odoo_install.sh and just changing the Odoo version to 11.0?

**Comment by ubntfox** [comment]
> @misuv any chance you can test the branch https://github.com/Yenthe666/InstallScript/blob/12-requirements/odoo_install.sh and just changing the Odoo version to 11.0?

Tested on Ubuntu 16.04 works perfect! thanks

**Comment by Yenthe666** [comment]
Closing as somebody reported that it is working and as all branches now run on requirements.txt, which auto fixes this.
