### ISSUE TITLE
Command not found message

### ISSUE THREAD

**Issue by alxolivares** [Yenthe666/InstallScript#152]
Hi!

Just after running the script a **command not found** message appears for the `sudo add-apt-repository` instruction.

![1](https://user-images.githubusercontent.com/13812335/57713361-522a5000-7640-11e9-8eaf-5ff3d5dee755.png)

I googled a little and this could be solved adding `sudo apt-get install software-properties-common -y` before this [line](https://github.com/Yenthe666/InstallScript/blob/12.0/odoo_install.sh#L47)

I think this behavior is due to the environment where I am using the script (Docker and Image of Ubuntu 18.04).

Regards

**Comment by Yenthe666** [comment]
Hmm odd, I haven't seen that before yet. Do you run this locally or?

**Comment by alxolivares** [comment]
I executed the script within a container running a ubuntu:18.04 image.

**Comment by emagdalenaC2i** [comment]
I have the same issue trying to install Odoo 11 and Odoo 13 in Ubuntu 18.04 in a VPS.
Seems that the VPS have previously Ubuntu 16 and when I upgraded to Ubuntu 18.04 all the sources in /etc/apt/sources.list are missing except 
`deb http://archive.ubuntu.com/ubuntu bionic main`

So I have to run:

`sudo apt-get install software-properties-common -y
sudo apt-add-repository universe
`
