### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by alzubairy** [Yenthe666/InstallScript#153]
I installed from the link, but the page orientation does not work from right to left.
Please Help

https://github.com/Yenthe666/InstallScript

**Comment by Yenthe666** [comment]
Hi,

This has nothing to do with my script. Have a look at an issue on the official Github tracker which explains what extra steps you need to take. See https://github.com/odoo/odoo/issues/29958#issuecomment-452635223

**Comment by alzubairy** [comment]
Hi,
When using these instructions, the direction works well.
https://www.odoo.com/documentation/12.0/setup/install.html#prepare

I do not install on Windows

My Server:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

Please help me

**Comment by Yenthe666** [comment]
Hmm I see your point now (https://www.odoo.com/documentation/12.0/setup/install.html#id4) to quote from the docs:

> on Linux, use your distribution’s package manager to install nodejs and npm. Once npm is installed, use it to install rtlcss:
$ sudo npm install -g rtlcss

As I don't have this package installed you cannot do RTL in Odoo. I guess I have to add it.

**Comment by alzubairy** [comment]
Thank you for your reply.

When will I be able to get the updated file so I can benefit from it?

My warm regards to you

**Comment by Yenthe666** [comment]
It is now by default supported since https://github.com/Yenthe666/InstallScript/commit/3f82153853f21164b492ade03368ae90a7f8403d

**Comment by alzubairy** [comment]
Very cool..

**Comment by alzubairy** [comment]
Hello..
I've been absent for a long time
I try to execute the file but the direction does not work

**Comment by ghost** [comment]
till today RTL is not working 2020

**Comment by j209** [comment]
test with node 10.

**Comment by ray-odoo** [comment]
Was unable to install rtlcss today with the v14 script.

What worked was:
`sudo npm i -g npm@latest
`

**Comment by qspaceit** [comment]
Hello..
The problem is in Odoo 13.0 and 14.0
And the solution that has worked for me so far is:

sudo apt update
npm install -g npm@latest
npm install -g n
n stable
npm install -g rtlcss
sudo apt remove nodejs npm
service odoo-server stop
service odoo-server start

With repeated execution
reboot
