### ISSUE TITLE
[12] Odoo 12 Installation problem ubuntu 18.04

### ISSUE THREAD

**Issue by vvgediya** [Yenthe666/InstallScript#156]
Hello,
I have tried to install Odoo 12.0 in Ubuntu 18.04 x64 in Vultr server but got an error. installation not work

![image](https://user-images.githubusercontent.com/11443543/58635783-5c20a400-830c-11e9-850a-911401a7a982.png)

![image](https://user-images.githubusercontent.com/11443543/58635802-6b075680-830c-11e9-96dd-410043d57555.png)

![image](https://user-images.githubusercontent.com/11443543/58635815-72c6fb00-830c-11e9-8e06-8ed56aa217f1.png)

**Comment by vvgediya** [comment]
Stoped during installation 

![image](https://user-images.githubusercontent.com/11443543/58870925-b9d33880-86de-11e9-85ba-4f7331164139.png)

![image](https://user-images.githubusercontent.com/11443543/58870948-c5befa80-86de-11e9-8085-5775ad8b1257.png)

**Comment by Yenthe666** [comment]
Looks very similar to https://github.com/Yenthe666/InstallScript/issues/155
Does it work at another provider (or locally)?

**Comment by vvgediya** [comment]
I have tried on Amazon AWS server

**Comment by Yenthe666** [comment]
Also without success?

**Comment by vvgediya** [comment]
First I have tried with Vultr server. On that try some solutions and it's work.

Then after 4 days, I have tried on AWS with 1 GB Memory then got an error. Then I have tried with 2 GB memory and it's installed.

**Comment by Yenthe666** [comment]
Yeah 1GB memory servers will absolutely fail. They'll run out of memory before they're through all dependencies and installs.
