### ISSUE TITLE
Daemon error in Ubuntu 16.04

### ISSUE THREAD

**Issue by muhammadfaizalns** [Yenthe666/InstallScript#157]
When I tried your script of odoo 12 in Ubuntu 16.04 I got daemon error. I have more than two GB of RAM also.

sudo /etc/init.d/odoo_12_e-server restart
Restarting odoo_12_e-server: start-stop-daemon: warning: failed to kill 27735: No such process
odoo_12_e-server.

**Comment by Yenthe666** [comment]
It looks like your instance didn't start. Is your Odoo available? Does it run after you restart it manually (or run it from the terminal)?
