### ISSUE TITLE
Arabic Support

### ISSUE THREAD

**Issue by mediaengagers** [Yenthe666/InstallScript#158]
@Yenthe666 It might be a good idea to install rtlcss for right to left languages support.

`sudo npm install -g rtlcss`

**Comment by Yenthe666** [comment]
Hi,

https://github.com/Yenthe666/InstallScript/issues/153 was the same report but I made a fix now!
Resolved it in https://github.com/Yenthe666/InstallScript/commit/3f82153853f21164b492ade03368ae90a7f8403d by installing `npm` and `rtlcss` by default.

Regards,
Yenthe
