### ISSUE TITLE
Odoo 9 - Ubuntu LTS 14.04 server or desktop?

### ISSUE THREAD

**Issue by yboujraf** [Yenthe666/InstallScript#16]
Dear,

I am trying to execute the script to install Odoo 9 but I have many errors :
- not found GIT
- not found nodejs
- ...

Somebody can confirm witch is the ubuntu LTS version and if this is a desktop or server edition we need to install?

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
Hi @yboujraf,

This script should both work on Ubuntu desktop and servers. I've personally tested this on 14.04.
Could you provide me with more details about the problems?

**Comment by yboujraf** [comment]
Dear,

Please find the environnement :

Linux by-odoo9-srv 2.6.32-74-server #142-Ubuntu SMP Tue Apr 28 10:12:19 UTC 2015 x86_64 GNU/Linux
Ubuntu 10.04.4 LTS

Welcome to the Ubuntu Server!
 * Documentation:  http://www.ubuntu.com/server/doc

  System information as of Wed Oct 21 20:06:13 CEST 2015

  System load:  0.0               Processes:           82
  Usage of /:   3.8% of 29.93GB   Users logged in:     0
  Memory usage: 2%                IP address for eth0: 192.168.0.194
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

New release 'precise' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Oct 21 19:48:51 2015 from 192.168.0.166
by@by-odoo9-srv:~$ 

Now, I try to execute the script  :

by-systems@by-odoo9-srv:~$ ./odoo_install.sh 

---- Update Server ----
[sudo] password for by-systems: 
Hit http://security.ubuntu.com lucid-security Release.gpg
Ign http://security.ubuntu.com/ubuntu/ lucid-security/main Translation-en_US
Ign http://security.ubuntu.com/ubuntu/ lucid-security/restricted Translation-en_US
Ign http://security.ubuntu.com/ubuntu/ lucid-security/universe Translation-en_US
Ign http://security.ubuntu.com/ubuntu/ lucid-security/multiverse Translation-en_US
Hit http://security.ubuntu.com lucid-security Release
Hit http://be.archive.ubuntu.com lucid Release.gpg
Ign http://be.archive.ubuntu.com/ubuntu/ lucid/main Translation-en_US
Ign http://be.archive.ubuntu.com/ubuntu/ lucid/restricted Translation-en_US
Ign http://be.archive.ubuntu.com/ubuntu/ lucid/universe Translation-en_US
Ign http://be.archive.ubuntu.com/ubuntu/ lucid/multiverse Translation-en_US
Hit http://be.archive.ubuntu.com lucid-updates Release.gpg
Ign http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main Translation-en_US
Ign http://be.archive.ubuntu.com/ubuntu/ lucid-updates/restricted Translation-en_US
Ign http://be.archive.ubuntu.com/ubuntu/ lucid-updates/universe Translation-en_US
Ign http://be.archive.ubuntu.com/ubuntu/ lucid-updates/multiverse Translation-en_US
Hit http://security.ubuntu.com lucid-security/main Packages
Hit http://be.archive.ubuntu.com lucid Release                    
Hit http://security.ubuntu.com lucid-security/restricted Packages              
Hit http://security.ubuntu.com lucid-security/main Sources
Hit http://security.ubuntu.com lucid-security/restricted Sources
Hit http://security.ubuntu.com lucid-security/universe Packages
Hit http://security.ubuntu.com lucid-security/universe Sources
Hit http://security.ubuntu.com lucid-security/multiverse Packages
Hit http://security.ubuntu.com lucid-security/multiverse Sources
Hit http://be.archive.ubuntu.com lucid-updates Release
Hit http://be.archive.ubuntu.com lucid/main Packages
Hit http://be.archive.ubuntu.com lucid/restricted Packages
Hit http://be.archive.ubuntu.com lucid/main Sources
Hit http://be.archive.ubuntu.com lucid/restricted Sources
Hit http://be.archive.ubuntu.com lucid/universe Packages
Hit http://be.archive.ubuntu.com lucid/universe Sources
Hit http://be.archive.ubuntu.com lucid/multiverse Packages
Hit http://be.archive.ubuntu.com lucid/multiverse Sources
Hit http://be.archive.ubuntu.com lucid-updates/main Packages
Hit http://be.archive.ubuntu.com lucid-updates/restricted Packages
Hit http://be.archive.ubuntu.com lucid-updates/main Sources
Hit http://be.archive.ubuntu.com lucid-updates/restricted Sources
Hit http://be.archive.ubuntu.com lucid-updates/universe Packages
Hit http://be.archive.ubuntu.com lucid-updates/universe Sources
Hit http://be.archive.ubuntu.com lucid-updates/multiverse Packages
Hit http://be.archive.ubuntu.com lucid-updates/multiverse Sources
Reading package lists... Done              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

---- Install PostgreSQL Server ----
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-2.6.32-38 linux-headers-2.6.32-38-server
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpq5 postgresql-8.4 postgresql-client-8.4 postgresql-client-common
  postgresql-common ssl-cert
Suggested packages:
  oidentd ident-server postgresql-doc-8.4
The following NEW packages will be installed:
  libpq5 postgresql postgresql-8.4 postgresql-client-8.4
  postgresql-client-common postgresql-common ssl-cert
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 5,201kB of archives.
After this operation, 23.0MB of additional disk space will be used.
Get:1 http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main libpq5 8.4.22-0ubuntu0.10.04.1 [108kB]
Get:2 http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main postgresql-client-common 106ubuntu3 [52.6kB]
Get:3 http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main postgresql-client-8.4 8.4.22-0ubuntu0.10.04.1 [831kB]
Get:4 http://be.archive.ubuntu.com/ubuntu/ lucid/main ssl-cert 1.0.23ubuntu2 [10.9kB]
Get:5 http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main postgresql-common 106ubuntu3 [89.9kB]
Get:6 http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main postgresql-8.4 8.4.22-0ubuntu0.10.04.1 [4,074kB]
Get:7 http://be.archive.ubuntu.com/ubuntu/ lucid-updates/main postgresql 8.4.22-0ubuntu0.10.04.1 [35.3kB]
Fetched 5,201kB in 1s (3,835kB/s)   
Preconfiguring packages ...
Selecting previously deselected package libpq5.
(Reading database ... 63986 files and directories currently installed.)
Unpacking libpq5 (from .../libpq5_8.4.22-0ubuntu0.10.04.1_amd64.deb) ...
Selecting previously deselected package postgresql-client-common.
Unpacking postgresql-client-common (from .../postgresql-client-common_106ubuntu3_all.deb) ...
Selecting previously deselected package postgresql-client-8.4.
Unpacking postgresql-client-8.4 (from .../postgresql-client-8.4_8.4.22-0ubuntu0.10.04.1_amd64.deb) ...
Selecting previously deselected package ssl-cert.
Unpacking ssl-cert (from .../ssl-cert_1.0.23ubuntu2_all.deb) ...
Selecting previously deselected package postgresql-common.
Unpacking postgresql-common (from .../postgresql-common_106ubuntu3_all.deb) ...
Selecting previously deselected package postgresql-8.4.
Unpacking postgresql-8.4 (from .../postgresql-8.4_8.4.22-0ubuntu0.10.04.1_amd64.deb) ...
Selecting previously deselected package postgresql.
Unpacking postgresql (from .../postgresql_8.4.22-0ubuntu0.10.04.1_all.deb) ...
Processing triggers for man-db ...
Processing triggers for ureadahead ...
ureadahead will be reprofiled on next reboot
Setting up libpq5 (8.4.22-0ubuntu0.10.04.1) ...

Setting up postgresql-client-common (106ubuntu3) ...
Setting up postgresql-client-8.4 (8.4.22-0ubuntu0.10.04.1) ...
update-alternatives: using /usr/share/postgresql/8.4/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode.

Setting up ssl-cert (1.0.23ubuntu2) ...

Setting up postgresql-common (106ubuntu3) ...
Adding user postgres to group ssl-cert
Building PostgreSQL dictionaries from installed myspell/hunspell packages...

Setting up postgresql-8.4 (8.4.22-0ubuntu0.10.04.1) ...
Creating new cluster (configuration: /etc/postgresql/8.4/main, data: /var/lib/postgresql/8.4/main)...
Moving configuration file /var/lib/postgresql/8.4/main/postgresql.conf to /etc/postgresql/8.4/main...
Moving configuration file /var/lib/postgresql/8.4/main/pg_hba.conf to /etc/postgresql/8.4/main...
Moving configuration file /var/lib/postgresql/8.4/main/pg_ident.conf to /etc/postgresql/8.4/main...
Configuring postgresql.conf to use port 5432...
update-alternatives: using /usr/share/postgresql/8.4/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode.
 * Starting PostgreSQL 8.4 database server                               [ OK ] 

Setting up postgresql (8.4.22-0ubuntu0.10.04.1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place

---- Creating the ODOO PostgreSQL User  ----

---- Install tool packages ----
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wget is already the newest version.
Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package git has no installation candidate

---- Install python packages ----
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-simplejson is already the newest version.
E: Couldn't find package python-unittest2

---- Install python libraries ----
sudo: pip: command not found

--- Install other required packages
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Couldn't find package node-clean-css
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Couldn't find package node-less
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Couldn't find package python-gevent

---- Install wkhtml and place shortcuts on correct place for ODOO 9 ----
--2015-10-21 20:09:43--  http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
Resolving download.gna.org... 78.40.125.79
Connecting to download.gna.org|78.40.125.79|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14166104 (14M) [application/x-debian-package]
Saving to: `wkhtmltox-0.12.1_linux-trusty-amd64.deb'

100%[========================================================================================================================================================>] 14,166,104  2.22M/s   in 7.8s    

2015-10-21 20:09:51 (1.74 MB/s) - `wkhtmltox-0.12.1_linux-trusty-amd64.deb' saved [14166104/14166104]

sudo: gdebi: command not found

---- Create ODOO system user ----
Adding user `odoo' to group `sudo' ...
Adding user odoo to group sudo
Done.

---- Create Log directory ----

==== Installing ODOO Server ====
sudo: git: command not found

---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
cp: cannot stat `/odoo/odoo-server/debian/openerp-server.conf': No such file or directory
chown: cannot access `/etc/odoo-server.conf': No such file or directory
chmod: cannot access `/etc/odoo-server.conf': No such file or directory
* Change server config file
sed: can't read /etc/odoo-server.conf: No such file or directory
sed: can't read /etc/odoo-server.conf: No such file or directory
* Create startup file
bash: /odoo/odoo-server/start.sh: No such file or directory
bash: /odoo/odoo-server/start.sh: No such file or directory
chmod: cannot access `/odoo/odoo-server/start.sh': No such file or directory
* Create init file
* Security Init File
* Change default xmlrpc port
* Start ODOO on Startup
 Adding system startup for /etc/init.d/odoo-server ...
   /etc/rc0.d/K20odoo-server -> ../init.d/odoo-server
   /etc/rc1.d/K20odoo-server -> ../init.d/odoo-server
   /etc/rc6.d/K20odoo-server -> ../init.d/odoo-server
   /etc/rc2.d/S20odoo-server -> ../init.d/odoo-server
   /etc/rc3.d/S20odoo-server -> ../init.d/odoo-server
   /etc/rc4.d/S20odoo-server -> ../init.d/odoo-server
   /etc/rc5.d/S20odoo-server -> ../init.d/odoo-server
* Starting Odoo Service
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 8069
User service: odoo
User PostgreSQL: odoo
Code location: odoo
Addons folder: odoo/odoo-server/addons/
Start Odoo service: sudo service odoo-server start
Stop Odoo service: sudo service odoo-server stop
Restart Odoo service: sudo service odoo-server restart
-----------------------------------------------------------

Please have a look in the log, you will find error with git, python, nodes, ...

Thanks if you can help us. We use your script available in the github.

Best Regards,
Youssef

**Comment by yboujraf** [comment]
Dear,

I found the issue.

This is the version of the Ubuntu LTS server 14.04.04

I fixed by using Ubuntu LTS server 14.04.03

Otherwise, very nice the script. Perfect.

Now just missing to install nginx srv

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
@yboujraf,

Thanks for the detailed feedback. Looks like on your first try you used Ubuntu 10.04, which doesn't seem to have all those packages I guess?

**Comment by yboujraf** [comment]
Dear,

Yes it is.

Last but not the least,

Do you have any link where I can find the script to install nginx on a server and the setup for Odoo 9 please?

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
@yboujraf okay thanks for the feedback. I should check out what 10.04 needs in place of these..
As for the nginx on a server: I would like to add this in my current script but my knowledge is not good enough. There are some guides around though, such as https://gist.githubusercontent.com/parthivgls/c287f39cd148da646c63/raw/odoo_nginx.sh and http://www.nkr1ptd.com/2014/11/using-nginx-with-odoo-version-8-on.html

**Comment by yboujraf** [comment]
Dear,

Thanks,

I am trying to install a vm then I will let you know my status.

Otherwise, to close this issue,

How to enable apt-get update and apt-get upgrade for odoo package?

To be sure we can keep the odoo up to date?

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
@yboujraf apt-get update and upgrade is for upgrading your Linux environment / software. This has nothing to do with Odoo.
The Odoo can be updated from within the folder with a git update.

**Comment by yboujraf** [comment]
I followed this :
https://www.odoo.com/documentation/8.0/setup/install.html#deb

To install Odoo 8.0 on Debian-based distribution, execute the following commands as root:

# wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
# echo "deb http://nightly.odoo.com/8.0/nightly/deb/ ./" >> /etc/apt/sources.list
# apt-get update && apt-get install odoo
This will automatically install all dependencies, install Odoo itself as a daemon and automatically start it.

I 'd like to be sure if any new update from odoo I will be able to uptade the server without impacting the database.

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
@yboujraf I think you are really confusing things.. If I'm not mistaking this guide is used to setup Odoo 8.0 from scratch and install everything.
My script does the same, but in another way, so you now have two Odoo instances?
I'm not sure how the Odoo way works but with my script you can always update the code.

**Comment by yboujraf** [comment]
Dear,

Thanks,

I understand.

So that means, if new odoo version, just git clone, .... is it right?

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
@yboujraf just navigate in to your folder (for example /odoo/odoo-server) and run the following command:
```
git pull origin 9.0
```

As for configuring an Nginx, I just setup one. Commands:
```
sudo apt-get install nginx
sudo service nginx start
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo nano /etc/nginx/conf.d/openerp.conf
```

Add the following code in the file:
```
#worker_processes  1;

#events {
#    worker_connections  1024;
#}

    server {
        listen  80;
        server_name 127.0.0.1;
        location /socket.io {
            proxy_pass   http://127.0.0.1:8080;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_redirect off;
         }

        location / {
            proxy_pass   http://127.0.0.1:8080;
        }
    }
```

Finally, restart Nginx:
```
sudo service nginx restart
```

This should convert a running Odoo on port 8080 to running on port 80 (http://localhost)

**Comment by yboujraf** [comment]
Dear,

Probably you may help me about this issue.

I checked if any modules need to be updated.

I did : Settings> Modules > Update Modules List

Then Odoo lists all the modules need to be updated.

I selected the update and then we got this error :

![29-11-15 22-09-02](https://cloud.githubusercontent.com/assets/6151258/11473357/343b41cc-9772-11e5-9e73-d26c30737929.png)

This is a permission issue.

Do you know how to give the correct permission to the web browser to update the addons folder?

It will be great to add this permission in the installation script.

Best Regards,
Youssef

**Comment by Yenthe666** [comment]
Hi Youssef,

If you're really lazy and need it fixed asap:
```
sudo chmod -R 777 /odoo/odoo-server/addons
```

**Comment by yboujraf** [comment]
Dear Yenthe,

Thanks a lot for your quick answer.

I thought the same.

But if there is another way more secure, it will be welcome.

Best Regards,
Youssef

2015-11-30 15:10 GMT+01:00 Yenthe <notifications@github.com>:

**Comment by Yenthe666** [comment]
Well something along the lines of this would be better:
```
sudo chmod -R 755 /odoo/odoo-server/addons
```

Or to give only rights for one user:
```
sudo chown -R username:group directory
```

**Comment by yboujraf** [comment]
Thanks

2015-11-30 16:09 GMT+01:00 Yenthe <notifications@github.com>:
