### ISSUE TITLE
Cannot run server local

### ISSUE THREAD

**Issue by kamalkech** [Yenthe666/InstallScript#161]
System: 
`  4.19.56-1-MANJARO
`

after run server with command ./odoo-bin i get this error : 

```
/usr/lib/python3.7/site-packages/PIL/Image.py:115: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 4.0.0
Pillow version: 6.0.0
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/run/media/kamal/9C869EE0869EB9EA/Projets/Odoo/DD/odoo-server/odoo/__init__.py", line 106, in <module>
    from . import modules
  File "/run/media/kamal/9C869EE0869EB9EA/Projets/Odoo/DD/odoo-server/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/run/media/kamal/9C869EE0869EB9EA/Projets/Odoo/DD/odoo-server/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/run/media/kamal/9C869EE0869EB9EA/Projets/Odoo/DD/odoo-server/odoo/tools/__init__.py", line 13, in <module>
    from .image import *
  File "/run/media/kamal/9C869EE0869EB9EA/Projets/Odoo/DD/odoo-server/odoo/tools/image.py", line 7, in <module>
    from PIL import Image
  File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 100, in <module>
    __version__))
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 4.0.0
Pillow version: 6.0.0
```

**Comment by Yenthe666** [comment]
Hi,

The dependencies from Odoo require `Pillow` 4.0.0 and I assume you have 6.0.0 installed?
See https://github.com/odoo/odoo/blob/30f760d53491712bc639105c146c7d673c7fb90d/requirements.txt#L23

**Comment by ulisesgamboa** [comment]
Hi Yenthe

I have error to install lxml dependency during the installation, could you help me?

    creating build/temp.linux-x86_64-3.6/src/lxml
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/include/python3.6m -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-3.6/src/lxml/lxml.etree.o -w
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    creating tmp
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitta6threy.c -o tmp/xmlXPathInitta6threy.o
    /tmp/xmlXPathInitta6threy.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
     main (int argc, char **argv) {
     ^~~~
    cc tmp/xmlXPathInitta6threy.o -lxml2 -o a.out
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c_2h_92f/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-67bhmnm9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-c_2h_92f/lxml/

Regards
