### ISSUE TITLE
 Running setup.py install for lxml 

### ISSUE THREAD

**Issue by jayo2005** [Yenthe666/InstallScript#162]
Ive tried this on 3 or 4 setups. It is always getting stuck on  Running setup.py install for lxml 

this is  ODoo 12

**Comment by Yenthe666** [comment]
Do you have a server with just 512MB or 1GB of RAM maybe?

**Comment by jayo2005** [comment]
It's was AWS free tier. I tried on my own of and it's working fine. Just
note for other users the script does not work with AWS free tier

**Comment by Yenthe666** [comment]
Yeah, that is because the RAM is too low. The script tries to install all dependencies but they're too heavy weighted for very low/light VM's.

**Comment by ricoshocks** [comment]
Took me ages to solve this.

SOLVED: Create a swap 1G or 2G

Ubuntu: https://linuxize.com/post/how-to-add-swap-space-on-ubuntu-18-04/ 
Centos 7/8: https://linuxize.com/post/how-to-add-swap-space-on-centos-8/
