### ISSUE TITLE
odoo13 problem install

### ISSUE THREAD

**Issue by evansadji** [Yenthe666/InstallScript#168]
odoo13 can not find folder odoo-server

**Comment by evansadji** [comment]
i'm using ubuntu 18.04

**Comment by Yenthe666** [comment]
Hi,

That is because the 13.0 branch at Odoo its side does not exist yet. Switch this value:
https://github.com/Yenthe666/InstallScript/blob/b243ef7df815bd69320420f22956fb2c970ea5b6/odoo_install.sh#L27
to "master" for now. Odoo V13 is not yet officially released.
