### ISSUE TITLE
Install Enterprise Edition question

### ISSUE THREAD

**Issue by sel-carlitos** [Yenthe666/InstallScript#169]
Hi guys, 
Very beautiful script! Works flawlessly to get things up and running quickly in a brand new Ubuntu Server. I am setting IS_ENTERPRISE="**True**" and after the script completes successfully I reboot the server. When the server fires up and I go to IP:8069 I can only see the community edition running?? Is there anything else I am missing?? I mean, I have entered my user/password for github which has access to the odoo enterprise repository. Any hints/clues of what's going on will be greatly appreciated. 

Regards, 

Carlos

**Comment by sel-carlitos** [comment]
Sorry. I just realized that I had a problem accessing the enterprise repo with my account. So once I resolved that, and run the script again, the sources were copied to /odoo/enterprise/addons

**Comment by Yenthe666** [comment]
Good to hear :)
