### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cvuio_pp/psycopg2/

### ISSUE THREAD

**Issue by mfhm95** [Yenthe666/InstallScript#170]

**Comment by Yenthe666** [comment]
Euhh it looks like the package `psycopg2` itself failed installing, nothing related to the script 😉

**Comment by TheRealHatCoder** [comment]
Hi,
Having same problem, with following error message.

> Error: b'You need to install postgresql-server-dev-NN for building a server-side extension or libpq-dev for building a client-side application.\n'

In order to fix it, I had to 
> apt-get install postgresql-server-dev-11

Hope this helps you.

**Comment by Yenthe666** [comment]
@BIZ4Africa was it solved after installing the dev package?
