### ISSUE TITLE
odoo script 13 enterprise not working

### ISSUE THREAD

**Issue by selfietv110** [Yenthe666/InstallScript#177]
odoo script 13 enterprise not working i follow your step once we installed when i check the version it's same as Community Edition  
![odoo](https://user-images.githubusercontent.com/55563426/66560932-18169900-eb61-11e9-83b0-305053966f33.png)

**Comment by Yenthe666** [comment]
Hi @selfietv110,

Are you sure that you've set the enterprise version to true? I've installed another V13 today without any issues. Can you please list the steps you did? Are you a user with access to the enterprise code?

**Comment by selfietv110** [comment]
Yes i was done as it's sir when i installed its' asked GitHub user name and
password last step at that time i use my git hub login but they mention we
need enterprise partner may be yours login id

i was do as it's how u kept in git hub step please help me

**Comment by Yenthe666** [comment]
Well, that means you're not an official odoo partner and in this case you have no rights to that repository. The only way to be able to install enterprise is if you're an official odoo partner. ;)

**Comment by selfietv110** [comment]
official odoo partner ..?  i need to buy enterprise  from the official web site then what is use from here sir if i can  go direct download and purchase i don't need  i need to crack how i can  do without purchase ..?

**Comment by Yenthe666** [comment]
Only official odoo partners can use the enterprise code from Github. If you've bought the enterprise version and don't have a partner you've gotten packages that contain the code to put it on your system. If you don't have both there is no way for you to legally obtain it.
