### ISSUE TITLE
[13] backup problem - Database backup error: Command `pg_dump` not found.

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#178]
When I try to backup from /web/database/backup

This error appears

Database backup error: Command `pg_dump` not found.

The install script works fine.

Is it a bad instalation of postgres?

**Comment by Yenthe666** [comment]
I assume the script has copied over the configuration value `pg_path = None` in your config file. If it is set to `None` it will give a false positive resuling in this traceback. Can you check the configuration file, remove this option, restart the Odoo instance and try again? That should solve it.

**Comment by Ougda-chams** [comment]
Thank you!!
