### ISSUE TITLE
[All] Wishlist: Use Random master password instaed of 'admin'

### ISSUE THREAD

**Issue by sswapnesh** [Yenthe666/InstallScript#180]
Hello,

So I just discovered ~2~ **5** more Instances (~One~ **Two** Production) up and running with the "admin" master password.
I checked and Initial installation was made using this script. (It's definitely because of User/Admin choice, not this script)

I believe we should Implement Random password instead of default "admin"

What do you think about this?

EDIT: Only when `OE_SUPERADMIN` is `admin`

**Comment by Yenthe666** [comment]
Hi @sswapnesh,

Thanks for your suggestion. In an ideal world I believe we should indeed do this. The thing is that this script is created for pretty inexperienced people with not a lot of Odoo knowledge.
If I implement a way that generates a random administrator password I'm pretty sure that quite some people will not be able to find it (in the Odoo configuration file) as they don't know enough about the installation and running process of Odoo.
Maybe it could work out if I generate a random password, set this random password and then print it at the end of the script? Although I'm still afraid quite some people will not read the text and will then be creating issues here.

Regards,
Yenthe

**Comment by sswapnesh** [comment]
Hello,

Yes that should be more useful to Have password Printed at the End.( And also in README file)

If they can give Executable access to script  and add custom addons by them selves, then I believe they can manage to Get master password as well.

I can start working on this next month if you have plans for this Enhancements.

**Comment by Charly-HID** [comment]
Hello, I am part of the group of those inexperienced people, following the steps of your tutorial: https://www.oocademy.com/v14.0/tutorial/installing-odoo-14-on-ubuntu-59 in the configuration of the script I left it like this but now I don't know where to find the master password, could you guide me where to find it, thanks.

**Comment by Yenthe666** [comment]
under /etc in your configuration file (usually something like /etc/odoo14-server.conf)
