### ISSUE TITLE
Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /odoo/odoo/13.0/requirements.txt

### ISSUE THREAD

**Issue by kidddjh** [Yenthe666/InstallScript#182]
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff719c26610>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=15)')': /odoo/odoo/13.0/requirements.txt

**Comment by Yenthe666** [comment]
There was most likely a temporarely downtime for Github or your internet connection was too slow. Could you recheck? :)
