### ISSUE TITLE
RTL

### ISSUE THREAD

**Issue by alzubairy** [Yenthe666/InstallScript#183]
The installation script is great work, but the direction does not work.
I hope you can handle it

**Comment by Yenthe666** [comment]
We install the RTL dependencies through though:
https://github.com/Yenthe666/InstallScript/blob/7f8fd7908e40a39b27f22bfe341096a51bcf7b26/odoo_install.sh#L72-L73
If you have issues with RTL itself you'll need to be at Odoo itself ;)

**Comment by alzubairy** [comment]
but
When I use these instructions in the installation, the direction is working

http://www.odoo.com/documentation/13.0/setup/install.html#prepare

**Comment by ghost** [comment]
> but
> When I use these instructions in the installation, the direction is working
> 
> http://www.odoo.com/documentation/13.0/setup/install.html#prepare

I agree with you same issues exactly i face, I think Yenthe need to do some tests

**Comment by Yenthe666** [comment]
I don't really `need` to do anything, this script is a best effort basis. ;)

**Comment by ghost** [comment]
> I don't really `need` to do anything, **this script is a best effort basis**. ;)

**its the best**, I think most odoo's  like it, and they depend on it, 
for me I am just a year in this filed with slow internet, I am  totaly relay on it to save on the hard times, 
on my limited experience I spend about 2 months, with  2 hours to fix it, but I could not find a clue 
and truly **you dont 'need' do anything**,  
but  we like it so we like to have it works for RTL.. "it is you master piece"

in the end thank for this valuable tools. 
Ahmed

**Comment by Yenthe666** [comment]
I'll keep https://github.com/Yenthe666/InstallScript/issues/190 open for it but I'm pretty swamped with work these days. As I'm not an RTL user and I'm low on time it might take a while though, sorry

**Comment by anoureldin** [comment]
> it so we like to have it works for RTL.. "it is you master piece"

i tried alot to make RTL work but no luck 
then i installed it from odoo Documentation it's good and easy

**Comment by Yenthe666** [comment]
@anoureldin @ajasimiq I believe https://github.com/Yenthe666/InstallScript/commit/e2693d5d5c20edca213eb4686e362e4eb14b10c3 has fixed this for the 13.0 script. Can one of you test/confirm this? In the other thread one person confirmed this fixes it but would love a second opinion.

**Comment by anoureldin** [comment]
> @anoureldin @ajasimiq I believe [e2693d5](https://github.com/Yenthe666/InstallScript/commit/e2693d5d5c20edca213eb4686e362e4eb14b10c3) has fixed this for the 13.0 script. Can one of you test/confirm this? In the other thread one person confirmed this fixes it but would love a second opinion.



working great 
thanks

**Comment by ghost** [comment]
> @anoureldin @ajasimiq I believe [e2693d5](https://github.com/Yenthe666/InstallScript/commit/e2693d5d5c20edca213eb4686e362e4eb14b10c3) has fixed this for the 13.0 script. Can one of you test/confirm this? In the other thread one person confirmed this fixes it but would love a second opinion.

Hi Yenthe
Thans to you and for any other contribution to find the issue of path
Yes I confirm that RTL issue solved 
Thanks again 
Ahmed

**Comment by Yenthe666** [comment]
Awesome, thanks guys! I've also fixed it in V12 at https://github.com/Yenthe666/InstallScript/commit/e4284fadb2272cba9ad0772fe194041a89d5db27.

**Comment by ghost** [comment]
I use 13 version to install 12 after fix script variables it works for me.


Be


Ahmed




Get Outlook for Android







On Fri, Apr 17, 2020 at 10:01 AM +0300, "Yenthe Van Ginneken" <notifications@github.com> wrote:















Awesome, thanks guys! I've also fixed it in V12 at e4284fa.

**Comment by Yenthe666** [comment]
@ajasimiq you can use the 12.0 version now too, should work just fine :)
