### ISSUE TITLE
adding extra drive or installing to specific drive 

### ISSUE THREAD

**Issue by fazeelshahzad** [Yenthe666/InstallScript#184]
I have an online server which space is getting low. 
when i add some space to the existing server it creates another location (partition drive like in windows) 
what i want to do is , i will purchase a new server with ~250gb SSD and ~500gb normal. but i want to install odoo on 500 gb space not on SSD. is it possible to install on other location?
right now i'm working on Odoo 11. Kindly help me

**Comment by Yenthe666** [comment]
@fazeelshahzad create a virtual folder that maps to your new drive to the location you want to install the Odoo. Configure the script with this path & that should work (haven't done it myself so this is theoretical ;) )
