### ISSUE TITLE
Wkhtmltopdf missing?

### ISSUE THREAD

**Issue by mihaisumedre** [Yenthe666/InstallScript#185]
Clean Ubuntu 18.04 system, installed odoo 12 via script. Odoo shows an error that wkhtmltopdf is missing, though it's install option was set to true in the script. Any idea why?

**Comment by Yenthe666** [comment]
@mihaisumedre is there anything in the output from the installation that shows errors?
Can you access and download the Wkhtmltopdf from these URL's?
https://github.com/Yenthe666/InstallScript/blob/7f8fd7908e40a39b27f22bfe341096a51bcf7b26/odoo_install.sh#L39-L40

**Comment by mihaisumedre** [comment]
@Yenthe666 Yes, I'm able to access them both from the machine itself. Also, everything else seams to have been completed successfully. Unfortunately I don't have the install output any more. I just presumed that everything went well as it finished installing odoo and i rebooted the machine. I'll just create a new machine and get back with the error.

**Comment by Yenthe666** [comment]
Thanks, I'd need to see the traceback to know what went wrong. I've recently installed a few 12.0's without issues so I'm curious.
Which hosting provider by the way?

**Comment by mihaisumedre** [comment]
It's self-hosted on an ESXi server. I just recreated the steps (just for wkhtmltopdf) on the vm where it was missing before and it went without problems, works ok (manually followed the steps from the script). Thus, it looks like it was a one-time problem (like not being able to fetch the package at that specific time, can't know for sure). I'll still create a new machine, just to give you proper feedback and close the issue. Thanks for your help!

**Comment by Yenthe666** [comment]
Okay thanks! I assume it was a networking issue for a short while. Looking forward to hear back.

**Comment by mihaisumedre** [comment]
Just tested the script on a new installation - wkhtmltopdf worked without problems. I was probably just a temporary networking hickup. Thanks and keep up the good work. Your script has saved me a lot of time, indeed!

**Comment by Yenthe666** [comment]
That's good to hear, I'm happy about that.
Thanks for rechecking and for the kind words :)
