### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by frxnco** [Yenthe666/InstallScript#188]
Hello.

I installed odoo community v12 with InstallScript on a cloud server. This installation is running into server. But I can't connect, in browser appears "ERR_EMPTY_RESPONSE" message. Please Help me
![Anotación 2019-12-12 114817](https://user-images.githubusercontent.com/15082205/70727044-61a47100-1cd5-11ea-9122-dd58edc1535f.jpg)
![Anotación 2019-12-12 114829](https://user-images.githubusercontent.com/15082205/70727048-61a47100-1cd5-11ea-965f-38b3b759fe91.jpg)

**Comment by Yenthe666** [comment]
Please check the logfile under /var/log/odoo. If there is no logfile then run the Odoo instance from the terminal with `./odoo-bin -c /etc/your-odoo-server.conf`
