### ISSUE TITLE
Script hanging when installing on Ubuntu AWS server

### ISSUE THREAD

**Issue by andrewbuttner** [Yenthe666/InstallScript#189]
The script hangs on the following display:
 Running setup.py install for lxml ... -
I have tried all variants of Ubuntu on AWS, but it always hangs at this point.
Works fine on a local Ubuntu install, must be something unique to AWS.
Any suggestions?

**Comment by Yenthe666** [comment]
Do you happen to have very little RAM on these servers @andrewbuttner?

**Comment by andrewbuttner** [comment]
It's got 1GB RAM. Is that too little?

**Comment by Yenthe666** [comment]
Yeah, I've heard the same issue happen to others before. Go for 2GB or more and it'll get through :)
Don't forget that your Linux itself needs 300-700MB for operations, which leaves a very small fraction left for both the Odoo instance and the postgreSQL.
