### ISSUE TITLE
Combine Odoo 8.0 and 9.0 installation script in one version

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/InstallScript#19]
Hi guys,

Let us discuss this if we want to make one script for V8 AND V9 in one or not.
Do you guys see any downsides in it? I honestly think it would be easier to maintain the code and it would probably be easier for the end user too. No more choosing between scripts etc.
We'd just add something along these lines for adding 9.0 support:

```
if [ $OE_VERSION = "9.0" ]; then
  echo -e "\n--- Install Odoo 9 specific required packages"
  sudo apt-get install node-clean-css -y
  sudo apt-get install node-less -y
fi

```

@tvibliani, @sebastian-code I'd love feedback! If you guys are okay with it i'll add it in and make one script for both V8 and V9.

**Comment by sebastian-code** [comment]
Well, as I said before, I do agree. Is going to make the script a little bit more complicated, but it's easier for the final user and for any SysAdmin. I will go with the "Yes, Please!"

**Comment by tvibliani** [comment]
Sure, It should be nice

**Comment by bekee** [comment]
cool

**Comment by Yenthe666** [comment]
A test script is available at https://github.com/Yenthe666/InstallScript/tree/All 
This supports Odoo 8, Odoo 9 community and Odoo 9 enterprise.
