### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by saleemsalameh** [Yenthe666/InstallScript#190]
hello, 
the problem is that RTL does not work using the code for the Daemon.
if you run odoo directly without the daemon the RTL works as expected however, with daemon it does not work.

Please advice.

**Comment by anoureldin** [comment]
> hello,
> the problem is that RTL does not work using the code for the Daemon.
> if you run odoo directly without the daemon the RTL works as expected however, with daemon it does not work.
> 
> Please advice.

Salam bro 
are you able to fix this ?

**Comment by ghost** [comment]
is there any plan to do fixes, the Script is very helpful , but RTLCSS is not working

**Comment by autoparts-tech** [comment]
I am tried a lot to fix it but I can't all Arab user know that yenthe script is the best, but they don't use it because of this bug if you solve it this will be a very good dear

**Comment by Yenthe666** [comment]
Sorry I still haven't had time to figure it out & resolve it

**Comment by saleemsalameh** [comment]
hello, 
i figured that the issue is in the daemon configuration. in the daemon file we have this line:
PATH=/bin:/sbin:/usr/bin
this is the issue, the issue is in the path configured, if you remove the PATH it works or you can add the correct path to include the nodejs.

**Comment by Yenthe666** [comment]
@saleemsalameh could you test with this daemon configuration path instead of the old one?
`PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin`

**Comment by saleemsalameh** [comment]
@Yenthe666 yes it works.
thank you.
