### ISSUE TITLE
Installed using odoo13 script of yours on ubuntu16.04 but odoo13 does not run

### ISSUE THREAD

**Issue by CaptAnil** [Yenthe666/InstallScript#192]
Hi Freind , Good day ,I installed using your script and installation was smooth & showed no error , but I am unable to open in my web browser the setting of master database. No error was seen while installing 
Can you please help , I am a newbie and dont know much . Odoo12 ran with your script without any glitch 

regards
Anil

**Comment by chris001** [comment]
You should first look at `/var/log/odoo-server.log`.  Then, try to execute odoo from the terminal, and see what errors it shows while starting up.  Because it must be a silent fail.

**Comment by Yenthe666** [comment]
Exactly what @chris001 said :) (welcome back Chris! Haven't heard from you in a while)

**Comment by CaptAnil** [comment]
Hello Yenthe & Chris

I can not find the file mentioned but found a syslog
Output as below
No idea where I have issue . I am absolutely new to this so any help is appreciated
Seasons greetings
Kind regards
Anil
May  4 18:05:15 server rsyslogd: [origin software="rsyslogd" swVersion="8.16.0" x-pid="231" x-info="http://www.rsyslog.com"] start
May  4 18:05:15 server rsyslogd-3003: invalid or yet-unknown config file command 'KLogPermitNonKernelFacility' - have you forgotten to load a module? [v8.16$
May  4 18:05:15 server rsyslogd: rsyslogd's groupid changed to 111
May  4 18:05:15 server rsyslogd: rsyslogd's userid changed to 106
May  4 18:05:15 server rsyslogd-2039: Could not open output pipe '/dev/xconsole':: No such file or directory [v8.16.0 try http://www.rsyslog.com/e/2039 ]
May  4 18:05:15 server rsyslogd-2007: action 'action 9' suspended, next retry is Thu May  4 18:05:45 2017 [v8.16.0 try http://www.rsyslog.com/e/2007 ]
May  4 18:05:15 server systemd-sysctl[82]: Couldn't write '1' to 'fs/protected_symlinks', ignoring: No such file or directory
May  4 18:05:15 server systemd-sysctl[82]: Couldn't write '176' to 'kernel/sysrq', ignoring: Permission denied
May  4 18:05:15 server systemd-sysctl[82]: Couldn't write '1' to 'fs/protected_hardlinks', ignoring: No such file or directory
May  4 18:05:15 server systemd-sysctl[82]: Couldn't write '1' to 'kernel/kptr_restrict', ignoring: Permission denied
May  4 18:05:15 server systemd-sysctl[82]: Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: No such file or directory
May  4 18:05:15 server systemd[1]: Started udev Kernel Device Manager.
May  4 18:05:15 server systemd[1]: Starting Flush Journal to Persistent Storage...
May  4 18:05:15 server systemd[1]: Mounted /run/shm.
May  4 18:05:15 server systemd[1]: Reached target Local File Systems.
May  4 18:05:15 server systemd[1]: Starting Tell Plymouth To Write Out Runtime Data...
May  4 18:05:15 server systemd[1]: Starting Raise network interfaces...
May  4 18:05:15 server quota-initial-check.sh[90]:  * Checking quotas...
May  4 18:05:15 server systemd[1]: Started Load/Save Random Seed.
May  4 18:05:15 server quota-initial-check.sh[90]:    ...done.
May  4 18:05:15 server systemd[1]: Started Flush Journal to Persistent Storage.
May  4 18:05:15 server systemd[1]: Started Initial Check File System Quotas.
May  4 18:05:15 server systemd[1]: Started Tell Plymouth To Write Out Runtime Data.
May  4 18:05:15 server systemd[1]: Starting Create Volatile Files and Directories...
May  4 18:05:15 server systemd-tmpfiles[127]: [/usr/lib/tmpfiles.d/var.conf:14] Duplicate line for path "/var/log", ignoring.
May  4 18:05:15 server systemd[1]: Started Create Volatile Files and Directories.
May  4 18:05:15 server systemd[1]: Starting Update UTMP about System Boot/Shutdown...
May  4 18:05:15 server systemd[1]: Reached target System Time Synchronized.
May  4 18:05:15 server systemd[1]: Started Update UTMP about System Boot/Shutdown.
May  4 18:05:15 server systemd[1]: Started Raise network interfaces.
May  4 18:05:15 server systemd[1]: Reached target Network.
May  4 18:05:15 server systemd[1]: Reached target Network is Online.
May  4 18:05:15 server systemd[1]: Started Rebuild Hardware Database.
May  4 18:05:15 server systemd[1]: Starting udev Coldplug all Devices...
May  4 18:05:15 server systemd[1]: Started udev Coldplug all Devices.
May  4 18:05:15 server systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
May  4 18:05:15 server systemd[1]: Reached target Paths.
May  4 18:05:15 server systemd[1]: Reached target System Initialization.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chris001** [comment]
Sorry, the log file to look in for errors is: `/var/log/odoo/odoo-server.log`
( Ref: https://github.com/Yenthe666/InstallScript/blob/13.0/odoo_install.sh#L148 )

**Comment by CaptAnil** [comment]
Thanks Chris
I can not find the file .
So I did another install of Odoo12 and was able to locate the file for Odoo12 . That instance of Odoo12 is successful .
On odoo13 I did the all search & can not locate the log file

I thank you for taking time out to help

Regards
Capt Anil Sharma




Quote
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading state information... Done
(Reading database ... 61698 files and directories currently installed.)
Preparing to unpack wkhtmltox_0.12.5-1.trusty_amd64.deb ...
Unpacking wkhtmltox (1:0.12.5-1.trusty) over (1:0.12.5-1.trusty) ...
Setting up wkhtmltox (1:0.12.5-1.trusty) ...
Processing triggers for man-db (2.7.5-1) ...
ln: failed to create symbolic link '/usr/bin/wkhtmltopdf': File exists
ln: failed to create symbolic link '/usr/bin/wkhtmltoimage': File exists

---- Create ODOO system user ----
Adding user `odoo13' to group `sudo' ...
Adding user odoo13 to group sudo
Done.

---- Create Log directory ----

==== Installing ODOO Server ====
Cloning into '/odoo13/odoo13-server'...
remote: Enumerating objects: 27100, done.
remote: Counting objects: 100% (27100/27100), done.
remote: Compressing objects: 100% (22650/22650), done.
remote: Total 27100 (delta 7901), reused 11654 (delta 3587), pack-reused 0
Receiving objects: 100% (27100/27100), 115.44 MiB | 11.96 MiB/s, done.
Resolving deltas: 100% (7901/7901), done.
Checking connectivity... done.
Checking out files: 100% (24215/24215), done.

---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
* Creating server config file
* Create startup file
* Create init file
* Security Init File
* Start ODOO on Startup
* Starting Odoo Service
Starting odoo13-server: odoo13-server.
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 8069
User service: odoo13
User PostgreSQL: odoo13
Code location: odoo13
Addons folder: odoo13/odoo13-server/addons/
Start Odoo service: sudo service odoo13-server start
Stop Odoo service: sudo service odoo13-server stop
Restart Odoo service: sudo service odoo13-server restart
-----------------------------------------------------------

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yenthe666** [comment]
@CaptAnil run the Odoo from the terminal, it will force the logfile to be generated.
`./odoo-bin -c /etc/odoo13-server.conf`

**Comment by CaptAnil** [comment]
Hi Yenthe
Season’s Greetings
Nothing happens under that command
root@server:~# ./odoo-bin -c /etc/odoo13-server.conf
-bash: ./odoo-bin: No such file or directory
root@server:~# ./odoo13-bin -c /etc/odoo13-server.conf
-bash: ./odoo13-bin: No such file or directory
root@server:~#

I have a feeling that this has to do something with my webhosting as it is 16.04 Ubuntu
In some earlier installation I think there was error of Python as the default version is 3.5 whereas in odoo13 we require 3.6 version
If your script can force install 3.6 may be it will work

I have no issue in installing odoo12 with your script , and that is working perfectly

Just speculating as I have no idea what is happening in background

Regards
Merry Christmas
CaptAnil

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yenthe666** [comment]
@CaptAnil you're clearly not in the right place. First navigate into your Odoo folder (`/odoo13/odoo13-server` equivalent)

**Comment by CaptAnil** [comment]
Thanks Yenthe
/odoo13/odoo13-server# ./odoo-bin -c /etc/odoo13-server.conf
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/odoo13/odoo13-server/odoo/__init__.py", line 19, in <module>
    assert sys.version_info > (3, 6), "Outdated python version detected, Odoo requires Python >= 3.6 to run."
AssertionError: Outdated python version detected, Odoo requires Python >= 3.6 to run.

Regards
@CaptAnil

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yenthe666** [comment]
Hmmm, so you're right. Odoo needs 3.6 or up and by default 3.5 is installed on Ubuntu 16.04. I'd rather not force this though as I have no clue what is installed on the system of the user. I might as well break another system that is running on a server because it needs Python 3.5 for example.

@chris001 you're more of a devops guy than me, what would you propose?

**Comment by chris001** [comment]
You found the error, Odoo 13 requires python 3.6 or higher, this is why Odoo detects your python version 3.5 and stops.
1. Can you upgrade ubuntu from 16.04 to 18.04 ? Because 18.04 comes with python 3.6. Problem solved.
2. If not, try this to install python 3.6 on ubuntu 16.04, you'd end up with 3 python versions on your system, 2.7.x, 3.5, and 3.6, read all the way until the end and do the fix for terminal (re create the symlink): http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/
3. You could run Odoo in its own **"virtualenv"** which is a fully self contained python environment, for any version of python that you want, that doesn't touch the operating system python environment or version.  This would require some modifications to the install script to create and "inception" (enter) into the virtualenv, where it'd install needed python packages, and run the Odoo app code.  I had plans to complete this feature, it's really the preferred way, because it is guaranteed to not disturb or risk breaking any system apps depending on the distro python version and environment (ie mailman, offlineimap, many other python apps) by upgrading dependencies that they might require certain older versions of.

**Comment by CaptAnil** [comment]
Thaust run the Python interpreter of the version you want, with pip as module to execute, like:

python3.6 -m pip install some_package

That way you can be 100% sure the interpreter you launch your scripts with is the same as for which you manage pip packages. No system modifications necessary.

The pip executable is not exactly defined to be any fixed version anyway, whatever updates next would likely override it again. Plus it sometimes breaks for other reasons like version incompatibilities anyway. I'd usually not use it directly at all, except maybe for when you're in a venv (Python virtual environment) where it's exactly defined what it is.
nks , saw something like this on web


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by CaptAnil** [comment]
Hi Chris
Season’s Greeting
I have tried the below , but no success with that upgrade
Somehwhere I saw a possible solution which is based on running the installer with pip from >=3.6
If same can be added in script to call upon , may be it will work

My hosting doesn’t give me ubuntu>=16.04LTS



Just run the Python interpreter of the version you want, with pip as module to execute, like:

python3.6 -m pip install some_package

That way you can be 100% sure the interpreter you launch your scripts with is the same as for which you manage pip packages. No system modifications necessary.
Hope some way it can work
Regards
CaptAnil




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chris001** [comment]
> Hi Chris 
> Season’s Greeting 
> I have tried the below , but no success with that upgrade 
> Somehwhere I saw a possible solution which is based on running the installer with pip from >=3.6 If same can be added in script to call upon , may be it will work 
> My hosting doesn’t give me ubuntu>=16.04LTS 
> Just run the Python interpreter of the version you want, with pip as module to execute, like: 
> python3.6 -m pip install some_package 
> That way you can be 100% sure the interpreter you launch your scripts with is the same as for which you manage pip packages. No system modifications necessary. 
> Hope some way it can work Regards CaptAnil 

1. What host are you using, that doesn't support ubuntu 18.04 LTS ?!
2. In order to run `python3.6 -m pip install some_package`, you first would need to install python3.6, try these steps: 
http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/

**Comment by CaptAnil** [comment]
A2hosting unmanaged VPN
[cid:image003.png@01D5B9E8.4B39D450]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yenthe666** [comment]
Go with a bigger and more known provider such as DigitalOcean, AWS, OVH or another one.
I think I'll go with not implementing a solution for auto-installing & setting the Python version, its too risky. If you use this script you should have basic OS and Odoo knowledge anyways.

**Comment by chris001** [comment]
1. True, DigitalOcean uses KVM virtualization so you can install any OS including ubuntu 18.04 with python 3.6 included with the OS.  A2hosting uses OpenVZ 6 which doesn't have a Ubuntu 18.04 OS template available yet.
2. This is also a solution, use `virtualenv` to get python 3.6 on ubuntu 16.04, so it doesn't interfere with any python apps running on the operating system ie fail2ban, mailman, etc.:
https://vsupalov.com/developing-with-python3-6-on-ubuntu-16-04/

**Comment by CaptAnil** [comment]
Thank you Chris for the solution , I will do the needful and see if I can manage this 😊
I will switch to DigitalOcean later for avoiding such conflicts BUT I do not want to give up on installing Odoo13 in A2hosting .
Merry Christmas Chris & Yenthe

Regards
CaptAnil

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yenthe666** [comment]
Thanks, merry Christmas for you too!
