### ISSUE TITLE
Style Error after installing Odoo V11 at the login page

### ISSUE THREAD

**Issue by tomlou1** [Yenthe666/InstallScript#193]
Hi, I have a fresh installation of odoo V11 and got this error at the login page. Does anyone know how to solve the problem? Thanks

The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

(b'', b'TypeError: sys.print is not a function
    at /usr/lib/nodejs/less/bin/lessc:384:25
    at tree.importVisitor.finish [as _finish] (/usr/lib/nodejs/less/lib/less/parser.js:669:28)
    at tree.importVisitor.run (/usr/lib/nodejs/less/lib/less/import-visitor.js:25:22)
    at Object.parse (/usr/lib/nodejs/less/lib/less/parser.js:675:22)
    at parseLessFile (/usr/lib/nodejs/less/bin/lessc:345:12)
    at Socket. (/usr/lib/nodejs/less/bin/lessc:407:9)
    at Socket.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
')This error occured while compiling the bundle 'web.assets_common' containing:
    - /web/static/lib/bootstrap/less/variables.less
    - /web/static/lib/bootstrap/less/mixins/vendor-prefixes.less
    - /web/static/lib/bootstrap/less/mixins/buttons.less
    - /web/static/lib/bootstrap/less/mixins/clearfix.less
    - /web/static/lib/bootstrap/less/mixins/size.less
    - /web/static/src/less/variables.less
    - /web/static/src/less/utils.less
    - /web_editor/static/src/less/web_editor.variables.less
    - /web/static/lib/bootstrap-datetimepicker/src/less/_bootstrap-datetimepicker.less
    - /web/static/src/less/fonts.less
    - /web/static/src/less/navbar.less
    - /web/static/src/less/mimetypes.less
    - /web/static/src/less/modal.less
    - /web/static/src/less/animation.less
    - /web/static/src/less/rainbow.less
    - /web/static/src/less/datepicker.less
    - /web_planner/static/src/less/web_planner_common.less
    - /web_tour/static/src/less/tip.less
    - /web_tour/static/src/less/keyframes.less

**Comment by tomlou1** [comment]
root@i:/etc/apache2/sites-available# free -m
              total        used        free      shared  buff/cache   available
Mem:           1998         580         116          74        1301        1128
Swap:          4095           7        4088

This is my memory usage. So, this should not be a memory issue as other pointed out before, right?

**Comment by sleeth-slt** [comment]
I solved this issue installing recommended build dependencies from bootstrap

# npm install -g less jshint recess uglify-js
