### ISSUE TITLE
500 Internal Server Error install script odoo 13

### ISSUE THREAD

**Issue by geryescalier** [Yenthe666/InstallScript#199]
I have installed version 13 of odoo but when entering the browser the address http://localhost:8069/ gives me the error: 500 Internal Server Error and does not redirect me to http://localhost:8069/web/database/selector to create the new database when a new odoo installation starts.

The script I have used is the following https://raw.githubusercontent.com/Yenthe666/InstallScript/13.0/odoo_install.sh

I have a 32-bit Debian 10 installed on the PC

I have taken this tutorial as a reference https://www.youtube.com/watch?v=y-ZK6CHCWcY

use command

 ~ $ nmap -p 8069 localhost
PORT      STATE   SERVICE
8069/tcp  open      unknown

**Comment by Yenthe666** [comment]
What does the logfile mention? :)

**Comment by Yenthe666** [comment]
Closing as no feedback. Its built for Ubuntu-xx anyways not specifically for Debian.
