### ISSUE TITLE
Unable to get Odoo to start after installing (FYI: example resolution process)

### ISSUE THREAD

**Issue by ray-odoo** [Yenthe666/InstallScript#200]
I was asked to troubleshoot a fresh install and am leaving my steps documented here.

**Comment by ray-odoo** [comment]
First, check if there is a log file in /var/log/odoo

If there is, look and check for errors and/or warnings

**Comment by ray-odoo** [comment]
In this case there were none, so I checked if the Odoo service is running:

`ps aux | grep odoo`

**odoo       1384  0.0  0.1 375968 79256 ?        Sl   15:56   0:01 python3 /odoo/odoo-server/odoo-bin -c /etc/odoo-server.conf**

This shows one process running.  If you see more than one, that's probably a concern.

**Comment by ray-odoo** [comment]
So - turns out the issue was the firewall was blocking port 8069.

**Comment by Yenthe666** [comment]
@ray-odoo thanks for logging it here, always happy to see the guys from Odoo using it somewhere :)
So I can conclude there was no issue and that it was a deployment issue in the firewall?

**Comment by ray-odoo** [comment]
Correct.  Was going to keep this open and comment from time to time any other common issues that might help others.

**Comment by Yenthe666** [comment]
Yeah that's great! Since there's no issue in the script itself and it was the firewall I guess we can just close it off? Perhaps I should add a debugging chapter to the Readme though.
