### ISSUE TITLE
how to make server http to https ssl with this script (odoo_install.sh)

### ISSUE THREAD

**Issue by shaneebkhan** [Yenthe666/InstallScript#202]
i installed with your script but cant make it as secure connection using ssl 
please guide me for https connection instead of http connection for hosting

**Comment by CaptAnil** [comment]
Thanks Yenthe , I installed using the latest script just now . The install for odoo13 is great and happened without any glitch . NginX started and Odoo is running on http . It does not install certbot or service on https ? Is the https support not included in this script ? Regards

**Comment by Yenthe666** [comment]
@shaneebkhan @CaptAnil no sorry there is no auto-script for SSL/HTTPS yet. The final steps are up to you to do yourself. Its on the wishlist so maybe one day if I have enough time :)

**Comment by chris001** [comment]
FYI My version of this install script, from 2018, already automatically installed `https` certificate.

**Comment by Yenthe666** [comment]
@chris001 yeah I basically lack time to migrate, test it etc. I'm on too many cool projects hah.
