### ISSUE TITLE
You have to add  \ because the script read the $remote_addr as variable

### ISSUE THREAD

**Issue by mojahed4e** [Yenthe666/InstallScript#203]
https://github.com/Yenthe666/InstallScript/blob/775ee313fa197059e9cd3a87e5d3ab2718577294/odoo_install.sh#L280

Please just add a backslash to avoid the error in nginx
Ubuntu 18.04 LTS image on gcloud.

Regards,

**Comment by Yenthe666** [comment]
Good catch, this should fix it https://github.com/Yenthe666/InstallScript/commit/e5e7fba5b392e194c2a61758810646e467da8110
