### ISSUE TITLE
Odoo Service not starting after installation on Ubuntu 18.4

### ISSUE THREAD

**Issue by rexefe** [Yenthe666/InstallScript#207]
**Note: there was no log file so I had to create a new log file**

**Odoo Status**
rexefe@ThinkMagine:/odoo/odoo-server$ sudo service odoo-server status
● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; generated)
   Active: active (exited) since Sun 2020-02-23 00:41:29 GMT; 13min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 12183 ExecStop=/etc/init.d/odoo-server stop (code=exited, status=0/SU
  Process: 12247 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/

Feb 23 00:41:29 ThinkMagine systemd[1]: Starting LSB: Enterprise Business Applic
Feb 23 00:41:29 ThinkMagine odoo-server[12247]: Starting odoo-server: odoo-serve
Feb 23 00:41:29 ThinkMagine systemd[1]: Started LSB: Enterprise Business Applica

**Comment by Yenthe666** [comment]
@rexefe and what is logged in the logfile if you manually start the instance?

**Comment by rexefe** [comment]
Nothing

**Comment by Yenthe666** [comment]
Well there's nothing I can do if I don't have error logs or reproducable steps 😉 
So you where able to start the Odoo manually, there are no errors and it is accessible?

**Comment by rexefe** [comment]
That's the strange thing, 
the application doesn't load when I access it via HTTP on my localhost

**Comment by rexefe** [comment]
I'm thinking of restarting the process, but I'm a novice when it comes to installing process/modules in ubuntu

**Comment by Yenthe666** [comment]
Hmm can you just do a reboot of your server and then check if its up automatically? If not, does it work if you start it manually after the reboot?

**Comment by rexefe** [comment]
Nope

**Comment by rexefe** [comment]
rexefe@ThinkMagine:~$ sudo /etc/init.d/odoo-server force-reload
Restarting odoo-server: start-stop-daemon: warning: failed to kill 14786: No such process
odoo-server.

**Comment by Yenthe666** [comment]
What happens if you run it manually?
`sudo su odoo`
`./odoo-bin -c /etc/odoo-server.conf`

**Comment by rexefe** [comment]
it says : This account is currently not available.
(Strange :( )

**Comment by rexefe** [comment]
The first time I tried to install Odoo Manually(without the script), i rememebered typing in that command and it worked, but my installation process was not succesufl, so i had to use your script.

**Comment by Yenthe666** [comment]
Euhh that's a really odd one. I think you're having some Linux issues with already existing users or something. Try it on a clean VM or by using names/variables you're sure of that they're not yet in use (along with the port).

**Comment by captainjapeng** [comment]
> What happens if you run it manually?
> `sudo su odoo`
> `./odoo-bin -c /etc/odoo-server.conf`

Here's the output
![image](https://user-images.githubusercontent.com/26142675/75677340-358e0000-5cc6-11ea-9b2a-9206851fc97f.png)

**Comment by Yenthe666** [comment]
Hmm looks like some missing dependencies. Can you check if all dependencies from `requirements.txt` are correctly installed on your Linux?

**Comment by captainjapeng** [comment]
Yeah, that was the solution, I've runned `pip3 install -r requirements.txt` on odoo-server directory and it worked fine after

**Comment by rexefe** [comment]
odoo service is running

but seems i am not getting a response from the server i checked
rexefe@ThinkMagine:/odoo/odoo-server$ curl localhost:8069
curl: (7) Failed to connect to localhost port 8069: Connection refused

**Comment by captainjapeng** [comment]
It means that the server is has not started, please make sure you can run the ff code without any errors:

> What happens if you run it manually?
> `sudo su odoo`
> `./odoo-bin -c /etc/odoo-server.conf`

**Comment by rexefe** [comment]
@captainjapeng  
i get this reponse

rexefe@ThinkMagine:/odoo/odoo-server$ sudo su odoo
This account is currently not available.
