### ISSUE TITLE
Instance works perfectly well with ./odoo-bin but not with odoo-server service

### ISSUE THREAD

**Issue by kasback** [Yenthe666/InstallScript#214]
Hello and thanks for the really helpfull script, im facing a bit of a hard time trying to start the odoo-server service.
he'res my :
`$ sudo service --status-all`
and here's my `./odoo-bin -c /etc/odoo-server.conf
The server works perfectly well with the `./odoo-bin `command but not with the `sudo service odoo-service start`.

**Comment by kasback** [comment]
I managed to make it work after some tries, i had to start it with this command `sudo systemctl start odoo-server` instead of `sudo service odoo-server start`. it's odd but it worked so..

**Comment by Yenthe666** [comment]
After a reboot both will probably work fine too :)
