### ISSUE TITLE
Is odoo 13 stable version ?

### ISSUE THREAD

**Issue by composercodes** [Yenthe666/InstallScript#219]
Hi 
Thanks for your great script
But please I want to ask you if odoo 13 is stable version, or you would prefer use odoo 12 
What do you think please 
Or wait for 14 
Thanks,

**Comment by Yenthe666** [comment]
Hi,

I've already replied on your ticket at github.com/odoo/odoo and honestly you shouldn't post this question on random repositories ;-)
Yeah it is stable, it is fast and I have it reliable running (in production) at three customers already.
