### ISSUE TITLE
[V9 Enterprise] assets broken when doing -u all

### ISSUE THREAD

**Issue by Yenthe666** [Yenthe666/InstallScript#22]
When a user has a V9 Enterprise and does a `git update` and/or update of the modules with `-u all` the assets will be broken.
The whole Odoo screen will be broken and nothing will be shown except dozens of errors about the assets not being abled to load etc.

This happens because Ubuntu doesn't know which NodeJS to take. A nice explanation is here: http://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory

A possible fix:

```
ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by Yenthe666** [comment]
First fix attempt at https://github.com/Yenthe666/InstallScript/commit/e04b0e1e0a5f7194eefcc029bc6ffad2e1f8a12a
This removes the majory of the issues. Now remaining with:
<img src="http://i.imgur.com/scB91Jd.png" alt="bundle issues"/>

**Comment by Yenthe666** [comment]
@sebastian-code and @tvibliani do you guys have acces to the Enterprise version and do you guys run in to this problem? I've managed to fix a good part but there are still a few bundle issues.
Wondering if you guys know out of your head what might be wrong.

**Comment by sebastian-code** [comment]
No @Yenthe666, sorry, I have no access to that component. I'm not even using actively that version. Sorry

**Comment by tvibliani** [comment]
neither have I

**Comment by Yenthe666** [comment]
This problem has been fixed in the meanwhile. The issue was (then at the time) at Odoo itself.
