### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mm82299** [Yenthe666/InstallScript#221]
Hello,
I got this error message when installing Odoo 10 (I have already an instance of Odoo installed and i'm using Ubuntu 18.04):
Preparing to unpack wkhtmltox_0.12.5-1.trusty_amd64.deb ...
Unpacking wkhtmltox (1:0.12.5-1.trusty) over (1:0.12.5-1.trusty) ...
Setting up wkhtmltox (1:0.12.5-1.trusty) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
ln: failed to create symbolic link '/usr/bin/wkhtmltopdf': File exists
ln: failed to create symbolic link '/usr/bin/wkhtmltoimage': File exists

**Comment by Yenthe666** [comment]
@mm82299 that is normal. You already had `wkhtmltopdf` and `wkhtmltoimage` installed. Because you didn't set `INSTALL_WKHTMLTOPDF=False` the script tried to install it (again):
https://github.com/Yenthe666/InstallScript/blob/e2693d5d5c20edca213eb4686e362e4eb14b10c3/odoo_install.sh#L22

**Comment by mm82299** [comment]
Hello,

I have followup the recommendation but i got tan error message, bellow is the log file fyi.

---- Update Server ----
'universe' distribution component is already enabled for all sources.
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:3 http://deb.anydesk.com all InRelease                                     
Hit:4 http://download.virtualbox.org/virtualbox/debian bionic InRelease        
Hit:5 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:7 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:8 https://repo.skype.com/deb stable InRelease                              
Hit:10 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease          
Hit:12 http://repo.fortinet.com/repo/ubuntu bionic InRelease                   
Hit:11 http://mirrors.edge.kernel.org/ubuntu xenial InRelease           
Reading package lists... Done                            
N: Skipping acquire of configured file 'contrib/binary-i386/Packages' as repository 'http://download.virtualbox.org/virtualbox/debian bionic InRelease' doesn't support architecture 'i386'
W: Conflicting distribution: http://repo.fortinet.com/repo/ubuntu bionic InRelease (expected bionic but got )
Hit:1 http://download.virtualbox.org/virtualbox/debian bionic InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu bionic InRelease                     
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:4 http://deb.anydesk.com all InRelease                                     
Hit:5 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease             
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:7 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease           
Hit:8 https://repo.skype.com/deb stable InRelease                              
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Hit:10 http://repo.fortinet.com/repo/ubuntu bionic InRelease                   
Hit:11 http://mirrors.edge.kernel.org/ubuntu xenial InRelease              
Reading package lists... Done                      
N: Skipping acquire of configured file 'contrib/binary-i386/Packages' as repository 'http://download.virtualbox.org/virtualbox/debian bionic InRelease' doesn't support architecture 'i386'
W: Conflicting distribution: http://repo.fortinet.com/repo/ubuntu bionic InRelease (expected bionic but got )
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libqt5opengl5 libqt5printsupport5 libqt5x11extras5 libsdl-ttf2.0-0
  libsdl1.2debian
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  linux-generic-hwe-18.04 linux-headers-generic-hwe-18.04
  linux-image-generic-hwe-18.04
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

---- Install PostgreSQL Server ----
Reading package lists... Done
Building dependency tree       
Reading state information... Done
postgresql is already the newest version (10+190ubuntu0.1).
postgresql-server-dev-all is already the newest version (190ubuntu0.1).
The following packages were automatically installed and are no longer required:
  libqt5opengl5 libqt5printsupport5 libqt5x11extras5 libsdl-ttf2.0-0
  libsdl1.2debian
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

---- Creating the ODOO PostgreSQL User  ----

--- Installing Python 3 + pip3 --
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
build-essential is already the newest version (12.4ubuntu1).
python3-setuptools is already the newest version (39.0.1-2).
gdebi is already the newest version (0.9.5.7+nmu2).
libzip-dev is already the newest version (1.1.2-1.1).
node-less is already the newest version (1.6.3~dfsg-2).
python3-wheel is already the newest version (0.30.0-0.2).
git is already the newest version (1:2.17.1-1ubuntu0.5).
libldap2-dev is already the newest version (2.4.45+dfsg-1ubuntu1.4).
libsasl2-dev is already the newest version (2.1.27~101-g0780600+dfsg-3ubuntu2.1).
libxslt1-dev is already the newest version (1.1.29-5ubuntu0.2).
python3 is already the newest version (3.6.7-1~18.04).
python3-dev is already the newest version (3.6.7-1~18.04).
wget is already the newest version (1.19.4-1ubuntu2.2).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
python3-venv is already the newest version (3.6.7-1~18.04).
libpng12-0 is already the newest version (1.2.54-1ubuntu1).
The following packages were automatically installed and are no longer required:
  libqt5opengl5 libqt5printsupport5 libqt5x11extras5 libsdl-ttf2.0-0
  libsdl1.2debian
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

---- Install python packages/requirements ----
The directory '/home/mourad/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/mourad/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: Babel==2.3.4 in /usr/local/lib/python3.6/dist-packages (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 1))
Requirement already satisfied: decorator==4.0.10 in /usr/local/lib/python3.6/dist-packages (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 2))
Requirement already satisfied: docutils==0.12 in /usr/local/lib/python3.6/dist-packages (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 3))
Collecting ebaysdk==2.1.4 (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/88/3f/400677f116068aa52e9766a70281421f6b99242304e7374d09b930da7cb0/ebaysdk-2.1.4.tar.gz (40kB)
    100% |████████████████████████████████| 51kB 348kB/s 
Requirement already satisfied: feedparser==5.2.1 in /usr/local/lib/python3.6/dist-packages (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 5))
Requirement already satisfied: gevent==1.1.2 in /usr/local/lib/python3.6/dist-packages (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 6))
Requirement already satisfied: greenlet==0.4.10 in /usr/local/lib/python3.6/dist-packages (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 7))
Collecting jcconv==0.2.3 (from -r https://github.com/odoo/odoo/raw/10.0/requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/dd/5b/55d6dd385e8584c6750864ddec8d5ff82a295b37ac68344febc9e923bf99/jcconv-0.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5l6z_8g3/jcconv/setup.py", line 17
        print "unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5l6z_8g3/jcconv/

---- Installing nodeJS NPM and rtlcss for LTR support ----
Reading package lists... Done
Building dependency tree       
Reading state information... Done
npm is already the newest version (3.5.2-0ubuntu4).
nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
The following packages were automatically installed and are no longer required:
  libqt5opengl5 libqt5printsupport5 libqt5x11extras5 libsdl-ttf2.0-0
  libsdl1.2debian
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/usr/local/bin/rtlcss -> /usr/local/lib/node_modules/rtlcss/bin/rtlcss.js
/usr/local/lib
└── rtlcss@2.5.0 

Wkhtmltopdf isn't installed due to the choice of the user!

---- Create ODOO system user ----
Adding user `odoo000' to group `sudo' ...
Adding user odoo000 to group sudo
Done.

---- Create Log directory ----

==== Installing ODOO Server ====
Cloning into '/odoo000/odoo000-server'...
warning: redirecting to https://github.com/odoo/odoo.git/
remote: Enumerating objects: 24248, done.
remote: Counting objects: 100% (24248/24248), done.
remote: Compressing objects: 100% (18612/18612), done.
remote: Total 24248 (delta 7694), reused 11686 (delta 4882), pack-reused 0
Receiving objects: 100% (24248/24248), 117.50 MiB | 345.00 KiB/s, done.
Resolving deltas: 100% (7694/7694), done.
Checking out files: 100% (22035/22035), done.

---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
* Creating server config file
* Create startup file
* Create init file
* Security Init File
* Start ODOO on Startup
* Starting Odoo Service
Starting odoo000-server: odoo000-server.
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 9069
User service: odoo000
User PostgreSQL: odoo000
Code location: odoo000
Addons folder: odoo000/odoo000-server/addons/
Start Odoo service: sudo service odoo000-server start
Stop Odoo service: sudo service odoo000-server stop
Restart Odoo service: sudo service odoo000-server restart
-----------------------------------------------------------


please help.

Thanks,
Mourad
![Error](https://user-images.githubusercontent.com/44939338/78012890-951b1200-733d-11ea-99a9-56f4484bc148.png)

**Comment by Yenthe666** [comment]
1. You have issues with your pip packages
2. You reran this script again with I believe the same parameters, you shouldn't
3. Why such an odd name "odoo000"

**Comment by mm82299** [comment]
Hello,
I have changed the parameters and rerun the script but got this error:
python setup.py egg_info failed with error code 1 in /tmp/pip-build-l_tn8xbu/jcconv
Any idea?

**Comment by Yenthe666** [comment]
Totally out of scope of the script as you're having issues with your pip and setup packages. Google around about these subjects because there are a lot of help questions about this ;)

**Comment by mm82299** [comment]
Hello,
I have tried to install Odoo11 with the same script and it's worked, it seem that the problem is with Odoo10, how i can fix this issue ?
Thanks,
Mourad

**Comment by mm82299** [comment]
Hello,
I have tried to run the script on a new vps (with no instance of Odoo installed) but still got the same issue, it seem an issue with the version of Odoo10, would you please confirm ?

**Comment by mm82299** [comment]
Hello,
Is this because Odoo 10 is unsupported now as python 2.7 is dead

**Comment by Yenthe666** [comment]
Nope, you can still install Odoo 10 with python 2.7. I'm not sure what you do wrong but I can assure you the script still works, I used it lately.

**Comment by mm82299** [comment]
Hello,
Can i give you access to my server to check?
I will appreciate your help on that.
Cdt,
Mourad

**Comment by Yenthe666** [comment]
Sorry but I had to stop helping with these kind of questions because I literally get dozens a week and they take up too much time.  Take a new VM, start clean and give it good/clear names. then paste the error if there is still any

**Comment by mm82299** [comment]
The problem is not showing any error message, also i have tried to check the log file under /var/log/odoo/ but no file is there :-(

**Comment by mm82299** [comment]
I did the installation on a fresh copy

**Comment by Yenthe666** [comment]
Run it from the command, that forces a logfile creation.

**Comment by mm82299** [comment]
I did, i run the script from the command:
sudo chmod +x odoo_install.sh
 sudo ./odoo_install.sh

**Comment by Yenthe666** [comment]
No, that is the installation script. Run the odoo instance from the command.
`./odoo-bin -c /etc/your-odoo-server.conf`

**Comment by mm82299** [comment]
I got this message when i run ./odoo-bin -c
root@vps812041:~# ./odoo-bin -c
-bash: ./odoo-bin: No such file or directory
I can access the conf file and it contain that informations:
[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
addons_path = /usr/lib/python2.7/dist-packages/odoo/addons
[options]
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/odoo-server/addons,/odoo/custom/addons
xmlrpc_port = 8069

**Comment by mm82299** [comment]
See this, run odoo under /odoo/odoo-server:
root@vps812041:/odoo/odoo-server# ./odoo-bin
Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    __import__('pkg_resources').declare_namespace('odoo.addons')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2160, in declare_namespace
    declare_namespace(parent)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2176, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2111, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python2.7/pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/odoo/odoo-server/odoo/__init__.py", line 60, in <module>
    import modules
  File "/odoo/odoo-server/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/odoo/odoo-server/odoo/modules/graph.py", line 13, in <module>
    import odoo.osv as osv
  File "/odoo/odoo-server/odoo/osv/__init__.py", line 4, in <module>
    import osv
  File "/odoo/odoo-server/odoo/osv/osv.py", line 4, in <module>
    from ..exceptions import except_orm
  File "/odoo/odoo-server/odoo/exceptions.py", line 15, in <module>
    from tools.func import frame_codeinfo
  File "/odoo/odoo-server/odoo/tools/__init__.py", line 8, in <module>
    from misc import *
  File "/odoo/odoo-server/odoo/tools/misc.py", line 16, in <module>
    import passlib.utils
ImportError: No module named passlib.utils

**Comment by Yenthe666** [comment]
Don't just run `./odoo-bin`, provide the config file.. as I explained.
