### ISSUE TITLE
Odoo 13 new release 

### ISSUE THREAD

**Issue by composercodes** [Yenthe666/InstallScript#222]
I'm sorry for this question
Please odoo 13 has new release odoo 13.2
How to know all new relases from where  in future ?
How to upgrade to new release ?
How to know modules files releases ?
Thanks,

**Comment by KennyDizi** [comment]
Interesting in

**Comment by Yenthe666** [comment]
@composercodes:

I think you don't know something very important about Odoo. You should never install a subversion of Odoo (as 13.2). This is a SaaS release for their own Odoo hosting server/service and shouldn't not be used by customers. Odoo does not provide upgrade scripts for them and you're basically stuck in an inbetween version if you do not handle everything yourself.

The simple answer is: don't. Unless you REALLY know what you're doing and REALLY need something from this new subversion.

> How to know all new relases from where in future ?
You don't, it is not publicly announced for the Odoo SaaS versions. Only major versions are released (always september 30 - 2 october of a year).


> How to upgrade to new release ?
Don't. These are minor versions and there are no upgrade scripts for them. Only Odoo can (and should) do this.

> How to know modules files releases ?
Look at all the apps in every new release.
