### ISSUE TITLE
Odoo Connection lost with nginx

### ISSUE THREAD

**Issue by alzubairy** [Yenthe666/InstallScript#223]
Odoo looses the connection repeatedly, and when I turn off the Nginx, it works without any problem.
I went to the errors file and found the following:

2020/04/05 13:50:00 [error] 18985#18985: *93 connect() failed (111: Connection refused) while connecting to upstream, client: 205.160.111.102, server: erp.my.com, request: "POST /longpolling/poll HTTP/1.1", upstream: "http://127.0.0.1:8072/longpolling/poll", host: "178.62.218.104", referrer: "http://178.62.218.104/web"

2020/04/05 13:52:31 [error] 926#926: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 205.160.111.230, server: erp.my.com, request: "POST /longpolling/poll HTTP/1.1", upstream: "http://127.0.0.1:8072/longpolling/poll", host: "178.62.218.104", referrer: "http://178.62.218.104/web"

Please Help

**Comment by tarbib** [comment]
@alzubairy is it losing connection while browsing articles in form view for example ? (this is the issue I have)

**Comment by tonybenoy** [comment]
@alzubairy @tarbib have you guys tried increasing the workers in odoo config?

**Comment by tarbib** [comment]
@tonybenoy 
Is it somewhere in this file? /etc/odoo-server.conf
I only have this :
`
[options]
; This is the password that allows database operations:
admin_passwd = 0bQ4kv5uppuu1dT8
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/odoo-server/addons,/odoo/custom/addons
proxy_mode = True
`

**Comment by tarbib** [comment]
Is it somewhere in this file? etc/odoo-server.conf 
I only have this inside :
```
[options]
; This is the password that allows database operations:
admin_passwd = XXXXXXXXXXX
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/odoo-server/addons,/odoo/custom/addons
proxy_mode = True
```

**Comment by tonybenoy** [comment]
@tarbib https://www.odoo.com/documentation/13.0/setup/deploy.html#worker-number-calculation

**Comment by tarbib** [comment]
@tonybenoy that was it! thank you very much :+1:

**Comment by Yenthe666** [comment]
Thanks for the help @tonybenoy ;)

**Comment by alzubairy** [comment]
I'll try it.
Thanks @tonybenoy

**Comment by tonybenoy** [comment]
@Yenthe666 I think by default it should have workers=2 just so that longpolling works out of the box. And probably have an option to tweak that

**Comment by Yenthe666** [comment]
Mhmm but then only when Nginx is set on and let's stay away of even more configurable variables honestly. There are already a lot in the script

**Comment by tarbib** [comment]
@Yenthe666 Maybe it could be mentioned, in the readme there :
 INSTALL_NGINX is set to False by default. Set this to True if you want to install Nginx. _If True, you should consider setting workers in the Odoo config at etc/odoo-server.conf (add a line "workers = 2")_

**Comment by Yenthe666** [comment]
Added in a little note at https://github.com/Yenthe666/InstallScript/commit/cbe53879f379be35be16e3110bc177e83b99f507
