### ISSUE TITLE
Script seems to need to install Postgresql 12

### ISSUE THREAD

**Issue by Rtax** [Yenthe666/InstallScript#224]
I ran the script multiple times, fixing the odd permissions issue etc on Ubuntu 18.04 and it worked great. The only issue is Odoo would not run until I installed Postgres 12 from the postgres repository.

The issue I got in the Odoo logs was similar to: psycopg2.OperationalError: could not connect to server

**Comment by Yenthe666** [comment]
Well, what do you expect from me or what are you suggesting?
There's no steps, no logs, no output and no commands..
