### ISSUE TITLE
custom modules folder - permissions

### ISSUE THREAD

**Issue by cierek** [Yenthe666/InstallScript#226]
Hello,
Maybe it is good to update script with
sudo chmod -R 777 custom 
for custom modules folder so final users can upload modules straight after installation?

**Comment by Yenthe666** [comment]
doing a blind chmod with `777` rights is a VERY bad idea in the first place :) This means you're basically trusting every process/command done in that directory.
The user that is created for Odoo has rights to all the folders in the first place anyways.
