### ISSUE TITLE
Install script gets stuck on lxml installation

### ISSUE THREAD

**Issue by ossimantylahti** [Yenthe666/InstallScript#227]
Hi

Tried the installation for version 13.0 CE today on Amazon AWS EC2 Ubuntu 18.04 LTS instance and the script gets stuck on:

`---- Install python packages/requirements ----
...
  Downloading https://files.pythonhosted.org/packages/6b/57/5d1ee250a9c4e780d57d7dcc1b9553c4e386c759ed3087f813965c4534d2/python_stdnum-1.13-py2.py3-none-any.whl (839kB)
    100% |████████████████████████████████| 849kB 1.7MB/s
Installing collected packages: lxml, requests, ebaysdk, feedparser, greenlet, gevent, html2text, MarkupSafe, Jinja2, libsass, Mako, num2words, ofxparse, passlib, Pillow, polib, psutil, psycopg2, pydot, python-ldap, PyPDF2, python-dateutil, pyusb, qrcode, reportlab, isodate, appdirs, defusedxml, cached-property, zeep, python-stdnum, vatnumber, vobject, Werkzeug, XlsxWriter, xlwt, xlrd
  Found existing installation: lxml 4.2.1
    Not uninstalling lxml at /usr/lib/python3/dist-packages, outside environment /usr`
`  Running setup.py install for lxml ... -`

100% reproducible. Happens every time.

I tried installing manually lxml before executing the script. No help. Pressing Control-C aborts lxml installation but the script proceeds to the end.

**Comment by Yenthe666** [comment]
How much RAM & CPU's does your server have?

**Comment by ossimantylahti** [comment]
1 gigs of ram, 1 core. It is an amazon t2.micro instance.

Digging a bit deeper I found out that manually trying to start ./odoo-bin fails with several missing Python depencencies. And most serious of them seems to be Werkzeug. Odoo 13 apparently requires exactly correct Werkzeug version.

With following commands I at least can get the Odoo server to start. (But it still won't accept HTTP connections).

```
sudo pip3 install PyPDF2
sudo pip3 install passlib
sudo pip3 install werkzeug
sudo pip3 install polib
sudo pip3 install PIL
sudo pip3 install python-PIL
sudo pip3 install pil
sudo pip3 install Pillow
sudo pip3 install psycopg2
sudo pip3 install dateutil
sudo pip3 install python3-dateutil
sudo pip3 install python-dateutil
sudo pip3 install werkzeug.contrib
sudo pip3 uninstall Werkzeug
sudo pip3 install Werkzeug==0.14.1
sudo pip3 install psutil
sudo pip3 install reportlab
sudo pip3 install html2text
sudo pip3 install num2words
```

**Comment by Yenthe666** [comment]
Yeah surely multiple will fail once lxml fails. I've had reports about this before but in all honesty.. 1GB of RAM is not enough. Set it to 2GB and you'll see it'll work fine ;)

**Comment by ossimantylahti** [comment]
Confirmed. Lack of memory was the problem. When tried with Amazon AWS EC2 Small type instance, the installation script works fine. The installation takes a long time at "_Running setup.py install for lxml ... -_", but after waiting for five minutes, it proceeds. Fortunately there is a progress indicator (it started whirling after some two minutes).

**Comment by Yenthe666** [comment]
Yeah, sadly this seems to be the case on AWS. AWS EC seems to use a little bit more resources on their instances then others. Odoo installs on DigitalOcean its 1GB RAM servers but not on AWS. 
Either way, running on <= 1GB of RAM shouldn't be recommended anyways. One spike in traffic/load might get your server overloaded.
