### ISSUE TITLE
odoo 11 not woark

### ISSUE THREAD

**Issue by elkady1337** [Yenthe666/InstallScript#228]
odoo 11 not work

everything install good  but not working

---- Setting permissions on home folder ----
* Create server config file
* Creating server config file
* Create startup file
* Create init file
* Security Init File
* Start ODOO on Startup
* Starting Odoo Service
Starting odoo-server: odoo-server.
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 8069
User service: odoo
User PostgreSQL: odoo
Code location: odoo
Addons folder: odoo/odoo-server/addons/
Start Odoo service: sudo service odoo-server start
Stop Odoo service: sudo service odoo-server stop
Restart Odoo service: sudo service odoo-server restart

**Comment by chris001** [comment]
You need to run odoo server from command line, and then post back the errors in your log file.  Search this repo for those keywords to find the exact commands to run from command line to do this.

**Comment by Yenthe666** [comment]
Exactly :)
`./odoo-bin -c /etc/your_odoo.conf`

**Comment by kmrul** [comment]
Python package version has problem:
Werkzeug==0.11.15
Replace
werkzeug==0.16.0

**Comment by Yenthe666** [comment]
Sadly this is the default packaging in Odoo. See:
https://github.com/odoo/odoo/blob/b3bc1c74536d6f9f96af20aa2a8148d33b94d6e5/requirements.txt#L44

You could report it here though: https://github.com/odoo/odoo/issues
