### ISSUE TITLE
Log file doesn't exist

### ISSUE THREAD

**Issue by mm82299** [Yenthe666/InstallScript#229]
I have installed Odoo13 on ubuntu 16.04 but when i lunched i doesn't work (problem loading page), i tried to check the log but it doesn't exist (No such file or directory), how i can force the script to generate the Log file

**Comment by Yenthe666** [comment]
Hi,

Just like about 50 other completely similar issues.. Run the Odoo instance from the terminal (`./odoo-bin -c /etc/your-odoo.conf`) and then check the log.
