### ISSUE TITLE
Unable to use the install script for Ubuntu 20

### ISSUE THREAD

**Issue by ralph-ng** [Yenthe666/InstallScript#232]
These are the error I received:

> Building wheel for Pillow (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vmtl4vvf/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vmtl4vvf/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tuj5xa8y
>        cwd: /tmp/pip-install-vmtl4vvf/Pillow/
>

**Comment by TimarTimar** [comment]
I recived error while installing psycopg2

**Comment by Yenthe666** [comment]
This one probably resolved it: https://github.com/Yenthe666/InstallScript/commit/1b88837c6886514edd315a053f2e30931d8189d6
