### ISSUE TITLE
script issue 

### ISSUE THREAD

**Issue by saberabdelhady** [Yenthe666/InstallScript#236]
Dear 
i install your script but i face some issue like that 
![image](https://user-images.githubusercontent.com/39088480/81441547-3e8dc880-9172-11ea-86b4-5e0a4248f9db.png)

i edit this and run from root 
![image](https://user-images.githubusercontent.com/39088480/81441726-90365300-9172-11ea-8fa9-805ed70254bb.png)

can u help me please i install on Ubuntu 18.04 on azure 

![image](https://user-images.githubusercontent.com/39088480/81458892-3c8d2f00-919d-11ea-9082-da18029e720e.png)

**Comment by Yenthe666** [comment]
Why didn't you set a `website_name`? Either way, please paste the output from the logfile under /var/log/odoo

**Comment by saberabdelhady** [comment]
![image](https://user-images.githubusercontent.com/39088480/81458892-3c8d2f00-919d-11ea-9082-da18029e720e.png)
@Yenthe666

**Comment by Yenthe666** [comment]
Odd, it looks like it has no rights to the assets. Have you checked your rights for the folders?

**Comment by saberabdelhady** [comment]
i used root user

**Comment by Yenthe666** [comment]
Sure but does your Odoo user have rights on all the folders to run Odoo? Including all the assets?

**Comment by saberabdelhady** [comment]
I have installed the scripts with a different port and it works normally.( first 8068  second work normal 8069 but i allowed two port on azure )
If i install the first time, a problem occurs , if i install second it work normal

**Comment by Yenthe666** [comment]
"if I install the first time, a problem occurs", what does that mean? What does the log say?
