### ISSUE TITLE
odoo.conf update (plz help me)?

### ISSUE THREAD

**Issue by saberabdelhady** [Yenthe666/InstallScript#237]
Dear Expert 
can you help me in update this odoo.conf with the new specs hardware ( ram 49 gb cpu core 12 )
i use machine in azure 

in /etc/odoo.conf:

[options]
limit_memory_hard = 1677721600
limit_memory_soft = 629145600
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
workers = 25

**Comment by Yenthe666** [comment]
Hi,

See https://www.odoo.com/documentation/13.0/setup/deploy.html#id5 for examples on how to calculate it :)
