### ISSUE TITLE
Ent. installation with Two Factor Auth. 

### ISSUE THREAD

**Issue by husam-esco** [Yenthe666/InstallScript#239]
just need to add simple note here 
if you have applied two factor Auth. feature in your Git Account you should disable it before you proceed with this script to all you pass this blocking 

Thanks
Husam

**Comment by Yenthe666** [comment]
@AlBakree actually, you don't really have to. You can set one of your keys as a password and it'll pass it along just fine :)

**Comment by husam-esco** [comment]
thanks dear
but i had a few failed tries , so when i disabled the two factor Auth. it worked fine
thats why i shared it

**Comment by Yenthe666** [comment]
Check this out as an alternative, I've tested it before: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
