### ISSUE TITLE
Multiple Version and VirtualEnv

### ISSUE THREAD

**Issue by jonatasartur** [Yenthe666/InstallScript#241]
Has anyone tried to use this script to install different versions on the same server?
And someone tried to use this script with venv?

**Comment by chris001** [comment]
I tried it, some time ago.  Odoo should work just fine in a `venv`.  The script needs small adjustments if you wish for the script to be aware of `venv` and handle installing into the different `venv`.

**Comment by Yenthe666** [comment]
It can easily handle multiple installations on one server :) There's no venv logic right now but as @chris001 said it could be modified.
