### ISSUE TITLE
Option for remote postgresql

### ISSUE THREAD

**Issue by imunisasi** [Yenthe666/InstallScript#244]
this installscript forced user to use 1 instance
how if we want to use 2 instance ( 1 app and 1 db )

thanks

**Comment by chris001** [comment]
Try reading these answers to the same question on odoo forum.  This is one of many identical questions answered on the odoo forum about configuring separate db server and odoo front end server::
https://www.odoo.com/forum/help-1/question/how-to-connect-odoo-with-postgresql-146966
