### ISSUE TITLE
About getting the full rights to all features of an odoo database

### ISSUE THREAD

**Issue by larskjohansen** [Yenthe666/InstallScript#246]
When I log in as a new user on a new odoo database I can not get admin rights ... And when I try to log in with "admin" and "the generated Password for superadmin (database)"
is the output: Wrong login / password.

My scritp:
OE_SUPERADMIN = "admin"
// Set to "True" to generate a random password, "False" to use the variable in OE_SUPERADMIN
GENERATE_RANDOM_PASSWORD = "True"
OE_CONFIG = "$ {} OE_USER server"

So how do I get full rights to all features of an odoo database?

**Comment by Yenthe666** [comment]
@larskjohansen the superadmin password is not your Odoo user it's password. It's the password for database operations and nothing else.
When you've created your database through the frontend you've filled in a password for your admin user, it is this one that you're looking for (which is not stored in the config either by the way).

**Comment by larskjohansen** [comment]
@Yenthe666 - does this mean that when I create the first odoo database, the user who is created gets admin rights?

![Skærmbillede fra 2020-08-04 10-30-16](https://user-images.githubusercontent.com/17451970/89272975-380ed000-d63f-11ea-9899-e71d72e19a04.png)

**Comment by Yenthe666** [comment]
Yep :) And the field "Master Password" needs the master password set in your service.conf file.
