### ISSUE TITLE
Building wheel for lxml (setup.py)  freezes.

### ISSUE THREAD

**Issue by ichdamola** [Yenthe666/InstallScript#247]
Hello Yenthe! I have used the installation script to provision clean instances several times smoothly. Now, I tried to use it, but the installation froze while "Building wheel for lxml", I had to ctl + C to move to the next step. I am installing on a DigitalOceans droplet.

**Comment by Yenthe666** [comment]
How much RAM does the droplet have?

**Comment by ichdamola** [comment]
1GB RAM, 1 vCPU. Oh, I guess that might be the problem. I will increase vCPU, and see how it works out.

**Comment by Yenthe666** [comment]
Yeah or the 1GB RAM. There have been more reports of this and basically the server doesn't have enough resources to finish it.
See https://github.com/Yenthe666/InstallScript#minimal-server-requirements

**Comment by ichdamola** [comment]
Thank you for the recommendation, I have now taken it into account. But the problem was that DigitalOceans recently upgraded Ubuntu droplet to version 20.04 from 18.04. I had to choose the version 18.04 to make requirements install smoothly like they used to.
