### ISSUE TITLE
[9.0] Missing Dependency: psycogreen - For Use With Longpolling/LiveChat

### ISSUE THREAD

**Issue by lukebranch** [Yenthe666/InstallScript#25]
@Yenthe666 ,

While running your script for testing with Aeroo i've noticed that the psycogreen dependency is not installed which means livechat will not function.

Dependency is installed by pip:

sudo pip install psycogreen

That along with multiple workers (ie. greater than 0) enabled and a longpolling port assigned will allow for proper function for the livechat module.

**Comment by Yenthe666** [comment]
@lukebranch what a great catch! I'll add this in when I have some extra time to test it.
Thanks! :+1

**Comment by lukebranch** [comment]
@Yenthe666 ,

No problem. Sorry I missed this issue thread:

https://github.com/Yenthe666/InstallScript/issues/18

I'll make sure to post any other missing dependencies I find (if any) so as not to create too many issues.

**Comment by Yenthe666** [comment]
@lukebranch fixed in all versions of my script. Thanksl :+1:
