### ISSUE TITLE
ssl not working on new install with script.

### ISSUE THREAD

**Issue by dishdoctor** [Yenthe666/InstallScript#250]
Package python-certbot-nginx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-certbot-nginx

E: Package 'python-certbot-nginx' has no installation candidate
sudo: certbot: command not found
SSL/HTTPS is enabled!
* Starting Odoo Service
Starting odoo-server: odoo-server.

please fix

**Comment by Yenthe666** [comment]
Which OS, which version, which script, which configuration, which steps followed? This is far too little info at least.

**Comment by dishdoctor** [comment]
Odoo 13 install script Ubuntu 20.04
All the steps specified to enable ssl with nginx.

I was able to get it working by manually installing 

Sudo apt-get install python3-certbot-nginx -y

sudo certbot --nginx -d My website.com --noninteractive --agree-tos --email Myemail --redirect

**Comment by ygol** [comment]
I believe 'snap' should be used to install certbot in ubuntu 20.04
`sudo snap install --classic certbot`

**Comment by dishdoctor** [comment]
On Ubuntu server?

**Comment by dishdoctor** [comment]
Your script should work with 20.04 server right?

**Comment by dishdoctor** [comment]
the script tries to install python-certbot-nginx

**Comment by dishdoctor** [comment]
I just tried a new install on ubuntu 18.04 using your odoo14 script and I'm still getting error:

Package python-certbot-nginx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python3-certbot-nginx

E: Package 'python-certbot-nginx' has no installation candidate
sudo: certbot: command not found
SSL/HTTPS is enabled!

to correct the issue I add a "3" to the part in the script "python-certbot-nginx" so it looks like "python3-certbot-nginx"
and everything works after doing this.

**Comment by WonderM** [comment]
#Python2 (#252) development had been stopped and #Python3 is now the only version in development.
The migration to #Python3 is not yet 100% complete yet the challenge you are facing.
Just this little tweek on your OS will solve this challenge:
sudo ln -s /usr/bin/python3 /usr/bin/python
This will create a link to direct python to the latest python3.

Happy Coding #LTHB

**Comment by Yenthe666** [comment]
& by default our script installs P3:
https://github.com/Yenthe666/InstallScript/blob/5cd3a2bb5216f5ecee797c6418913db33a2076bd/odoo_install.sh#L78
and adds certbot : https://github.com/Yenthe666/InstallScript/blob/5cd3a2bb5216f5ecee797c6418913db33a2076bd/odoo_install.sh#L357
So I wonder why yours failed.

**Comment by dishdoctor** [comment]
Not sure, I tried it both on Ubuntu server 18.04 and 20.04 default settings. 
Get the same error.

**Comment by Yenthe666** [comment]
Which provider did you test on?

**Comment by dishdoctor** [comment]
Digital ocean 
2vcpu 2GB ram

**Comment by cj9255** [comment]
Thanks "dishdoctor" your edit helped. This worked for installing Odoo 13 & 14 on 20.04 while SSL was failing with nginx certbot.

"Package python-certbot-nginx is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-certbot-nginx

E: Package 'python-certbot-nginx' has no installation candidate

Err:8 http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]

E: The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Err:8 http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

The following package was automatically installed and is no longer required:
  libssl1.0.0
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  libpng12-0

Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested nginx plugin does not appear to be installed

Saving debug log to /var/log/letsencrypt/letsencrypt.log
The requested nginx plugin does not appear to be installed


**After Doing dishdoctor suggestion**

Odoo 13 & 14 / install script Ubuntu 20.04

All the steps specified to enable ssl with nginx. I was able to get it working by manually installing

sudo apt-get install python3-certbot-nginx -y

sudo certbot --nginx -d YOURWEBSITE.com --noninteractive --agree-tos --email YOUREMAIL --redirect

**Comment by dishdoctor** [comment]
Can we get the script updated to rectify this issue?

**Comment by Yenthe666** [comment]
Done in https://github.com/Yenthe666/InstallScript/commit/03d3db69d415201c3a52a2b356d6b2a196a85a12
