### ISSUE TITLE
Odoo 10 : Python 2.7 reached the end of its life on January 1st, 2020

### ISSUE THREAD

**Issue by rolandn** [Yenthe666/InstallScript#252]
Hi,
Is it already possible to install Odoo 10 ? 
Because the python version is deprecated no ?
When I lunch the script (odoo 10), Odoo doesn't install and I have this message for all packages : 
 "Package 'python-feedparser' has no installation candidate" and  :
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

Thank for your help.
Roland

**Comment by Yenthe666** [comment]
You should upgrade to a newer version or manage Python 2.x yourself. This is basically a known issue as Python 2 is EOL so if you don't keep up you need to provide your own solutions.
I'd highly advise you to upgrade to a newer version :)
