### ISSUE TITLE
nginx with www.mydomain.com and mydomain.com

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#259]
Hello,

Great script.

In one instalation I need that the odoo shop is rachable in

mydomain.com

and allso

www.mydomain.com

Is it posible with nginx and letsencrypt.?

Now it works great for me but with only one option.

**Comment by chris001** [comment]
Absolutely it's possible

**Comment by Yenthe666** [comment]
Yep :) Just expand your Nginx logic a bit so you rewrite mydomain.com to www.mydomain.com (or the other way around).
It's outside of the install script its scope though.
