### ISSUE TITLE
postgresql.service is active (exited)

### ISSUE THREAD

**Issue by gikwereresteven** [Yenthe666/InstallScript#263]
how I Can solve the problem of Postgresql active (exited) many days without solution of it.
I install odoo13 using scripts odoo is active(running), i can't accessing my database i don't know what happen because it was working well on ubuntu 20.04 and where i hosted after two weeks postgresql active(exited).

pg_lsclusters:
12  main    5432 online postgres /var/lib/postgresql/12/main  /var/log/postgresql/postgresql-12-main.log // is online 
Please help me.
Thanks regards

![Screenshot from 2020-10-15 14-46-03](https://user-images.githubusercontent.com/40658827/96128091-355d1080-0ef5-11eb-965c-fecd2e7bfc27.png)

**Comment by Yenthe666** [comment]
@gikwereresteven what happens if you restart PSQL?

**Comment by gikwereresteven** [comment]
thanks your scripts was good for me very easy to install it was running well sure.
 so when i restart still have active (exited) rigtht now i can't access my database.
I try to stop, start, restard even enable nothing changed Sir

**Comment by Yenthe666** [comment]
Have you tried restarting your server? What's in the logfiles of postgreSQL?

**Comment by gikwereresteven** [comment]
How can restart my server odoo is running well problem is posgress only

**Comment by gikwereresteven** [comment]
12  main    5432 online postgres /var/lib/postgresql/12/main /var/log/postgresql/postgresql-12-main.log

**Comment by gikwereresteven** [comment]
when I run like that i see is running well

![Screenshot from 2020-10-15 16-23-56](https://user-images.githubusercontent.com/40658827/96142932-e61ddc80-0f02-11eb-9a8a-2dfb109b4da5.png)

**Comment by Yenthe666** [comment]
reboot your VM.

**Comment by gikwereresteven** [comment]
no change

**Comment by gikwereresteven** [comment]
On my browser the error I have:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by Yenthe666** [comment]
Show the output from the Odoo & PostgreSQL logs.

**Comment by gikwereresteven** [comment]
I installed as it is no change i did  let me check

**Comment by gikwereresteven** [comment]
![Screenshot from 2020-10-15 17-15-21](https://user-images.githubusercontent.com/40658827/96149831-0f8e3680-0f0a-11eb-994d-9a4241a4beb6.png)

**Comment by Yenthe666** [comment]
I really need better info, I cannot help you this way. Please paste the correct parts which indicates ERROR's or failures. Not some random little part in the logs..

**Comment by gikwereresteven** [comment]
thanks, sir I am a new user of odoo the problem is this for sure  **postgresql is active(exited)** is not running but odoo is active running 
so i installed odoo using your process of your scripts so i don't know how to shows you that file you may asked to me, everything is ok but postgress is only problem i have i was running well last time but the cause of make it going down i don't know
Kind regards

**Comment by Yenthe666** [comment]
Well, dig logs & outputs. There have to be errors. Since you're not providing any further details and seem to have an extremely low level of knowledge about systems there is not much I can do though. I suggest you to do research and self-study about all components.

**Comment by gikwereresteven** [comment]
ok thanks for your help
let try to find that log
