### ISSUE TITLE
What Am I missing?

### ISSUE THREAD

**Issue by WonderM** [Yenthe666/InstallScript#268]
Done! The Odoo server is up and running. Specifications:
Port: 8069
User service: odoo
Configuraton file location: /etc/odoo-server.conf
Logfile location: /var/log/odoo
User PostgreSQL: odoo
Code location: odoo
Addons folder: odoo/odoo-server/addons/
Password superadmin (database): ***************************
Start Odoo service: sudo service odoo-server start
Stop Odoo service: sudo service odoo-server stop
Restart Odoo service: sudo service odoo-server restart

Hi @Yenthe666 

Previous InstallScript dnever gave an issue but this time something interesting i happening
 I will only refere to the current challenge as I have not documented the previous installation challenges.

This time, the installation didn't create the "odoo_user", I had to do it manually and I am OK

re-installation went well but then I can't access the local server on the browser with error message "ERR_CONNECTION_REFUSED" and the log file is not created.

I am on Linux Mint 20: Cinnamon DE

Please note, that I have not installed NginX and SSL as I don't need them locally

**Comment by Yenthe666** [comment]
@WonderM what does the log mention?

**Comment by WonderM** [comment]
It was not created. I left the installation for now but will check it later. Something is funny this side

**Comment by Yenthe666** [comment]
Yeah run Odoo from the terminal & then check the logs please :)

**Comment by WonderM** [comment]
Hi @Yenthe666 

Please receive my apology for responding this late.

Please note that first challenge of why @Linux_Mint didn't create the necessary user account, /odoo/custom and /odoo/custom/addons  is not resolved and we both agree that this will have to be a follow up with the relevant developers. Yes, it's a funny way to challenge my interest.

The second challenge why odoo gave me a challenge to run:
  By trying to solve the first challenge, I relaunched the whole script without commenting out some of the details.
  This led to inserting two details in the /etc/odoo-server.conf file and upon commenting out one, I have now a working system.

So, Please receive my apology for distracting you. I have moved to another residential place and I am juggling between my task and unfortunately had disturbed your peace. I hope you will pardon me for my lack of focus.

Let The Hacking Beggin (LTHB) ;)

**Comment by Yenthe666** [comment]
So I guess we can conclude that it works? :D

**Comment by WonderM** [comment]
Indeed, it works ;)

The only challenge is to understand why it didn't work the first time. I kept on relooking it and decided to give you the full terminal output, maybe I am missing something.

The error points to line 70.

Here's the link to pastebin
https://pastebin.com/i2zMTBgz

Check line 2 of pastebin

**Comment by Yenthe666** [comment]
Strange:
`./odoo_install.sh: line 70: n----: command not found`
Could it be you removed a " by accident?

P.S: Closing as it is working
