### ISSUE TITLE
odoo_instal.sh 8.0 update-rc.d error.

### ISSUE THREAD

**Issue by F4NNIU** [Yenthe666/InstallScript#27]
$OE_CONFIG error:
echo '# Provides: $OE_CONFIG' >> ~/$OE_CONFIG

**Comment by Yenthe666** [comment]
@FanNiu what is your error / issue? This is to limited to help I'm afraid..

**Comment by FanNiu** [comment]
in ubuntu 16.04,  "sudo update-rc.d $OE_CONFIG defaults" Can not add Startup Items.
recommend change line 124.
echo '# Provides: $OE_CONFIG' >> ~/$OE_CONFIG
to
echo "# Provides: $OE_CONFIG" >> ~/$OE_CONFIG

**Comment by Yenthe666** [comment]
This has been fixed quite a while ago. Shouldn't be a problem anymore.
