### ISSUE TITLE
After running the script, ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ishmumx** [Yenthe666/InstallScript#275]
First of all thank you to the creator of this script. 

I would like to report an issue: When you run this on a fresh Ubuntu 18.04 machine, it..........doesn't work. 

Details:

System used:

Digital Ocean $5/month Ubuntu 18.04 droplet
1GB RAM/25GB storage,1VCPU

Expected behavior: For the webserver to pull the setup page

Actual behavior: ERR_CONNECTION_REFUSED when going to IP:Port

The odoo logs have nothing showing in them. Also:

`root@odoo:~# service odoo-server status
● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; generated)
   Active: active (exited) since Sun 2020-11-22 20:46:08 UTC; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 30530 ExecStop=/etc/init.d/odoo-server stop (code=exited, status=0/SUCCESS)
  Process: 30536 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/SUCCESS)

Nov 22 20:46:08 odoo systemd[1]: Stopped LSB: Enterprise Business Applications.
Nov 22 20:46:08 odoo systemd[1]: Starting LSB: Enterprise Business Applications...
Nov 22 20:46:08 odoo odoo-server[30536]: Starting odoo-server: odoo-server.
Nov 22 20:46:08 odoo systemd[1]: Started LSB: Enterprise Business Applications.
`

I am at a loss here where else to look for issues. Any help would be appreciated. Thanks!

**Comment by Yenthe666** [comment]
Basically this https://github.com/Yenthe666/InstallScript#minimal-server-requirements and there are numerous reports like this in the past.
