### ISSUE TITLE
Ubuntu 20.04 libpng12-0

### ISSUE THREAD

**Issue by kimasplund** [Yenthe666/InstallScript#281]
On a fresh AWS Ubuntu 20.04 
So im not sure is libpng12-0 strictly needed for v14 but having it in the line(78) to install dependencies seems to cause the entire line to get skipped and not installing any of them (and in turn not installing python3-pip so requirements.txt also get skipped). libpng12-0 seems to have been removed from ubuntu rep since pre 18.04 also.
If some version of odoo cant live without libpng12-0 fix can be found here: https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html
Otherwise would it work to just install libpng-dev instead?

never mind. i think i broke it by my self somehow or it just did not add the repository (line 61) correctly for some reason

**Comment by herawais** [comment]
did you found any solution ?

**Comment by Yenthe666** [comment]
> never mind. i think i broke it by my self somehow or it just did not add the repository (line 61) correctly for some reason
