### ISSUE TITLE
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.

### ISSUE THREAD

**Issue by sergemercado** [Yenthe666/InstallScript#283]
I tried using the `sudo wget https://raw.githubusercontent.com/Yenthe666/InstallScript/14.0/odoo_install.sh` then I encountered that error while scrolling through the terminal.

**Comment by Yenthe666** [comment]
Err not related to the script as you're literally trying to download it but don't have the packages to do so

**Comment by sergemercado** [comment]
I apologize since I still don't understand what you said yet, it's my first day of using Ubuntu and tried to install Odoo 14 Enterprise using your script. I just thought `testresources` is part of the requirements of Odoo 14.

**Comment by Yenthe666** [comment]
Just do a `pip3 install testresources` first :)
