### ISSUE TITLE
After Create database with demo data

### ISSUE THREAD

**Issue by apilabhk** [Yenthe666/InstallScript#284]
Error:
TypeError: this.$consumeEventAnchors is undefined

https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5236
Traceback:
_unbind_anchor_events@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5236:264
destroy@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5221:2000
OdooClass.extend/</prototype[name]</<@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:4620:488
_deactivate_tip@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5295:165
_check_for_tooltip@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5292:6
update@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5283:363
_processMutations@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5313:72
observer</mutationTimer<@https://om.maurysolutions.com/web/content/95-063fde4/web.assets_common.js:5314:160

**Comment by Yenthe666** [comment]
That has nothing to do with my script though. It is a JS error in Odoo itself and besides of that without debug mode on it gives no meaningful context either.

**Comment by apilabhk** [comment]
Hi, I checked it without debug mode when using by domain getting error as mentioned but when try to access direct by IP it's not given that error
