### ISSUE TITLE
Odoo 14

### ISSUE THREAD

**Issue by quantum-space** [Yenthe666/InstallScript#285]
[npm-debug.log](https://github.com/Yenthe666/InstallScript/files/5716356/npm-debug.log)
Description: Ubuntu 18.04.5 LTS
Release: 18.04
Codename: bionic

There is a problem with the direction of the language.

<img width="706" alt="1" src="https://user-images.githubusercontent.com/75446107/102508268-41e91b00-4096-11eb-9deb-50d601add4a6.png">

**Comment by quantum-space** [comment]
[npm-debug.log](https://github.com/Yenthe666/InstallScript/files/5716361/npm-debug.log)

**Comment by ekitsikpui5** [comment]
Any fixes for this?

**Comment by vvgediya** [comment]
I am also getting the same error on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/11443543/115651285-7f153080-a348-11eb-9c08-0947d84ccf5b.png)

I have solved this error previously by upgrading the nodejs and npm version.

**Comment by Yenthe666** [comment]
I remember I fixed it about a year ago
