### ISSUE TITLE
404 on static files

### ISSUE THREAD

**Issue by overthrowrobotics** [Yenthe666/InstallScript#288]
![q7qhMr6hnY](https://user-images.githubusercontent.com/32023173/103110984-c12da000-45fc-11eb-8af0-114f4a0cc6ae.gif)
I used the 13.0 install script and set nginx to true. The odoo-server.conf had /odoo/custom/addons but that folder didn't exist and was causing an error when starting related to ir_module_module not found. I created the custom/addons folder and restarted. Odoo started but all static files are 404. 

https://recordit.co/q7qhMr6hnY

**Comment by Yenthe666** [comment]
Looks like another misuse/configuration though. What did the full log show?

**Comment by Yenthe666** [comment]
Closing as no response.
