### ISSUE TITLE
odoo service automatic shutdown issue.

### ISSUE THREAD

**Issue by elliotxin** [Yenthe666/InstallScript#29]
I deploy the odoo 9 in the digital ocean with ubuntu 14.4, i am sure the server never restart, because if the server  restart, the ip address will change also.my question is when i type "sudo service odoo-server start" to start the odoo, but in the second day, the odoo can not open anymore, i should going to Terminal to type this commend again to start odoo, so does had anyway to help me keep the odoo running?

**Comment by Yenthe666** [comment]
Hi @elliotxin,

If the server never restarts the Odoo service shouldn't ever go down or back up either. A service keeps running thoughout the lifetime of the server and in combination with a daemon it will always start at bootup. So this looks like you've got another problem going on.
Either way: yes you can always manually start or stop the Odoo with `sudo service odoo-server start` or stop.
