### ISSUE TITLE
How can I open port 5432 in order to use powerbi to analyze odoo data?

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#290]
How can I open port 5432 in order to use powerbi to analyze odoo data?

postgres only works with localhost

I used webmin to manage postgres allowed ports and databases but it is not working

**Comment by chris001** [comment]
What operating system?  If Ubuntu OS then the Ubuntu firewall ("`ufw`") is maybe blocking that port `5432` by default so you must open it with a command, or with `webmin`.
Try this command to view which ports `postgres` is listening on:
`netstat -lp | grep postgres`

**Comment by fgarcia-humanoide** [comment]
No , I have no ufw or similar. I think it is something with postgresql.conf. By default it only works with localhost.

**Comment by Yenthe666** [comment]
See https://stackoverflow.com/a/38466547/2262409 as a sample but not related to my script :)
