### ISSUE TITLE
[v14] missing dependency for Enterprise: psycopg2-binary

### ISSUE THREAD

**Issue by ray-odoo** [Yenthe666/InstallScript#294]
To resolve:

`pip3 install psycopg2-binary
`

**Comment by Yenthe666** [comment]
Yep indeed, I noticed this one last week too, just didn't add it yet.
Added in at https://github.com/Yenthe666/InstallScript/commit/897e7d49accd1c7fd6b31694ea45ebe3bb999b94 - thanks for reporting!
