### ISSUE TITLE
Odoo 12 active (exited)

### ISSUE THREAD

**Issue by kalicolorgold** [Yenthe666/InstallScript#295]
Using ubuntu 20.04 on aws ec2 i run your file for 12.0 odoo branch and i get mgs bellow:

ubuntu@odoo:~$ sudo service odoo-server status
● odoo-server.service - LSB: Enterprise Business Applications
     Loaded: loaded (/etc/init.d/odoo-server; generated)
     Active: active (exited) since Sat 2021-01-16 07:36:12 UTC; 5min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 436 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/SUCCESS)

Jan 16 07:36:12 odoo.exelbuy.com systemd[1]: Starting LSB: Enterprise Business Applications...
Jan 16 07:36:12 odoo.exelbuy.com odoo-server[436]: Starting odoo-server: odoo-server.
Jan 16 07:36:12 odoo.exelbuy.com systemd[1]: Started LSB: Enterprise Business Applications.

I also notice that the dependencies installation hangs at .....lxml setup.py

Installing collected packages: pytz, Babel, decorator, docutils, lxml, requests, ebaysdk, feedparser, greenlet, gevent, html2text, MarkupSafe, Jinja2, libsass, Mako, pbr, mock, num2words, soupsieve, beautifulsoup4, ofxparse, passlib, olefile, Pillow, psutil, psycopg2, pyparsing, pydot, pyldap, PyPDF2, pyserial, python-dateutil, pyusb, qrcode, reportlab, suds-jurko, python-stdnum, vatnumber, vobject, Werkzeug, XlsxWriter, xlwt, xlrd
  Running setup.py install for lxml ... 

I have tried on Ubuntu 18 and 20.04 servers and same error.  In Ubuntu 16 no issue with installation but sill wont run.

Could you please assist. Thank you

**Comment by Yenthe666** [comment]
how much RAM does your VM have?

**Comment by kalicolorgold** [comment]
RAM is 1gb on aws ec2. 

I observed in Ubuntu 16 that it did not run because postresql was not running. when i fixed that, it can now run. 

My issue is, i prefer Ubuntu 20.4 to the others but installation keeps hanging at preparing wheel for lxml or libsass

**Comment by kalicolorgold** [comment]
I chanced upon https://stackoverflow.com/questions/33064433/lxml-will-never-finish-building-on-ubuntu

Yes memory resource constraint is certainly the issue.

Will work around it and update you

Thanks so much.

PS: Apparently Postgresql 9.5 and above require more than 1GB RAM (2GB minimum).

This means with my 1GB I can use only postgresql 9.3 which requires only (128MB of RAM)

**Comment by Yenthe666** [comment]
Yes, as noted in our readme. See https://github.com/Yenthe666/InstallScript#minimal-server-requirements
