### ISSUE TITLE
Odoo 14 can't start after installation on ubuntu 20.10 on rpi4(8G)

### ISSUE THREAD

**Issue by faithiology** [Yenthe666/InstallScript#296]
It is giving me "502 bad gateway" error.
any ideas?

**Comment by Yenthe666** [comment]
That has to be a networking/config option :) Can you access the Odoo by IP & port? e.g "127.0.0.1:8069"?

**Comment by faithiology** [comment]
No I can't

**Comment by Yenthe666** [comment]
What's in the logs?
