### ISSUE TITLE
The install script is not working with version 10

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#30]
The install script is not working with version 10

**Comment by fgarcia-humanoide** [comment]
odoo is not running. I did just what the installscript says.

**Comment by gediminasvenc** [comment]
Found a quick fix for v10. You have to add [options] line in odoo-server.conf in /etc/ folder, and rename DEAMON to DEAMON=/odoo/odoo-server/odoo-bin in odoo-server file in etc/init.d folder.
But its working only with community version. Still looking for a solution for an enterprise version

**Comment by fgarcia-humanoide** [comment]
DAEMON=/odoo/odoo-server/odoo-bin was allready in my instalation

the [options] line was allready in my instalation too

so

The install script is not working with version 10

Thank you for the answer

**Comment by gediminasvenc** [comment]
I managed to tun community version with modifications mentioned in my post, but not enteprise

**Comment by fgarcia-humanoide** [comment]
I am running community , I have the lines you wrote from the begining, without making any changes.

But I can't start the service

**Comment by fgarcia-humanoide** [comment]
I changed DAEMON=/odoo/odoo-server/odoo-bin

to

DAEMON=/odoo/odoo-server/openerp-server

and now the odoo process started 

but I have

I**nternal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

**Comment by gediminasvenc** [comment]
Found solution for enterprise version, one dependancy was missing - just pip install xlsxwriter

@fgarcia-humanoide check your files once more here are is mine:

for enterprise:
```
odoo-server.conf:
[options]
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/enterprise/addons,/odoo/odoo-server/addons
xmlrpc_port = 8069

```
for community it will be:
```
[options]
logfile = /var/log/odoo/odoo-server.log
addons_path=/odoo/enterprise/addons,/odoo/odoo-server/addons
xmlrpc_port = 8069
```

and in odoo-server file **line 14** changed to this:
`DAEMON=/odoo/odoo-server/odoo-bin`

**Comment by fgarcia-humanoide** [comment]
ok, you were right.

It was solved with your advice. I did not change version in the script and installed 9

The change needed was to write [options] in odoo-server.conf

Thank you very much

**Comment by Yenthe666** [comment]
Hi @fgarcia-humanoide and @gediminasvenc,

The script is still in development for Odoo 10, I'm currently at Odoo experience and have limited time and resources.
Give me a few days to get this up and running 😄

**Comment by gediminasvenc** [comment]
Here is working script for both v10 community and enterprise versions(Just dont forget to change True of False in line 30)
[odoo_install.sh.zip](https://github.com/Yenthe666/InstallScript/files/513444/odoo_install.sh.zip)

**Comment by Yenthe666** [comment]
Hi @fgarcia-humanoide,

I've just finished the V10 script and it is now ready to install Odoo.

**Comment by paulbrunn** [comment]
i got an internal server error for enterprise.. community works

**Comment by Yenthe666** [comment]
@paulberater can you post the traceback here please?

**Comment by paulbrunn** [comment]
@Yenthe666 where can i find it?

**Comment by Yenthe666** [comment]
In your Odoo log, at /var/log/odoo usually.
