### ISSUE TITLE
Ubuntu 20

### ISSUE THREAD

**Issue by lbonjean** [Yenthe666/InstallScript#307]
In order to get the script working on ubuntu 20 there is a modification needed in the postgresql installation section.
This is what I changed:
#sudo apt-get install postgresql postgresql-server-dev-all -y
sudo apt-get install postgresql postgresql-common libpq-dev -y

**Comment by Yenthe666** [comment]
Hmm are you sure? We run multiple instances on 20.x with the script. Where do you host?

**Comment by lbonjean** [comment]
It was a fresh install from image on our own hosting.
The problem was with the postgresql-server-dev-all package.
When I try it now it seems to work.
Strange.

**Comment by Yenthe666** [comment]
Good to know! Thanks for the feedback & the report :)
