### ISSUE TITLE
[14.0] Update Odoo Repository - Fetch

### ISSUE THREAD

**Issue by yboujraf** [Yenthe666/InstallScript#309]
Dear @Yenthe666 

I'd like to fetch the latest commits from odoo 14 repository on my server.

I created this small script "odooUpdateRepository.sh"

```
sudo git fetch origin 14.0
sudo git reset --hard origin/14.0
sudo service odoo-server restart -u all -c /etc/odoo-conf-file.conf
```

Is it a good way?

Best Regards,

**Comment by Yenthe666** [comment]
Yeah that is fine :) I'm not a huge fan of `-u all` running that after every update though but it is possible too.
