### ISSUE TITLE
[10.0] If ubuntu user odoo already existed the script will failed to create custom addons directory  

### ISSUE THREAD

**Issue by jlzhou** [Yenthe666/InstallScript#31]
When I install ubuntu 16.04.1, I created the odoo user in GUI. After it, log on by odoo account, run the script to create odoo dev environment, it reports issue to add custom/addons directory.

I suggest not register odoo service in ubuntu since no instant error log displayed during debug.

**Comment by Yenthe666** [comment]
Hi there,

@chris001 is expanding the script and he is building in these safety checks at https://github.com/Yenthe666/InstallScript/pull/74 to counterpart this.
In short: I'm aware of the issue and a fix should come eventually!

Regards,
Yenthe

**Comment by chris001** [comment]
@jlzhou 
This bug should be fixed, please try the version referred in #74 and report back your results!
