### ISSUE TITLE
[14] installscript not working porblembus unavailable and  problem wkhtmltopdf

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#310]
Imposible to use odoo 14

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
Exception: bus.Bus unavailable

I dont know what this means , no bus , no taxi no bycicle

and once again with the wkhtmltopdf problem. It is a monster that never dies

The script works fine in odoo 13

I supose nobody is using odoo 14 so problems do not appear.

**Comment by chris001** [comment]
Solution here: 
https://www.linkedin.com/pulse/how-fix-exception-busbus-unavailable-odoo-version-13-francisco-neto?articleId=6622987408927531008

**Comment by Yenthe666** [comment]
We run dozens of V14 instances without any issues so has to be your builds/deployments :)
