### ISSUE TITLE
add custom module

### ISSUE THREAD

**Issue by the-yaz** [Yenthe666/InstallScript#314]
Hi sir ! thanks for the script .
as a developer i need to create a custom modules , to do that i tried to configure odoo with pycharm , but it didn't work , actually when i type in terminal "sudo service odoo-server start " it worked fine but when i try to run it by using "./odoo-bin" give a some errors , 
do you have any suggestions to where and how add my customs modules .

**Comment by Yenthe666** [comment]
Hi,

Sorry but it is out of scope of this issue tracker.
However, the official help forums are a good place to ask this :) See https://www.odoo.com/forum/help-1
