### ISSUE TITLE
Odoo 15 and Ubuntu 20.04

### ISSUE THREAD

**Issue by ivanporras** [Yenthe666/InstallScript#318]
CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/db.py", line 66, in _initialize_db
    env = odoo.api.Environment(cr, SUPERUSER_ID, {})
  File "/odoo/odoo-server/odoo/api.py", line 506, in __new__
    for env in transaction.envs:
AttributeError: 'NoneType' object has no attribute 'envs'

**Comment by ivanporras** [comment]
so weird I set admin and admin for email and password in the odoo interface database manager. It' work

**Comment by Yenthe666** [comment]
The rest of the install went smooth? :)

**Comment by ivanporras** [comment]
yes all is OK. Thank you!
