### ISSUE TITLE
V15

### ISSUE THREAD

**Issue by Eureco** [Yenthe666/InstallScript#319]
tried creating 3 droplets with diffrent sizes .

Used the install script , then I got the ip:port website where I have to fill in the database password + infos.
Database creation error: Access Denied

No access to database.

Never had this problem with script for V14

**Comment by ivanporras** [comment]
when you are creating the database in the odoo interface, set email: admin and password: admin. Works for me

**Comment by unjoss** [comment]
same here as eureco reported, Iwas hitting my head against the wall installed it 3 times brand new ubuntu20 server and error denied database. 

thanks ivanporras that worked for me too.

**Comment by Eureco** [comment]
Thank you, this was indeed the solution ! Use admin/admin after that in odoo change your users email and password.
