### ISSUE TITLE
requirements source

### ISSUE THREAD

**Issue by kimasplund** [Yenthe666/InstallScript#325]
Line 81 is:
sudo -H pip3 install -r https://github.com/odoo/odoo/raw/${OE_VERSION}/requirements.txt

But i think should be: 
sudo -H pip3 install -r https://raw.githubusercontent.com/odoo/odoo/${OE_VERSION}/requirements.txt

to work.

**Comment by Yenthe666** [comment]
No, requirements is in the main direct of the odoo path:
https://github.com/odoo/odoo/blob/15.0/requirements.txt

**Comment by kimasplund** [comment]
But for the script to work it needs the raw file does it not?
Or is it just me having issues with this? because with the current line im stuck installing stuff manually after.
Second line works for me on ubuntu

**Comment by Yenthe666** [comment]
It's run by thousands of people in the world & you are the very first one ever having issues with this 🤔
