### ISSUE TITLE
Wkhtmltopdf V15 Ubuntu 20.04 issue (AW2 EC2)

### ISSUE THREAD

**Issue by FutureAndroidLearn** [Yenthe666/InstallScript#326]
In ubuntu 20.04 I ran V15 script, but wkhtmltopdf was not installed. Then I tried 

*sudo apt-get install xfonts-75dpi
sudo wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.bionic_amd64.deb
sudo dpkg -i wkhtmltox_0.12.6-1.bionic_amd64.deb
sudo cp /usr/local/bin/wkhtmltoimage /usr/bin/wkhtmltoimage
sudo cp /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf* 

And wkhtmltopdf was installed properly. I tested by

*wkhtmltopdf https://google.com google.pdf*

But in Odoo  I'm still getting "Unable to find Wkhtmltopdf in this system"

**Comment by Yenthe666** [comment]
Closing in favor of https://github.com/Yenthe666/InstallScript/issues/316
I still have to patch the script for wkhtmltopdf but no time the last weeks.
