### ISSUE TITLE
github login failing

### ISSUE THREAD

**Issue by geoff-bbc** [Yenthe666/InstallScript#328]
I'm official partner and I have access to the odoo/enterprise repo but the github login portion of the script is failing. Tried a couple of different ways, changed github pwd to be 100% sure. Still failure. Installing Enterprise v14 on AWS EC2 t2.small ubuntu 20.04.
Thanks in advance.

**Comment by Yenthe666** [comment]
Sorry but this works on hundreds of deployments. Which error do you get and are you sure you don't have 2FA which fails it?

**Comment by geoff-bbc** [comment]
Hi @Yenthe666. I was working on a direct connection to github and received the following message. I think this is probably the reason the script is failing to authenticate too.

> remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
> remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.

**Comment by Yenthe666** [comment]
Yeah new Github rules. You can do it by trying 2/3 times usually or switch over to other/safer ways as explained on the blog :)
