### ISSUE TITLE
Upgrade from 14 to 15

### ISSUE THREAD

**Issue by killmasta93** [Yenthe666/InstallScript#329]
Hi
I wanted to say amazing script its working wonderful, 
Now that v15 came out i would love to upgrade from 14 to 15, would someone shed some light which parameters i should change for this to work?
If i would update would the information disappear? or gets migrated with it? 

Thank you

**Comment by Yenthe666** [comment]
Hi,

Migrations are totally not related to the installation script.
You'll need to upgrade either through Odoo (upgrade.odoo.com) or through OpenUpgrade
