### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by yboujraf** [Yenthe666/InstallScript#330]
Dear @Yenthe666 

Any chance to get the docker compose to install Odoo like your install script with environment , Odoo.conf files and volumes (addons)

Best regards

**Comment by Yenthe666** [comment]
Hi  @yboujraf,

We don't really actively use docker & I don't have it on the roadmap honestly.
I'm not a huge fan of Docker personally :-)

Regards,
Yenthe
