### ISSUE TITLE
unable to locate odoo.conf file

### ISSUE THREAD

**Issue by arham93** [Yenthe666/InstallScript#332]
Trying to add a new folder link to the conf file of odoo.conf for custom addons 

Please Guide 
Used default just download and run the Script

**Comment by WonderM** [comment]
Hi

Please check line 157 to 178 of the installation script.

Of you can understand this part, it will be easier to ammend it according to your liking

Hope you will be good

**Comment by Yenthe666** [comment]
Yeah indeed :) Just add the repository on your disks, link it in the config file and configure the app.
