### ISSUE TITLE
Odoo 11 starts and stops after 3 seconds

### ISSUE THREAD

**Issue by KarimNaouar** [Yenthe666/InstallScript#336]
Since approximativly one month when I use the script to install odoo 11 every thing looks fine until I start odoo-server service, the process appears for 3 seconds then it stops.

If I start ./odoo-server I get this error: ModuleNotFoundError: No module named 'PIL'

This happen in wsl environment and also in vps

**Comment by WonderM** [comment]
try: pip install Pillow

**Comment by KarimNaouar** [comment]
I made some changes to the script to fix the issue: https://gist.github.com/KarimNaouar/f42a66946f80c32a810f10a21cd04fc8
