### ISSUE TITLE
After installing 

### ISSUE THREAD

**Issue by mohannadfj** [Yenthe666/InstallScript#337]
Dear , 

I have used your script to install odoo in my digitalocean ubuntu 20.4

but i cloudnt modify the parameters as the installation took its proccess without giving me the oppotunity to modify. 

now i got the odoo installed and seems it is working but i do not know the database name and password 

is there any way to check the name and passrord ? and modify parameters? 

Regards ,

**Comment by Yenthe666** [comment]
Hi,
Our scripts don't auto run, you have to manually execute them and so you did.
After the script finalized it always prints out all details about the Odoo config:
https://github.com/Yenthe666/InstallScript/blob/6db2b2121fb5b0a325c6e7577f003b4ad36d719c/odoo_install.sh#L371-L386

Besides of that you can look in the Odoo config file for the configuration values.
