### ISSUE TITLE
How to find and access files?

### ISSUE THREAD

**Issue by PRTBELL** [Yenthe666/InstallScript#339]
I have hosted my Odoo on Digital Ocean, but how do I access the developer files? I need to make customizations but cannot find the proper path. 

Please guide me on how i can configure my Pycharm to access and modify the contents to add custom modules.

![image](https://user-images.githubusercontent.com/91874900/152488078-c410ecbf-3980-452a-81ca-e1b648d38ec0.png)

**Comment by Yenthe666** [comment]
Sorry but that's completely out of the scope of our script/repository :) See e.g https://www.jetbrains.com/help/pycharm/remote-development-a.html

**Comment by PRTBELL** [comment]
Thank you for the link,
I am able to establish a connection with the remote server, but I am not sure which project repository to select.

**Comment by PRTBELL** [comment]
/// Sorry but that's completely out of the scope of our script/repository 

Do you mean i cannot make custom modules and develop it through pycharm?
