### ISSUE TITLE
[10.0/Master] Feature Request - Add Whiptail for TUI (Terminal UI)

### ISSUE THREAD

**Issue by lukebranch** [Yenthe666/InstallScript#34]
@Yenthe666 ,

<H1>Suggested Features:</H1>

<ul>
<li>Markup current 10.0 branch script with whiptail to provide a TUI for selecting options during the setup process.</li>
</ul>

<H1>More Info On Whiptail:</H1>

<a href="https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail">Whiptail Wiki</a>

<H1>Notes:</H1>

<p>I will come back to this issue and revisit it with more information as soon as possible. Generally I believe the first step would be to markup the current script with whiptail without adding any new features besides the TUI.</p>

<p>I will elaborate on these points shortly, this is just a placeholder for now.</p>

**Comment by Yenthe666** [comment]
Hi @lukebranch,

I was looking at this again. It actually does look interesting.
I've made a test branch here: https://github.com/Yenthe666/InstallScript/blob/All-Whiptail/odoo_install.sh
This branch simulates all the usual commands in terminal, gives an overview and then simulates a progress bar.
Example screenshots:
![image](https://user-images.githubusercontent.com/6352350/29488251-676c4a6c-8507-11e7-99f4-af428aec0658.png)

![image](https://user-images.githubusercontent.com/6352350/29488254-7482e12a-8507-11e7-86fe-b522a98eae8c.png)


Thoughts?

**Comment by lukebranch** [comment]
@Yenthe666 ,

Thanks for the information. It looks great!

I'm going to come back to this issue thread a bit later once I have a bit of free time so we can discuss.

I feel like this might be a bit more of a friendly interface for non-technical end-users looking to use the script. I've also been thinking about piping the output of the script into a logfile as well. I have an SH script laying around that I use for this, i'll make a PR with it when I come back to this issue thread.

**Comment by Yenthe666** [comment]
I guess that since nobody ever requested this anymore that I should close this off & don't put too much time in it?

**Comment by lukebranch** [comment]
@Yenthe666 , yes, no problem i'll close this off. I have not had time to work on a PR unfortunately.
