### ISSUE TITLE
hello can you help?

### ISSUE THREAD

**Issue by alahwany** [Yenthe666/InstallScript#348]
hello

iam new in odoo and still learning it.

i saw your script on youtube and trying install odoo enterprise as your video but said  
```
"Your authentication with Github has failed! Please try again.
In order to clone and install the Odoo enterprise version you
need to be an offical Odoo partner and you need access to
http://github.com/odoo/enterprise.
TIP: Press ctrl+c to stop this script."
```

can you help me to install it to learn it and explorer it ?

thank you

**Comment by Yenthe666** [comment]
Sorry but there's not much to help with. Either your Github username or password you enter in the terminal is invalid 😅

**Comment by alahwany** [comment]
my user & password is correct but on the terminal said faild i don't know why! 

is this script need to license from odoo or github? and how to buy it?

**Comment by Yenthe666** [comment]
Ah right you're trying to pull the enterprise part too. You can only do that if you have been added to https://github.com/odoo/enterprise as a collaborator. The only way to being added is if you are an official Odoo partner or an employee working at a partner and that you add yourself through https://www.odoo.com/my/partner.
Otherwise you cannot have Github access ;)

**Comment by yonalemneh** [comment]
Hello; I am facing the same issue.
I am an official partner, I have access to Odoo Enterprise on Github, I am using your installation script for Odoo 15, but no luck. Can you help me on that?

**Comment by javier-marroquin** [comment]
I have the same problem to install Odoo Enterprise V15.

The Partner has granted me access.

**Comment by eversatis** [comment]
@Yenthe666 github had changed the login method and do not allow password sign in now in terminals. You may find a way to update the code to grant terminal authentication to login. You can try the git bash for private repo for the changes.

**Comment by Yenthe666** [comment]
Our scripts support it by default, just use your token as password ;)

**Comment by etomProductions** [comment]
Hello,

To other pepole facing the same issue:
1- Add ssh to your GitHub account
2- create access token in your GitHub account


in the script installation:
1- USERNAME = GITHUB USERNAME
2- PASSWORD = GITHUB ACCESS TOKEN


Thank you
