### ISSUE TITLE
Stock/Inventary module error installation

### ISSUE THREAD

**Issue by apropsi** [Yenthe666/InstallScript#349]
Impacted versions:
14.0
Steps to reproduce:
Ubuntu 22.04
Install Odoo 14 with script, add all libraries, try to add stock (inventary) addon

Last hope, nothing found in internet. I just recreate database, update all modules and dependencies.
Dunno what else to do.

Current behavior:
Odoo Server Error
Error:
Odoo Server Error

Traceback (most recent call last):
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/quantum/quantum-server/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/quantum/quantum-server/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /quantum/quantum-server/addons/stock/data/stock_data.xml:13, near
record id="stock_quant_stock_move_line_desynchronization" model="ir.actions.server"
            field name="name">Correct inconsistencies for reservation</field
            field name="model_id" ref="base.model_ir_actions_server"/>
            field name="state">code</field>
            field name="code">
quants = env['stock.quant'].sudo().search([])

move_line_ids = []
move_line_to_recompute_ids = []

logging = ''
No other modules are installed, no custom modules, just a fresh installation in a new server.

**Comment by PieceofShid** [comment]
Did you find any solutions ?

**Comment by apropsi** [comment]
No :_(
The only thing that occurs to me is that it is a missing library. But I have gone through the entire script and installed each and every one of them by hand. The stock module is 14.0.1.1
I have also tested its dependencies that there is nothing wrongly installed.
I can not think of anything else.

Problem should be here:
odoo.tools.convert.ParseError: while parsing /quantum/quantum-server/addons/stock/data/stock_data.xml:13, near
record id="stock_quant_stock_move_line_desynchronization" model="ir.actions.server"
            field name="name">Correct inconsistencies for reservation</field
            field name="model_id" ref="base.model_ir_actions_server"/
            field name="state">code</field>
            field name="code">

Maybe ir.actions.server its wrong...

**Comment by PieceofShid** [comment]
Maybe it's not yet compatible using ubuntu 22, Because after I downgrade it to 20 version its working properly

**Comment by apropsi** [comment]
Works perfect in ubuntu 20.04

Thank you @PieceofShid , good advice!
