### ISSUE TITLE
Active (exited)

### ISSUE THREAD

**Issue by onerpsystems** [Yenthe666/InstallScript#350]
I have followed the script step by step and the only thing I changed is Generate password = "False"
However, once the installation is complete, I am unable to start Odoo service and  when I check the status it five me 
active (exited)
I am unable to access the Odoo instance from port 8069
Note I have installed Odoo 14 CE on a cloud VPS, with Ubuntu 20.04

![IMG_20220629_020531.jpg](https://user-images.githubusercontent.com/62468568/176318681-fead6906-7873-4810-908d-791c4d422c06.jpg)

**Comment by Yenthe666** [comment]
First stop it (sudo service odoo stop) or kill it (sudo kill -9) with the pid or reboot your server once. That generally solves it and only happens the very first time sometimes.
