### ISSUE TITLE
PY-BABEL removed from apt-get in Ubuntu 16.10 (Yakkety Yak)

### ISSUE THREAD

**Issue by ianathompson** [Yenthe666/InstallScript#36]
The python library py-babel has been removed from Ubuntu 16.10 and will cause a fatal error in the apt-get portion of the script. Was able to install it via pip. Suggest adding babel to the list of "pip install" commands.

**Comment by Yenthe666** [comment]
Hi @ianathompson,

Thank you for the report and sorry for the delay.
Any official sources that prove this fact?

Regards,
Yenthe

**Comment by ianathompson** [comment]
Deprecated now as you need to look at 17. Versions now. I assume it is the same for 17 though.

Also, I've been working on my own installation. Too many changes happening in Odoo and Python, and the packages available for Ubuntu.

As such, I have just been using PIP to install all of the python packages instead of the prebuilt ones for Ubuntu.

Since you have to use apt-get and pip, I figured I would just use PIP instead and only use apt-get for python2.7 and postgresql 9.6.

It works better that way for me, and today's server have no problem getting the pip packages installed.

Additionally due to the fact that any really system must have production, staging and development versions of Odoo running on the system, I have changed do doing everything manually.

Just made it easier.

On Aug 20, 2017 12:08 AM, "Yenthe V.G" <notifications@github.com> wrote:

Hi @ianathompson<https://github.com/ianathompson>,

Thank you for the report and sorry for the delay.
Any official sources that prove this fact?

Regards,
Yenthe

**Comment by chris001** [comment]
@Yenthe666 @ianathompson 
Look at my pull request #62 
It installs many missing python3 packages with `pip3`.
Without these packages, Odoo crashes/fails.
Try it and give your feedback.

**Comment by Yenthe666** [comment]
This has been handled in the newest installation script (V11 - see https://github.com/Yenthe666/InstallScript/blob/11.0/odoo_install.sh#L71) with a `pip3` install to fullfill. This should also prevent this bug from happening on newer installations.
