### ISSUE TITLE
Imposible to install odoo 15 due to AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by fgarcia-humanoide** [Yenthe666/InstallScript#365]
Impossible to install odoo 15

This is the error

AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

The problem is that pyopenssl is broken . It was 20 days ago.

¿Anione with a solution?

Thanks

**Comment by fgarcia-humanoide** [comment]
This script is not working 

In the odoo forum someone answerd but I have no results after changing requirements.txt

Avatar
[Malay Khamar](https://www.odoo.com/fr_FR/forum/aide-1/user/1282379?forum_origin=/forum/aide-1/impossible-to-install-odoo-v15-ce-in-ubuntu-20-04-due-to-pyopenssl-210435)
28 septembre 2022
Hi, 
I have already installed odoo 15 CE in ubuntu 20.04. 
please upgrade pip to 22.2.2 and yes Check if you can upgrade pyOpenSSL to 22.0.0 to fix the issue.

Try to install all the requirements from odoo/requirements.txt file

Hope it will help you.

**Comment by Yenthe666** [comment]
See https://github.com/odoo/odoo/issues/99809, nothing specific for our script.
