### ISSUE TITLE
Great job need to Update for Odoo 16 EE

### ISSUE THREAD

**Issue by khaledalrajeh** [Yenthe666/InstallScript#366]
Dear Yanthe 

can you please update this great script for odoo 16 EE, looks like not working with the new release.

Thanks

**Comment by Yenthe666** [comment]
@khaledalrajeh I made some changes/improvements :) I believe it should be better/smoother now :)

**Comment by khaledalrajeh** [comment]
Dear Yanthe

Thank you for your valuable update, but looks like still dependences missing, 
Can you please use the script in fresh Ubuntu 20.04 installation to figure out what's missing.

Thanks

**Comment by Yenthe666** [comment]
Part of it is related to bad dependency management from Odoo it seems actually.
