### ISSUE TITLE
npm WARN notsup Unsupported engine for rtlcss@4.0.0

### ISSUE THREAD

**Issue by Ahmed4120** [Yenthe666/InstallScript#368]
When the command run: 
` sudo npm install -g rtlcss`

This is the result

```
/usr/local/bin/rtlcss -> /usr/local/lib/node_modules/rtlcss/bin/rtlcss.js
npm WARN notsup Unsupported engine for rtlcss@4.0.0: wanted: {"node":">=12.0.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: rtlcss@4.0.0

+ rtlcss@4.0.0

```

I suggest to modify the script to make npm and node are compatible

**Comment by quangbahoa** [comment]
Switch your Node to >=12 ??

**Comment by Ahmed4120** [comment]
> Switch your Node to >=12 ??

I did, another WARN came.. it seems using node10 is ok and I have to ignore this WARN.
