### ISSUE TITLE
sub-domain 

### ISSUE THREAD

**Issue by RoobleCali** [Yenthe666/InstallScript#373]
i am using this script how can i set up sub-domain using degital ocean any one help me this

**Comment by noblesocius** [comment]
@Yenthe666 Kindly close this issue as there doesn't seem to be any movement here. Also this doesn't really consider the InstallScript part of things. Thank you

**Comment by chris001** [comment]
@shakuurally Normally you specify your fully qualified domain name ( subdomain.domain.com ) in all places where it asks for the host name.  Then, this script should install and run Odoo server just fine.
