### ISSUE TITLE
proposed update on the debian install odoo script

### ISSUE THREAD

**Issue by safecoms** [Yenthe666/InstallScript#38]
Hi Team,

I noticed that the odoo install script for debian is missing the automatic port set up when creating the server config file.
At the end in the script it is xmlrpc_port = 8069

But I think that it should be xmlrpc_port = $OE_PORT

Best regards

**Comment by safecoms** [comment]
I forgot the link to the script I am referring to
https://github.com/Yenthe666/InstallScript/blob/10.0/odoo_install_debian.sh

**Comment by Yenthe666** [comment]
Hi @safecoms,

Thanks a lot for your report and this was indeed a bug.
It has been fixed here https://github.com/Yenthe666/InstallScript/commit/967f70364d4c10d41f38683652445418ce835196

Regards,
Yenthe
