### ISSUE TITLE
What would be my default odoo email & Password

### ISSUE THREAD

**Issue by roqkabel** [Yenthe666/InstallScript#387]
After installing the script.
And setting up the database.

I cannot login into the Odoo APP.

I tried using email: admin & password: admin

please what could be the possible cause.

**Comment by niyasraphy** [comment]
hi, @roqkabel 
the password is entered by the end user while setting up the db, in case if you forget, you can try resetting it from the db level, if you find this one as hard, you can just drop the current db(if no data needed from the db) and create a new db and try remembering the password you recorded while creating the db.

thanks

**Comment by noblesocius** [comment]
Please mark this issue as closed if fixed. If not, please post the error log. Thank you

**Comment by roqkabel** [comment]
Thanks @niyasraphy
