### ISSUE TITLE
customs addon folder with entreprise

### ISSUE THREAD

**Issue by safecoms** [Yenthe666/InstallScript#39]
Hi guys,

I noticed that if the entreprise is installed with the odoo10 script, the custom addons folder is being skipped.
I don't know if it is a wanted result or not but I think it should not be the case.

Also, If we use the script for installing multiple Odoo on the same server, we don't need to re-install PostgreSQL and the dependencies right?

**Comment by Yenthe666** [comment]
Hi @safecoms,

Thank you for your report.
This was indeed a bug, something that was not ported from V9 to V10.
Fixed in https://github.com/Yenthe666/InstallScript/commit/9a3f1296889247c41c174c0a2692e9b5ea2f8f69

Regards,
Yenthe
