### ISSUE TITLE
Add email setup like postfix 

### ISSUE THREAD

**Issue by danayen** [Yenthe666/InstallScript#390]
Have any Idea to setup email configuration?
For example, installing postfix and set smtp , ... . Finally use local emailing system.

**Comment by chris001** [comment]
Install [Virtualmin GPL](https://www.virtualmin.com/download/) it installs and manages Postfix, mail users, mail boxes, filter spam/virus, your Odoo domain, etc.
```
wget https://software.virtualmin.com/gpl/scripts/virtualmin-install.sh
sudo sh virtualmin-install.sh
```

**Comment by danayen** [comment]
Thank you Chris. My issue was about adding Postfix installation (and Virtualmin) to odoo installation script.
I mean, we can add these installations as an option.

A few codes will add to script, but solve many things :) ... . I'm going to try it.

**Comment by chris001** [comment]
Great idea, @danayen , add two lines to the script to install Virtualmin with Odoo !
