### ISSUE TITLE
Enterprise edition 

### ISSUE THREAD

**Issue by Powerpbox** [Yenthe666/InstallScript#391]
we tried to install enterprise edition , when it comes to git repository now we can not use passwords But tokens , I added user name ( not email ) and in password fireld the token , enterprise was not installed but only community . Can you guide please ?

**Comment by AcroVenom** [comment]
> we tried to install enterprise edition , when it comes to git repository now we can not use passwords But tokens , I added user name ( not email ) and in password fireld the token , enterprise was not installed but only community . Can you guide please ?
> 
> 

is the enterprise addons included in the conf file?

**Comment by Yenthe666** [comment]
I presume you have no access to github.com/Odoo/enterprise with that user?

**Comment by CaptAnil** [comment]
We have access and it is tested . Odio also confirmed the access and activated the same

Warm regards
Capt Anil Kumar Sharma
Mobile +91 7506926394
Default email : ***@***.***
________________________________

**Comment by noblesocius** [comment]
Kindly close the issue if solved. If not, please ping again as this post is two weeks old. Thank you

**Comment by Yenthe666** [comment]
Yeah I'm not sure, we don't have a lot of feedback/insights here. It works for hundreds of people 🤔
