### ISSUE TITLE
404: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by renshed** [Yenthe666/InstallScript#395]
---- Create ODOO system user ----
Adding user `odoo' to group `sudo' ...
Adding user odoo to group sudo
Done.

---- Create Log directory ----

==== Installing ODOO Server ====
Cloning into '/odoo/odoo-server'...
warning: redirecting to https://github.com/odoo/odoo.git/
remote: Enumerating objects: 40349, done.
remote: Counting objects: 100% (40349/40349), done.
remote: Compressing objects: 100% (28751/28751), done.
remote: Total 40349 (delta 11753), reused 33309 (delta 10354), pack-reused 0
Receiving objects: 100% (40349/40349), 155.20 MiB | 10.75 MiB/s, done.
Resolving deltas: 100% (11753/11753), done.
Updating files: 100% (35530/35530), done.

---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
* Creating server config file
* Generating random admin password
* Create startup file
* Create init file
* Security Init File
* Start ODOO on Startup
Nginx isn't installed due to choice of the user!
./odoo_install.sh: line 404: syntax error near unexpected token `fi'
./odoo_install.sh: line 404: `  fi'

**Comment by hunsly** [comment]
Missing `;` character before `then`:
https://github.com/Yenthe666/InstallScript/blob/0aafdd6e3c16f7d1dc4540485c41cc32e12a0f79/odoo_install.sh#L405
https://github.com/Yenthe666/InstallScript/blob/0aafdd6e3c16f7d1dc4540485c41cc32e12a0f79/odoo_install.sh#L402

**Comment by Yenthe666** [comment]
Should be resolved with https://github.com/Yenthe666/InstallScript/commit/87c8ade5700604b4e265cdeb28878a47758c0a11 I believe 🤔

**Comment by noblesocius** [comment]
@renshed Please mark this issue as solved and close it if it's been resolved. Thanks
