### ISSUE TITLE
I want to add a translation

### ISSUE THREAD

**Issue by danayen** [Yenthe666/InstallScript#402]
I want to send pull request, but GitHub say that I have to be a contributor.
I want to add translation for fa.po. How can I do?

**Comment by noblesocius** [comment]
Have you tried the 'fork and pull request' workflow? If not, please try doing that from [here](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project). If you've already tried that and still can't create the request, please mention Yenthe and he'll get back to you on this. Thank you

**Comment by Yenthe666** [comment]
Yes indeed :) You should be able to fork, make code changes and then make a pull request to this repository.
