### ISSUE TITLE
Instructions in script don't align with instructions in readme

### ISSUE THREAD

**Issue by cliffkujala** [Yenthe666/InstallScript#406]
For consistency sake.  The filename used on the readme is odoo_install.sh, however the filename used in the instruction block between lines 9 and 14 is odoo-install.sh

Small problem but one you might want to consider fixing.

**Comment by Yenthe666** [comment]
Hi,

Not quite :) The readme on Github explains you how to download the file by command and execute it.
The instructions in the script explain creating a file manually and adding in the code.

**Comment by cliffkujala** [comment]
True.  I guess I saw it more as a consistency thing.  Is there a reason you would want the naming convention to be different per the two methods?
