### ISSUE TITLE
Unescaped left brace in regex is deprecated, passed through in regex

### ISSUE THREAD

**Issue by maravento** [Yenthe666/InstallScript#43]
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/(?<!\\)\${ <-- HERE ([^}]+)}/ at /usr/sbin/pam_getenv line 78.
Repeat several times
thanks

**Comment by shedeed101** [comment]
i am having the same problem

**Comment by Yenthe666** [comment]
Hi @maravento and @shedeed101,

Thank you for your report & feedback.
Can you give more information on how to reproduce this issue? I've just tested with the latest versions of my script but I do not have any issues. Have you tried running the latest updates?

Regards,
Yenthe

**Comment by maravento** [comment]
It seems that the problem does not affect the operation of the program or the script

**Comment by Yenthe666** [comment]
It actually doesn't and it is coming from the postgreSQL packages itself. It isn't harmfull.
