### ISSUE TITLE
Updating odoo after installation

### ISSUE THREAD

**Issue by bnjroos** [Yenthe666/InstallScript#53]
How to update odoo 10CE to the latest version after installation ? 
Thanks,

bnjroos

**Comment by Yenthe666** [comment]
Hi @bnjroos,

1. Navigate into the Odoo
2. Do a git fetch
3. Do a git reset
4. Do an update of your Odoo

In commands something like this:
1. cd /odoo/your_odoo
2. sudo git fetch origin 10.0
3. sudo git reset --hard origin/10.0
4. sudo service odoo-server stop
    sudo su your_odoo_user
    ./odoo-bin -u all -c /etc/your_odoo.conf

For more information see my tutorial at https://www.odoo.yenthevg.com/update-odoo-environment-github/

Regards,
Yenthe
