### ISSUE TITLE
[11] Excel — XLWT required

### ISSUE THREAD

**Issue by salmemik** [Yenthe666/InstallScript#60]
Hi and thank you for the script! I'm not sure if this is install script issue but anyway something seems to be missing from my Ubuntu 16.04.3 environment after installation of Odoo 11 Community using the script.  See the attached image, Excel export option cannot be selected and there is text: "Excel — XLWT required".
 
<img width="969" alt="excel xlwt required" src="https://user-images.githubusercontent.com/11749898/31859576-86e30e3a-b716-11e7-89b3-8051fe74e675.png">

**Comment by chris001** [comment]
Fixed in #62 
@Yenthe666

**Comment by Yenthe666** [comment]
Hi @salmemik,

Thanks a lot for your report! The installation script was indeed missing the dependency. This has been fixed in https://github.com/Yenthe666/InstallScript/commit/c4c69b17fa55fce5585d202ec11a1159e8086785

Regards,
Yenthe
