### ISSUE TITLE
ERR_CONNECTION_REFUSED. Cannot reach my-ip:8069

### ISSUE THREAD

**Issue by Vaerum** [Yenthe666/InstallScript#61]
Hi

I have just installed Odoo 11 CE using the install script from Odoo 11. 

After running the script, the Odoo service starts, but I cannot reach Odoo by http//:my-ip:8069. I get the error ERR_CONNECTION_REFUSED (chrome).

# service odoo-server status
root@odoo-11:~# service odoo-server status
● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; bad; vendor preset: enabled)
   Active: active (exited) since Sun 2017-10-22 14:01:39 UTC; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4265 ExecStop=/etc/init.d/odoo-server stop (code=exited, status=0/SUCCESS)
  Process: 4270 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/SUCCESS)

Oct 22 14:01:39 odoo-11 systemd[1]: Starting LSB: Enterprise Business Applications...
Oct 22 14:01:39 odoo-11 odoo-server[4270]: Starting odoo-server: odoo-server.
Oct 22 14:01:39 odoo-11 systemd[1]: Started LSB: Enterprise Business Applications.

# netstat -ntlp | grep LISTEN
root@odoo-11:~# sudo netstat -ntlp | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1329/sshd       
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1475/postgres   
tcp6       0      0 :::80                   :::*                    LISTEN      1476/apache2    
tcp6       0      0 :::22                   :::*                    LISTEN      1329/sshd 

Any suggestions?

Best Regards,
Rasmus

**Comment by chris001** [comment]
> Active: active (exited) 

Your odoo service is not running - it exited immediately, probably because a required system package is missing.

**Comment by chris001** [comment]
@Vaerum 
Try this:
```
sudo service odoo-server stop
cd /odoo/your-odoo
sudo su odoo
./odoo-bin -c /etc/odoo-server.conf
```

**Comment by Vaerum** [comment]
Just tried: ./odoo-bin -c /etc/odoo-server.conf

`Traceback (most recent call last):
  File "./odoo-bin", line 5, in <module>
    import odoo
  File "/odoo/odoo-server/odoo/__init__.py", line 84, in <module>
    from . import modules
  File "/odoo/odoo-server/odoo/modules/__init__.py", line 8, in <module>
    from . import db, graph, loading, migration, module, registry
  File "/odoo/odoo-server/odoo/modules/graph.py", line 10, in <module>
    import odoo.tools as tools
  File "/odoo/odoo-server/odoo/tools/__init__.py", line 7, in <module>
    from . import pdf
  File "/odoo/odoo-server/odoo/tools/pdf.py", line 4, in <module>
    from PyPDF2 import PdfFileWriter, PdfFileReader
ImportError: No module named 'PyPDF2'
`

**Comment by chris001** [comment]
@Vaerum 
That's the reason why your odoo server failed to start.
Your server is missing the `PyPDF2` python package.
`pip3 install PyPDF2`

@Yenthe666 
Maybe some missing packages in the script?
Look here, because, maybe you need to add some packages, maybe some are missing from this script:
https://webkul.com/blog/install-odoo11-on-ubuntu/

**Comment by Vaerum** [comment]
I found out that some python3 dependencies were missing. After installing all these everything worked again.

apt install python3-babel python3-pypdf2 python3-passlib python3-werkzeug python3-lxml python3-decorator python3-dateutil python3-psycopg2 python3-psutil python3-html2text python3-docutils python3-reportlab python3-requests 

Best regards,
Rasmus

**Comment by chris001** [comment]
Thanks @Vaerum 
I added the missing python3 packages in #62

**Comment by the7th** [comment]
For me, I need to also install these two through pip3:

sudo pip3 install pyyaml
sudo pip3 install jinja2

**Comment by chris001** [comment]
@the7th 
You might want to install all of them just to be sure you get all of them, because on a 16.04 about 10 packages were missing:
```
sudo pip3 install Babel decorator docutils ebaysdk feedparser gevent greenlet html2text Jinja2 lxml Mako MarkupSafe mock num2words ofxparse passlib Pillow psutil psycogreen psycopg2 pydot pyparsing PyPDF2 pyserial python-dateutil python-openid pytz pyusb PyYAML qrcode reportlab requests six suds-jurko vatnumber vobject Werkzeug XlsxWriter xlwt xlrd
```

**Comment by SedonasOpensourceSolutions** [comment]
Noob? When I sudo su odoo it asks for a password, using the script, what would the password be please?

**Comment by Yenthe666** [comment]
@SedonasOpensourceSolutions by default the odoo user is created without a password. You can set one by calling `sudo passwd odoo`.
@Vaerum and @the7th there where indeed quite some packages missing in the beginning for V11 (under P3). If you'd get them all again it should be all fine.

**Comment by chris001** [comment]
@SedonasOpensourceSolutions 
If you are not `root`, then `sudo su odoo` will ask you for a password.

**Comment by prabby** [comment]
Faced same error in 13.0, the server was missing the PyPDF2 python package.
Thanks for the help
