### ISSUE TITLE
[v11] Backup file wrong name

### ISSUE THREAD

**Issue by jreders** [Yenthe666/InstallScript#64]
i observed a small problem i would like to signal, when using the web based interface to backup my database, the .zip file is not created well, it's named " b'mydb_2017-10-23_21-47-00.zip' " instead of " mydb_2017-10-23_21-47-00.zip ". By the way, deleting the " b'...' " characters made the zip file usable for import.

**Comment by chris001** [comment]
@jreders  Are you sure it isn't a bug in odoo causing that bug on the backup filename encoding?

**Comment by Yenthe666** [comment]
This indeed looks like an encoding issue. What happens when you take a normal dump from the web interface?

**Comment by jreders** [comment]
Hello,
Sorry for the delay guys...
@chris001 Indeed, it looks like a encoding issue
@Yenthe666 i have the same problem with a normal dump
Moreover i observed the same problem downloading any file attached in a project/tasks (.pdf ..etc)
Any idea to solve this issue? should i signal this problem to Odoo?
Thanks for your help, it is appreciated!

**Comment by chris001** [comment]
@jreders 
This is only a guess, but maybe the error is a result of missing package related to text or xml.
Can you re-run the installer script latest version to make sure you get the packages which were previously missing, then delete the duplicate contents from the `/etc/odoo-server.conf` file, and try it again.

**Comment by Yenthe666** [comment]
Or, alternatively, only call the update & installation part of the script to prevent potential issues.
