### ISSUE TITLE
Can not access localhost

### ISSUE THREAD

**Issue by Rmendiola** [Yenthe666/InstallScript#71]
Hello Everyone

I am new to Ubuntu, but i managed to install odoo using Yenthe excellent script, and server seems to be running. this is what i get:

`● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; generated; vendor preset: enabled)
   Active: active (exited) since Mon 2017-11-06 17:40:58 WET; 22min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 7860 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/S
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/odoo-server.service

nov 06 17:40:58 Mendiolaserver systemd[1]: Starting LSB: Enterprise Business App
nov 06 17:40:58 Mendiolaserver odoo-server[7860]: Starting odoo-server: odoo-ser
nov 06 17:40:58 Mendiolaserver systemd[1]: Started LSB: Enterprise Business Appl`

but when i try to access the main page from the web browser i just get a unable to connect localhost:8069

There does not seem to be any log file on /var/log/odoo/odoo-server.log so i can not post anything of some kind of error. 

I am using Ubuntu 17.10 and not sure if that has anything to do with me not being able to go into the setup screen of Ubuntu. 

since i am only testing, i did not change password or port or anything, i just downloaded the script, chmoded and installed with your instructions.

any ideas?

**Comment by Rmendiola** [comment]
O and by the way if i just write localhost, i get the apache2 ubuntu default page.

**Comment by chris001** [comment]
```
Active: active (exited)
```
Your odoo service has exited or possibly has been killed by Linux OOM (out of memory) manager.
How many GB of total RAM do you have on your server.

**Comment by Rmendiola** [comment]
Hi Chris, 

Thanks for getting back to me. well i am doing this on an old thinkpad laptop, i wanted just to try this so should have read that i need something more powerful even for testing.

but to answer your question i have 8gb ram.

**Comment by chris001** [comment]
8GB is more than enough RAM.
`service odoo-server restart` then reload the odoo web page.

**Comment by Rmendiola** [comment]
Keeps giving me the same error

● odoo-server.service - LSB: Enterprise Business Applications
   Loaded: loaded (/etc/init.d/odoo-server; generated; vendor preset: enabled)
   Active: active (exited) since Mon 2017-11-06 18:58:17 WET; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 8838 ExecStop=/etc/init.d/odoo-server stop (code=exited, status=0/SUC
  Process: 8840 ExecStart=/etc/init.d/odoo-server start (code=exited, status=0/S

nov 06 18:58:17 Mendiolaserver systemd[1]: Starting LSB: Enterprise Business App
nov 06 18:58:17 Mendiolaserver odoo-server[8840]: Starting odoo-server: odoo-ser
nov 06 18:58:17 Mendiolaserver systemd[1]: Started LSB: Enterprise Business Appl

**Comment by chris001** [comment]
```
journalctl -xe -u odoo-server
tail -40 /var/log/odoo/odoo-server
```

**Comment by Rmendiola** [comment]
HI Chris

when i try those commandas, i get the following:

-- Unit odoo-server.service has begun shutting down.
nov 06 18:58:17 Mendiolaserver odoo-server[8838]: Stopping odoo-server: start-st
nov 06 18:58:17 Mendiolaserver odoo-server[8838]: odoo-server.
nov 06 18:58:17 Mendiolaserver systemd[1]: Stopped LSB: Enterprise Business Appl
-- Subject: Unit odoo-server.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit odoo-server.service has finished shutting down.
nov 06 18:58:17 Mendiolaserver systemd[1]: Starting LSB: Enterprise Business App
-- Subject: Unit odoo-server.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit odoo-server.service has begun starting up.
nov 06 18:58:17 Mendiolaserver odoo-server[8840]: Starting odoo-server: odoo-ser
nov 06 18:58:17 Mendiolaserver systemd[1]: Started LSB: Enterprise Business Appl
-- Subject: Unit odoo-server.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit odoo-server.service has finished starting up.
-- 
-- The start-up result is done.

but when i run the second one it tells me there is nothing on the lg folder. 

i did check and the log folder is empty.

**Comment by Yenthe666** [comment]
@Rmendiola run your Odoo from the terminal and do a `-u all` - then check your logfile.

**Comment by Rmendiola** [comment]
Yenthe66

thanks for getting back to me. 

Actually i had to do basically all the dependencies installs by themselves each one at the time. some even i had to do with python3 not just python, to get them to stop showing on Sudo su odoo.

seems to be working now.

thanks you.

**Comment by Yenthe666** [comment]
@Rmendiola,

Thanks for the feedback!
Strange though, as all Python 3 dependencies should be installed (see https://github.com/Yenthe666/InstallScript/blob/11.0/odoo_install.sh#L71).
Could you double check if `pip` is installed on your server? Perhaps the problem originated there..
