### ISSUE TITLE
[11] Uncaught TypeError: Cannot read property 'isPassword' of undefined

### ISSUE THREAD

**Issue by salmemik** [Yenthe666/InstallScript#72]
Hi,

Again I'm not sure if this is Odoo or InstallScrip bug but anyway, here are steps to reproduce:

- Take new clean Ubuntu 16.04.3 virtual server. I used this: https://www.hetzner.com/virtual-server/cx20
- Install Odoo 11 Community using the script
- Install module, e.g. Sales Management
- Activate the developer mode
- Create one Product
- Open Product form and select "Set Defaults" from Developer tools menu
- ==> Odoo Client Error popup window will be displayed (see the picture & text is also copied below)

Screenshot is from Crome but error was similar looking with Safari as well

Regards,
Mikko

--------
TypeError: undefined is not an object (evaluating 'fieldsInfo[fieldName].options.isPassword')

http://xxx.xxx.xxx.xxx:8069/web/content/303-ecf5db7/web.assets_backend.js:640
Traceback:
TypeError: Cannot read property 'isPassword' of undefined
    at http://xxx.xxx.xxx.xxx:8069/web/content/303-ecf5db7/web.assets_backend.js:640:303
    at Function._.map._.collect (http://xxx.xxx.xxx.xxx:8069/web/content/302-537590b/web.assets_common.js:13:270)
    at _.(anonymous function) [as map] (http://xxx.xxx.xxx.xxx:8069/web/content/302-537590b/web.assets_common.js:69:526)
    at Class.set_defaults (http://xxx.xxx.xxx.xxx:8069/web/content/303-ecf5db7/web.assets_backend.js:639:514)
    at Class.perform_callback (http://xxx.xxx.xxx.xxx:8069/web/content/303-ecf5db7/web.assets_backend.js:628:866)
    at HTMLAnchorElement.<anonymous> (http://xxx.xxx.xxx.xxx:8069/web/content/302-537590b/web.assets_common.js:3909:11)
    at HTMLLIElement.dispatch (http://xxx.xxx.xxx.xxx:8069/web/content/302-537590b/web.assets_common.js:892:451)
    at HTMLLIElement.elemData.handle (http://xxx.xxx.xxx.xxx:8069/web/content/302-537590b/web.assets_common.js:865:173)

<img width="1375" alt="odoo_client_error" src="https://user-images.githubusercontent.com/11749898/32509444-f9969b86-c3f5-11e7-9e88-7d53c39b8c9a.png">

**Comment by chris001** [comment]
@salmemik 
Could it be related to this ?
https://github.com/odoo/odoo/pull/19588

**Comment by salmemik** [comment]
I don't have enough technical skills to tell :) I hope so if that commit will be made soon. One more thing I noticed. I installed Odoo 11 Community using this script also couple of weeks ago (17.10. I think) and in that environment I don't have this error.

**Comment by chris001** [comment]
The new OS 17.10 has many much newer versions of system packages.
If I were you I'd definitely post this issue on https://github.com/odoo/odoo/issues/new and include a link to this issue https://github.com/Yenthe666/InstallScript/issues/72 because if this crash is really a bug in odoo, then they will want to know about it right now, and if it isn't a bug, they'll want to see why they need to provide a more user friendly error message saying how to fix the issue. If a required package missing, it should say, this package is missing. Etc.

**Comment by Yenthe666** [comment]
Hi @salmemik,

Thank you for the bug report. The initial JavaScript error you posted is a bug in Odoo itself. I made a new bug report at https://github.com/odoo/odoo/issues/20786 to get this fixed.
@chris001 no it is not related to https://github.com/odoo/odoo/pull/19588 - different issue.
It is odd that you wouldn't have this error on the Ubuntu 17.04 though as it is JS related. Have you tried updating that Odoo to the latest source code? I'm quite sure it'll break there too then.
Anyways, keep an eye on https://github.com/odoo/odoo/issues/20786 it'll be fixed soon enough! 😉 

Regards,
Yenthe
