### ISSUE TITLE
Accounting Settings (Anglosaxon, Fiscal Year Locking,..)

### ISSUE THREAD

**Issue by armbakri** [Yenthe666/InstallScript#77]
Hi,
In Odoo11 CE , i am missing in accounting settings
1-Anglosaxon Enabling Check box
2-Fiscal Year and and Lock Accounting Date Features
3-Liquidity Transfer Account

**Comment by Yenthe666** [comment]
Hi @armbakri,

Thanks for the report.
This is not a bug in my script nor in Odoo though. All these features have been either changed or moved to the enterprise version.
1) Enterprise
2) No longer in Odoo 10 and 11. Odoo 12 will reintroduce this.
3) not sure, I think this is also enterprise now.

**Comment by chris001** [comment]
@armbakri 
Maybe worth for you to subscribe it's cheap for a monthly license for Odoo 11 Enterprise..
Also, verify these features are existing on Odoo 11 Enterprise online free demo: 
https://demo.odoo.com
