### ISSUE TITLE
Getting multiple errors after brand new install

### ISSUE THREAD

**Issue by davidjhi** [Yenthe666/InstallScript#79]
Hello!, first of all, thanks for all the work making this script!,
- Brand new server, ubuntu 16.04 fully updgraded, minimal installation, no special changes. 
- Unmodified script
- Nothing else installed.
- Server installed in a container (proxmox), accesing from lan.

After a succesfull run of the script, we have access to the odoo server, and we are able to create the new database. But after installing the first module, "sales", we get the attached error.

Also tried to install odoo without script, getting the same problems, so its most likely a bug with this build?, and not from the script¡?

Thanks in advance

`Error:
TypeError: self.searchview is undefined

http://10.45.50.11:8069/web/content/303-cd7572f/web.assets_backend.js:2093
Rastreo de error:
start@http://10.45.50.11:8069/web/content/303-cd7572f/web.assets_backend.js:2093:4017
__widgetRenderAndInsert/<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:3943:958
then/</</<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:802:678
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
updateFunc/<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:804:482
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
then/</</<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:802:849
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
then/</</<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:802:849
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
Deferred/</deferred[tuple[0]]@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:803:31
then/</</<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:802:678
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
then/</</<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:802:849
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
then/</</<@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:802:849
fire@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:796:281
fireWith@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:801:198
done@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:1192:86
callback@http://10.45.50.11:8069/web/content/302-4ae3859/web.assets_common.js:1212:15`

**Comment by chris001** [comment]
Try installing again, with my new version of the script, it's a **big update**, and report back your results:
```
rm odoo_install.sh
wget https://github.com/chris001/InstallScript/raw/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh
```
