### ISSUE TITLE
Outdated wkhtmltopdf version

### ISSUE THREAD

**Issue by sebastian-code** [Yenthe666/InstallScript#8]
There is a more recent version of the file for Ubuntu at the wkhtmltopdf portal, perhaps is worth it to modify the script, I worked with that version for the Odoo v8.0

**Comment by Yenthe666** [comment]
Hi Sebastian,

Thanks for making an issue about this. I assume you're talking about 0.12.2 or higher?
Odoo has announced that they officially support 0.12.1 at the moment and that 0.12.2 or higher might still give problems, that is why mine is still at 0.12.1!

**Comment by sebastian-code** [comment]
I imagine that, thanks for answer
