### ISSUE TITLE
Database creation error: Access denied

### ISSUE THREAD

**Issue by dinosaurkfb** [Yenthe666/InstallScript#81]
Hi,

Thank you for your great work of making this script.

I'm trying to install Odoo V11 in a Ubuntu16.04 server.
But it seems there is something wrong with the installation. When I create database in the first page, it says:
> Database creation error: Access denied

And when I check the log of postgresql, I found this error in the log:
> 2018-01-17 11:53:24 CST [1369-1] odoo@exampledb FATAL:  password authentication failed for user "odoo"
> 2018-01-17 11:53:24 CST [1369-2] odoo@exampledb DETAIL:  User "odoo" has no password assigned.

The password I entered is just the same as what's saved in odoo-server.conf. So can you help me figure out where the problem is?

BTW, in your script, *OE_SUPERADMIN* is defined, but I didn't see how it's used to create a password. I'm not sure if it's the reason behind this error.

**Comment by dinosaurkfb** [comment]
Never mind, the password I input is wrong because Chrome remembers the wrong password.

**Comment by Yenthe666** [comment]
Good catch. Happy you've figured it out. 😉

**Comment by IgnacioAz** [comment]
I already have this issue
