### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by BI-supports** [Yenthe666/InstallScript#85]
helloYenthe666 thanks for any thinks that you give us for helping i have some problems , i have using your script to install odoo v 9 in ubunto 16.4  it work nice and i have installed and server work good
my question is ? when i want to start service  using command sudo service odoo-server start it work but i need to show server running in the terminal i need to see error when I'm developing module in terminal ?

**Comment by chris001** [comment]
@osamaIT 
You can open another terminal and do this command to show the log lines instantly:
```
tail -f /var/log/odoo/odoo-server
```

**Comment by BI-supports** [comment]
ok i will try .   thanks  chris001
