### ISSUE TITLE
Install without sample data

### ISSUE THREAD

**Issue by eonlab** [Yenthe666/InstallScript#86]
Hi, I've used the install script for the first time to try it but it installed odoo with sample data. How can I use this script so it doesn't install the sample data?

Thank You.

**Comment by Yenthe666** [comment]
Hi @eonlab,

The install script only installs the Odoo itself. Creating the database and choosing if you want demo data or not is something that you do yourself.

**Comment by chris001** [comment]
@eonlab 
The first time you view your odoo site, it guides you to create your database, and you can leave the checkbox "Install demo data" off.

**Comment by eonlab** [comment]
I guess I passed that detail, Thank you both.
