### ISSUE TITLE
Odoo connection to /xmlrpc/2/common

### ISSUE THREAD

**Issue by ghost** [Yenthe666/InstallScript#88]
Firstly let me say Im a big fan of your work! thanks for providing these automation tools!

Im having a bit of an issue.. and im not sure what seems to be the problem.  Apologies if this is not the right place to tell you this, as i don't have your email.

Im trying to integrate "WP Odoo Form Integrator Settings" with Odoo 10, unfortunately the developers of that wordpress plugin are very scarce, and i really need this to work for my business to be able to link invoices to contact forms.

By integrating this plugin, it requires that the link: http://myodooserver.com:8069/xmlrpc/2/common
is able to be reached from outside.
http://myodooserver.com:8069 **is** able to be reached from outside, however when trying to access  http://myodooserver.com:8069/xmlrpc/2/common then i get a 404 error.
I was hoping with your experience with odoo & xmlrpc you might know what the problem would be?

Is there a specific step i need to do in "activating" xmlrpc from within the install script?

thanks in advance

**Comment by ghost** [comment]
So i tried a simple python script like this locally:

import xmlrpclib
url = 'http://localhost:8069'
common = xmlrpclib.ServerProxy('{}/xmlrpc/2/common'.format(url))
common.version()

ran the python script and keep getting this error:

`Traceback (most recent call last):
  File "xml.py", line 1, in <module>
    import xmlrpclib
  File "/usr/lib/python2.7/xmlrpclib.py", line 538, in <module>
    from xml.parsers import expat
  File "/home/user/xml.py", line 3, in <module>
    common = xmlrpclib.ServerProxy('{}/xmlrpc/2/common'.format(url))
AttributeError: 'module' object has no attribute 'ServerProxy'
`

Please tell me is xmlrpc disabled or something?   it seems it does not recognize ServerProxy

**Comment by Yenthe666** [comment]
Hi @2SI3NX,

By default it should be working just fine. You might want to look at better Python packages to handle API calls, such as erppeek, though as they're much easier to use.

**Comment by ghost** [comment]
thanks @Yenthe666 will keep that in mind.. However do you know why that simple python script isnt working locally? am i doing something wrong?  i just want to get the version first but it doesnt seem to be recognizing ServerProxy

**Comment by Yenthe666** [comment]
@2SI3NX not really sorry. I never use the default xmlrpc calls anyways so not much to compare for me 😞

**Comment by ghost** [comment]
@Yenthe666 

even when running your example from your site:

`
import erppeek

DATABASE = 'ErpPeekDemoDatabase'
SERVER = 'http://localhost:8069'
ADMIN_PASSWORD = 'admin'

client = erppeek.Client(server=SERVER)
 
if not DATABASE in client.db.list():
    print("The database does not exist yet, creating one!")
    client.create_database(ADMIN_PASSWORD, DATABASE)
else:
    print("The database " + DATABASE + " already exists.")
`

i get the error:
`Traceback (most recent call last):
  File "xml.py", line 1, in <module>
    import erppeek
  File "/usr/local/lib/python2.7/dist-packages/erppeek.py", line 27, in <module>
    from xmlrpclib import Fault, ServerProxy, MININT, MAXINT
  File "/usr/lib/python2.7/xmlrpclib.py", line 538, in <module>
    from xml.parsers import expat
  File "/home/user/xml.py", line 7, in <module>
    client = erppeek.Client(server=SERVER)
AttributeError: 'module' object has no attribute 'Client'
`

Any idea what is missing?  i just need to find the main problem here..

**Comment by Yenthe666** [comment]
Hi @2SI3NX,

I just tested it with a new Python file and it works fine out of the box.
Which Odoo version are you trying? Do you have custom development or very specific deployments?

Regards,
Yenthe

**Comment by ghost** [comment]
hi @Yenthe666,

I have installed fresh Ubuntu server with xfce4 minimal desktop and then straight away used your install script to install Odoo 10, the server is reachable locally and remotely. However im getting that error and im not sure why.. im starting to think im missing a specific dependency that comes with Ubuntu Desktop? unless im wrong..  Maybe a specific dependency of python?

**Comment by Yenthe666** [comment]
Really shouldn't be. If your Odoo is working, if you have Python and erppeek installed it should work fine.

**Comment by ghost** [comment]
Apologies, i had named the test file xml.py which coincidentally clashed with one of the python files so i had to just rename it so that it can work. thanks for the help anyway!

**Comment by Yenthe666** [comment]
Oh, ouch that is a painful thing. I'm happy you've figured it out & you're welcome! Best of luck.
