### ISSUE TITLE
custome module can't load

### ISSUE THREAD

**Issue by DudhatShivam** [Yenthe666/InstallScript#89]
Hello
as per this script with ent code, I cannot load a custom module
when I add the custom module in a folder then Odoo not loaded,
my conf. file like this 
admin_passwd = ******
xmlrpc_port = 8069
logfile = /var/log/odoo/odoo-server
addons_path=/odoo/enterprise/addons,/odoo/odoo-server/addons

I try like this 
1 : > addons_path=/odoo/custom/addons,/odoo/enterprise/addons,/odoo/odoo-server/addons
2 : > addons_path=/odoo/enterprise/addons,/odoo/custom/addons,/odoo/odoo-server/addons
3 : > addons_path=/odoo/enterprise/addons,/odoo/odoo-server/addons,/odoo/custom/addons

when I am trying custom module it will run perfectly without ent version
in custom module not use any single JS, CSS

**Comment by chris001** [comment]
@DudhatShivam 
Try my version from #74 it should fix this bug.
```
cd ~
rm odoo_install.sh
wget https://github.com/chris001/InstallScript/raw/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh
```

**Comment by DudhatShivam** [comment]
@chris001 
as per your script, there is the same folder structure

function create_odoo_server_config_file {
  local config=~/${OE_CONFIG}.conf
  local community_addons_dirs="${OE_HOME_EXT}/addons,${OE_CUSTOM_ADDONS}"
  addons_dirs=$community_addons_dirs
  if [[ $IS_ENTERPRISE == "True" ]]; then
    addons_dirs="${OE_ENTERPRISE_ADDONS},${community_addons_dirs}"
  fi
  cat <<EOF > $config

**Comment by chris001** [comment]
@DudhatShivam 
Did you run it though?  It fixes many, many bugs.

**Comment by Yenthe666** [comment]
Closing as there was no feedback.
