### ISSUE TITLE
I can not restart the service

### ISSUE THREAD

**Issue by deyvsonaguiar** [Yenthe666/InstallScript#91]
I've try many commands: 

sudo service odoo10 restart
sudo systemctl restart odoo10.service
sudo /etc/init.d/odoo10 restart
Restarting odoo10: odoo10.

but not stop and reload. 

I need that the applications write my news custom folders.  Help me please. 

my final log installation, look that: 

---- Create ODOO system user ----
Adding user `odoo10' to group `sudo' ...
Adding user odoo10 to group sudo
Done.

---- Create Log directory ----

==== Installing ODOO Server ====
Cloning into '/odoo10/odoo10-server'...
remote: Counting objects: 24148, done.
remote: Compressing objects: 100% (17812/17812), done.
remote: Total 24148 (delta 7798), reused 12627 (delta 5584), pack-reused 0
Receiving objects: 100% (24148/24148), 114.58 MiB | 11.84 MiB/s, done.
Resolving deltas: 100% (7798/7798), done.
Checking connectivity... done.
Checking out files: 100% (21950/21950), done.

---- Create custom module directory ----

---- Setting permissions on home folder ----
* Create server config file
* Change server config file
* Create startup file
* Create init file
* Security Init File
* Change default xmlrpc port
* Start ODOO on Startup
* Starting Odoo Service
Starting odoo10: odoo10.
-----------------------------------------------------------
Done! The Odoo server is up and running. Specifications:
Port: 8070
User service: odoo10
User PostgreSQL: odoo10
Code location: odoo10
Addons folder: odoo10/odoo10/addons/
Start Odoo service: sudo service odoo10 start
Stop Odoo service: sudo service odoo10 stop
Restart Odoo service: sudo service odoo10 restart

**Comment by deyvsonaguiar** [comment]
I solved. 

Make restarted in my server . Tks.

**Comment by chris001** [comment]
@deyvsonaguiar 
Try my fork, it's much a Big update #74 , much improved, more secure, bugs fixed, added support for nginx and free HTTPS: https://github.com/chris001/InstallScript/tree/patch-2/odoo_install.sh

```
cd ~
rm odoo_install.sh
wget https://github.com/chris001/InstallScript/raw/patch-2/odoo_install.sh
chmod +x odoo_install.sh
./odoo_install.sh --help
./odoo_install.sh
```

**Comment by deyvsonaguiar** [comment]
Eu posso instalar a versão 10 também nesse patch-2 or is exclusivy for install odoo 11?
