### ISSUE TITLE
Install Script (V11) on Ununtu 16.04 + auto_backup + pdf reports

### ISSUE THREAD

**Issue by rogerv95** [Yenthe666/InstallScript#94]
I'm not sure if it's an issue or I'm doing something wrong but I'm really frustrated and about to give up on odoo 11.
I've tried a lot of different configurations, install methods and scripts and I'm stuck with same issues. What I'm doing now is:
1.Fresh Ubuntu 16.04 install on VMware ESXI 5
2.Basic server setup (updates, static ip...)
3.Odoo 11 install from your script. (only parameter modifyed master password)
4.Testing with clean db or demonstration data db ==> pdf reports show plain text, html works well. I assume it's a wkhtmltopdf configuration problem but I'm installing it with the script.
5.Install some random odoo modules for testing (Invoice, Sales...) some times I got a 500 Internal Server Error while installing.
6.Upload via ftp the auto_backup addon. (changing permissions to write the folder)
7.If I update app list auto_backup addon shows broken link on it's icon and it's screenshots on description don't work.
8.After server reboot when loading odoo gives Internal server Error and other times a broken database selector page. I can still access odoo if I don't clear cache and I'm logged in but images and icons don't display.

As I said, I don't know if it's a issue or I'm doing something wrong but after more than 20 VM with fresh installs and trying anything from odoo v10, v11 and many other things I don't know what else I can do.

This is the log from my last fresh install:
[odoo-server.log](https://github.com/Yenthe666/InstallScript/files/1859663/odoo-server.log)

**Comment by Yenthe666** [comment]
Hi @rogerv95,

Wow, you've got quite some different issues running through eachother here.
For the backup module: it is clear that you have not installed the dependencies or that your system cannot detect them. Output of the log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1312, in __call__
    self.load_addons()
  File "/odoo/odoo-server/odoo/http.py", line 1334, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/odoo/odoo-server/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>
    
  File "/odoo/custom/addons/auto_backup/models/__init__.py", line 3, in <module>
    from . import db_backup
  File "/odoo/custom/addons/auto_backup/models/db_backup.py", line 27, in <module>
    'This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)')
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)
```

The issue about your reports is either the `wkhtmltopdf` that is failing or because you haven't configured the `report.url` or `web.base.url` to point to `127.0.0.1:8069` so that Odoo can find the `wkhtmltopdf` to print your reports cleanly.

**Comment by hengsoheak** [comment]
How to configure report.url

**Comment by Yenthe666** [comment]
Under settings > technical parameter (with developer mode activated)

**Comment by chris001** [comment]
@rogerv95 
You should try installing 11 with my updated version of this install script, in the PR "Big Update" #74 I've fixed many bugs and made the script much more safe from the possibility of user errors.

**Comment by Yenthe666** [comment]
@chris001,

If you read the whole initial topic it looks to me like the Odoo itself is working though. It is misconfiguration and in deployment of the backup module. 
The core seems to be fine.

**Comment by rogerv95** [comment]
@Yenthe666 @chris001 
Thanks for your support! I made a new clean install from scratch with the script from "Big Update"  and after configuring `web.base.url` and `report.url` I've got `wkhtmltopdf` working exporting all the reports in the correct format. After that I installed all the odoo modules I'm planning to use and after that installed pysftp and uploaded the backup module and everything seems fine now. 
I don't understand why it's working now because the only different thing in all the setup is the install script.
But besides that, everything looks fine from the UI perspective but I'm still seeing some errors on the log `ERROR odoo.http JSON request` and `ie: python module not available "phonenumbers"` I've been able to solve the python module errors installing all the missing modules but not the JSON errors.
[odoo-server.log](https://github.com/Yenthe666/InstallScript/files/1864549/odoo-server.log)


Also while running the install script I've got some errors when it was trying to `chown` and `chmod` with the odoo user. I'm uploading the terminal output because the errors don't show on the install log

[output.txt](https://github.com/Yenthe666/InstallScript/files/1864556/output.txt)

**Comment by chris001** [comment]
@rogerv95 @Yenthe666 My Big Update setup script has fixed a number of subtle yet serious bugs, which have been present since the original author wrote it.  This is why odoo's working smoothly now for you.
I'll add the `phonenumbers` python module to the script, thanks for reporting that one.

**Comment by Yenthe666** [comment]
Awesome to hear!
@chris001 please resolve the merge conflicts on the PR, I really want to land it in a branch!

**Comment by sachinodoo19** [comment]
Restarting odoo-server: start-stop-daemon: warning: failed to kill 22218: No such process
start-stop-daemon: unable to set gid to 129 (Operation not permitted)
odoo-server.
 i found these issue when installed script as describe
