### ISSUE TITLE
postgresql access via pgadmin

### ISSUE THREAD

**Issue by davidogles** [Yenthe666/InstallScript#95]
Using the script, all installs correctly and can use.  But when trying to access database remotely via pgadmin, getting the following error:
could not connect to server: Connection refused (0x0000274D/10061) Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 5433?

I can connect to other odoo remote db's that I installed all manually.  checked the pg conf files and all are exactly the same.  It seems that the postgres user "odoo" that it builds assigns a different password other than the OE_superuser that is defined in the script.  Any insight on to what the postgres user "odoo" password is set to?

**Comment by chris001** [comment]
For anti hacker security, the user `odoo` is a system user with no password, so that remote connect (by hackers) is not possible.
If you want to set a strong password, you can, and then connect remotely with it:
```
python3 -c 'import base64, os; print(base64.b64encode(os.urandom(24)))'` #generates random 32 character password
passwd odoo #copy paste the above random 32 character password
passwd -S odoo  #show the password status of the user odoo
```

**Comment by Yenthe666** [comment]
Hi @davidogles,

As @chris001 has answered we create a passwordless user with the installer for safety reasons.
When you follow his guidance or just set a password with `sudo passwd user` you'll have a password to authenticate with.

P.S: Don't forget about the PostgreSQL configuration about remote connections too.

**Comment by davidogles** [comment]
thanks

**Comment by shaiazran** [comment]
Hi,
i follow the instructions and change the password and cannot connect locally ..

psql -U odoo -h localhost -p 5432 odoo
Password for user odoo: XXXXX
psql: FATAL:  password authentication failed for user "odoo"
FATAL:  password authentication failed for user "odoo"

Pls advise. 
tnx shaya
