### ISSUE TITLE
odoo not start

### ISSUE THREAD

**Issue by afrati** [Yenthe666/InstallScript#96]
hi 
after install odoo i can to access to home page but i can't view anything
see this image
how can solve ?

![image](https://user-images.githubusercontent.com/33252107/39315121-335fabea-4976-11e8-99f8-b69fe66ec6b8.png)

**Comment by chris001** [comment]
1. Try watching the log in the console:
`tail -f /var/log/odoo/odoo-server`
2. Then reload the browser page (click reload icon or press `ctrl`+`r`).
3. See what are the `odoo-server` log messages that appear in your console. Watch especially for `ERROR`, `FATAL`, `WARNING`, `Exception`, etc.
4. Copy/paste those interesting log results here - (first remove/repalce private information, IP address, domain name, etc.).

**Comment by xinuxnt** [comment]
Same issue, not logs file at all, /var/log/odoo/   empty.     service status started and active

**Comment by chris001** [comment]
Try these commands to see if it's really running:
* `ps aux | grep odoo`
* `systemctl -xe`

**Comment by xinuxnt** [comment]
this is the result
root      8905  0.0  0.0  12784   992 pts/1    S+   21:45   0:00 grep odoo

**Comment by chris001** [comment]
* That output means odoo isn't really running.  When odoo's running the output shows `python3`.
* What version of ubuntu OS you running.
* How much RAM does this vm have.
* You should manually start odoo and watch the console for errors:
```
cd /home/odoo/odoo-server
./start.sh
```

**Comment by xinuxnt** [comment]
![image](https://user-images.githubusercontent.com/19438179/39365694-3f1870e2-4a08-11e8-88df-178825dc611d.png)

**Comment by chris001** [comment]
Which linux distro are you using?
It is unusual for `sudo` not to be installed, but it may simply not be in your Path. 
Try `/usr/bin/sudo command`
If `sudo` is not installed, install it with `apt install sudo`

**Comment by afrati** [comment]
now odoo start but i'm in this situation 
![image](https://user-images.githubusercontent.com/33252107/39393328-6f4c94e8-4ac4-11e8-87cf-45c0f8ed3957.png)

**Comment by afrati** [comment]
ok now it work but i have another problem, i open  new issues

**Comment by xinuxnt** [comment]
The same for me

**Comment by gabrielmoralessaez** [comment]
How did you solve the problem? 
You should have uploaded the solution for everyone

**Comment by chris001** [comment]
His problem was, `sudo`  command wasn't installed.
Solution was to install `sudo` command.
`apt-get install sudo`
`service odoo-server start`  (Use whatever your odoo server is named on your system).
