### ISSUE TITLE
debian install script outdated

### ISSUE THREAD

**Issue by xinuxnt** [Yenthe666/InstallScript#97]
Debian version of the script is out to date and get several errors during installation

---- Update Server ----

---- Install dialog ----

---- Upgrade Server ----

---- Install PostgreSQL Repo Key ----
OK

---- Install PostgreSQL Server 9.6 ----

---- Creating the ODOO PostgreSQL User  ----

---- Install packages ----

---- Install wkhtml and place shortcuts on correct place for ODOO 10 ----
This package is uninstallable
Dependency is not satisfiable: libpng12-0

---- Create ODOO system user ----

---- Create Log and data directory ----
mkdir: cannot create directory ‘/var/log/odoo’: File exists

==== Installing ODOO Server ====
fatal: destination path '/odoo/odoo-server' already exists and is not an empty directory.

---- Create custom module directory ----
mkdir: cannot create directory ‘/odoo/custom’: File exists
mkdir: cannot create directory ‘/odoo/custom/addons’: File exists

---- Setting permissions on home folder ----
* Create server config file

---- Install python packages and virtualenv ----
  Failed building wheel for psutil
  Failed building wheel for pyldap
  Failed building wheel for reportlab
Command "/odoo/python_env/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tvV805/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-JGt_NB/install-record.txt --single-version-externally-managed --compile --install-headers /odoo/python_env/include/site/python2.7/psutil" failed with error code 1 in /tmp/pip-install-tvV805/psutil/
* Create service file
* Security Init File
* Start ODOO on Startup
Synchronizing state of odoo-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable odoo-server
* Starting Odoo Service

**Comment by chris001** [comment]
Yes the debian version is out of date.
Your options are:
1. Try the regular version of the script. It's made for ubuntu 14+ so it'll probably work fine on debian 9.
2. Download the `.deb` package for debian + ubuntu from https://www.odoo.com/page/download
3. Fix the debian script and make a pull request!  But I think you don't need to, because option 1, the regular ubuntu version should work fine on debian 9.

**Comment by Yenthe666** [comment]
I've removed it from the newest version as it was really hopelessly outdated now. Thanks for the feedback.
