### ISSUE TITLE
Can't add custom apps

### ISSUE THREAD

**Issue by afrati** [Yenthe666/InstallScript#98]
hi , i have a problem when i try to install custom app
i go to setting 
click upgrade apps list
![image](https://user-images.githubusercontent.com/33252107/39394231-d26d0106-4acf-11e8-9fa7-ca1c910aba15.png)
i click on this button, but the windows disappeared
![image](https://user-images.githubusercontent.com/33252107/39394240-f0e8705c-4acf-11e8-8015-562fb4b17196.png)
how can solve it ?

**Comment by Yenthe666** [comment]
Hi,

Have a look at your logfile. Either your assets failed compiling or you have access rights issues or you're missing a dependency. 
Post back the errors from the log please.

**Comment by afrati** [comment]
this is my log file
[log.txt](https://github.com/Yenthe666/InstallScript/files/1957601/log.txt)

**Comment by chris001** [comment]
Can you verify all the addons directories are real existing directories on your system, especially this first one, it probably doesn't exist, and it shouldn't, the installer didn't create it, or it was leftover from an old version and should be removed from your `addons_path`:
```
ls -la /odoo/.local/share/Odoo/addons/11.0
ls -la /home/odoo/enterprise/addons
ls -la /home/odoo/odoo-server/addons
ls -la /home/odoo/custom/addons
ls -la /home/odoo/odoo-server/odoo/addons
```

* To remove from `addons_path` :
`nano /etc/odoo/odoo-server.conf`
* Edit the line `addons_path = ` and remove the path `/odoo/.local/share/Odoo/addons/11.0` from the comma-separated list of paths.
